### ISSUE TITLE
Hugoai Bedside lamp not working

### ISSUE THREAD

**Issue by RaptorPR443** [tuya/tuya-home-assistant#109]
Device - Hugoai Bedside lamp
Connected app - Smart Life
Issue - 
while it recognizes the device, doesn't allow to turn off/on, rgb/cool to warm white control.
it can only control the brightness in Home Assistant.

with the old tuya integration everything works perfectly.

**Comment by tsutsuku** [comment]
@RaptorPR443  Can you provide the logs?

**Comment by RaptorPR443** [comment]
> @RaptorPR443 Can you provide the logs?

Last logged: 7:13:59 PM

Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/site-packages/tuya_iot/openmq.py", line 173, in run
    time.sleep(self.mq_config.expireTime - 60)
AttributeError: 'TuyaOpenMQ' object has no attribute 'mq_config'


Logger: tuya iot
Source: /usr/local/lib/python3.9/site-packages/tuya_iot/openmq.py:178
First occurred: 7:13:59 PM (1 occurrences)
Last logged: 7:13:59 PM

error while get mqtt config

if this is not what you want, you can guide me to find the logs you need.

**Comment by tsutsuku** [comment]
https://github.com/tuya/tuya-home-assistant/wiki/How-to-Get-the-Log

**Comment by RaptorPR443** [comment]
> https://github.com/tuya/tuya-home-assistant/wiki/How-to-Get-the-Log

2021-07-19 23:44:13 DEBUG (SyncWorker_5) [tuya iot] Response: {
"result": [
{
"active_time": 1626750244,
"biz_type": 18,
"category": "cz",
"create_time": 1626750244,
"icon": "smart/icon/ay1514359068372Hd98B/30ffb2da3044ba5b6fd3cefa4a5a1f6c.jpg",
"id": "eb8b761d7ce9694fe8dwiq",
"ip": "72.50.4.48",
"lat": "18.3918311",
"local_key": "7ebe6edf06ccfb6a",
"lon": "-66.9285115",
"name": "Switch Baño",
"online": true,
"owner_id": "42383586",
"product_id": "viv1giuyu2tk4kt4",
"product_name": "Smart Socket",
"status": [
{
"code": "switch_1",
"value": true
},
{
"code": "countdown_1",
"value": 0
}
],
"sub": false,
"time_zone": "-04:00",
"uid": "az1622589499903AWRZ1",
"update_time": 1626750286,
"uuid": "8b770ab2b88bd1c9"
},
{
"active_time": 1622589722,
"biz_type": 18,
"category": "dj",
"create_time": 1622589722,
"icon": "smart/icon/ay15289660454285DnGN/c38fd97e440302a77389923674718413.jpg",
"id": "ebe61ff5523e4ccd569xvb",
"ip": "72.50.4.119",
"lat": "18.3918719",
"local_key": "0d08c77a48fc0b05",
"lon": "-66.9285154",
"name": "Night Light Nenes",
"online": true,
"owner_id": "42383586",
"product_id": "poccfmsm2xhnostn",
"product_name": "Table Lamp - Hugo",
"status": [
{
"code": "switch_led",
"value": true
},
{
"code": "work_mode",
"value": "white"
},
{
"code": "bright_value_v2",
"value": 29
},
{
"code": "temp_value_v2",
"value": 0
},
{
"code": "colour_data_v2",
"value": "{\"h\":330,\"s\":857,\"v\":1}"
},
{
"code": "scene_data_v2",
"value": "{\"scene_num\":1,\"scene_units\":[{\"bright\":200,\"h\":0,\"s\":0,\"temperature\":0,\"unit_change_mode\":\"static\",\"unit_gradient_duration\":13,\"unit_switch_duration\":13,\"v\":0}]}"
},
{
"code": "countdown_1",
"value": 0
},
{
"code": "music_data",
"value": ""
},
{
"code": "control_data",
"value": ""
}
],
"sub": false,
"time_zone": "-04:00",
"uid": "az1622589499903AWRZ1",
"update_time": 1626442209,
"uuid": "c389400b4ab4aedd"
}
],
"success": true,
"t": 1626752653833
}
2021-07-19 23:44:13 DEBUG (SyncWorker_5) [tuya iot] Request: method = GET, url = https://openapi.tuyaus.com/v1.0/devices/eb8b761d7ce9694fe8dwiq/specifications, params = None, body = None, headers = {'client_id': '', 'sign': '', 'sign_method': 'HMAC-SHA256', 'access_token': '', 't': '1626752653903', 'lang': 'en'}
2021-07-19 23:44:14 DEBUG (SyncWorker_5) [tuya iot] Response: {
"result": {
"category": "cz",
"functions": [
{
"code": "switch_1",
"type": "Boolean",
"values": "{}"
},
{
"code": "countdown_1",
"type": "Integer",
"values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
}
],
"status": [
{
"code": "switch_1",
"type": "Boolean",
"values": "{}"
},
{
"code": "countdown_1",
"type": "Integer",
"values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
}
]
},
"success": true,
"t": 1626752654015
}
2021-07-19 23:44:14 DEBUG (SyncWorker_5) [tuya iot] Request: method = GET, url = https://openapi.tuyaus.com/v1.0/devices/ebe61ff5523e4ccd569xvb/specifications, params = None, body = None, headers = {'client_id': 'p9qsut9yaq89gv27amn1', 'sign': 'F51C4483A4033E73C27585494E5ED1BD71BF60AD70941307088A2F692549F4EF', 'sign_method': 'HMAC-SHA256', 'access_token': 'cee68addc3ce4228f08a937ccef3a18a', 't': '1626752654090', 'lang': 'en'}
2021-07-19 23:44:14 DEBUG (Thread-4) [tuya iot] Response: {
"code": 28841101,
"msg": "No permissions. This API is not subscribed.",
"success": false,
"t": 1626752654110
}
2021-07-19 23:44:14 ERROR (Thread-4) [tuya iot] error while get mqtt config
2021-07-19 23:44:14 DEBUG (SyncWorker_5) [tuya iot] Response: {
"result": {
"category": "dj",
"functions": [
{
"code": "switch_led",
"type": "Boolean",
"values": "{}"
},
{
"code": "work_mode",
"type": "Enum",
"values": "{\"range\":[\"white\",\"colour\",\"scene\",\"music\"]}"
},
{
"code": "bright_value_v2",
"type": "Integer",
"values": "{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}"
},
{
"code": "temp_value_v2",
"type": "Integer",
"values": "{\"min\":0,\"max\":1000,\"scale\":0,\"step\":1}"
},
{
"code": "colour_data_v2",
"type": "Json",
"values": "{}"
},
{
"code": "scene_data_v2",
"type": "Json",
"values": "{}"
},
{
"code": "countdown_1",
"type": "Integer",
"values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
},
{
"code": "music_data",
"type": "Json",
"values": "{}"
},
{
"code": "control_data",
"type": "Json",
"values": "{}"
}
],
"status": [
{
"code": "switch_led",
"type": "Boolean",
"values": "{}"
},
{
"code": "work_mode",
"type": "Enum",
"values": "{\"range\":[\"white\",\"colour\",\"scene\",\"music\"]}"
},
{
"code": "bright_value_v2",
"type": "Integer",
"values": "{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}"
},
{
"code": "temp_value_v2",
"type": "Integer",
"values": "{\"min\":0,\"max\":1000,\"scale\":0,\"step\":1}"
},
{
"code": "colour_data_v2",
"type": "Json",
"values": "{}"
},
{
"code": "scene_data_v2",
"type": "Json",
"values": "{}"
},
{
"code": "countdown_1",
"type": "Integer",
"values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
},
{
"code": "music_data",
"type": "Json",
"values": "{}"
},
{
"code": "control_data",
"type": "Json",
"values": "{}"
}
]
},
"success": true,
"t": 1626752654200
}
2021-07-19 23:44:15 INFO (MainThread) [custom_components.tuya_v2] init support type->['switch', 'fan', 'cover', 'climate', 'light', 'sensor', 'binary_sensor', 'humidifier', 'number', 'vacuum', 'select']
2021-07-19 23:44:15 INFO (MainThread) [custom_components.tuya_v2] tuya async platform-->switch
2021-07-19 23:44:15 INFO (MainThread) [custom_components.tuya_v2] tuya async platform-->fan
2021-07-19 23:44:15 INFO (MainThread) [custom_components.tuya_v2] tuya async platform-->cover
2021-07-19 23:44:15 INFO (MainThread) [custom_components.tuya_v2] tuya async platform-->climate
2021-07-19 23:44:15 INFO (MainThread) [custom_components.tuya_v2] tuya async platform-->light
2021-07-19 23:44:15 INFO (MainThread) [custom_components.tuya_v2] tuya async platform-->sensor
2021-07-19 23:44:15 INFO (MainThread) [custom_components.tuya_v2] tuya async platform-->binary_sensor
2021-07-19 23:44:15 INFO (MainThread) [custom_components.tuya_v2] tuya async platform-->humidifier
2021-07-19 23:44:15 INFO (MainThread) [custom_components.tuya_v2] tuya async platform-->number
2021-07-19 23:44:15 INFO (MainThread) [custom_components.tuya_v2] tuya async platform-->vacuum
2021-07-19 23:44:15 INFO (MainThread) [custom_components.tuya_v2] tuya async platform-->select
2021-07-19 23:44:17 INFO (MainThread) [custom_components.tuya_v2.switch] switch init
2021-07-19 23:44:17 INFO (MainThread) [custom_components.tuya_v2.switch] switch add-> ['eb8b761d7ce9694fe8dwiq']
2021-07-19 23:44:17 INFO (MainThread) [custom_components.tuya_v2.sensor] sensor init
2021-07-19 23:44:17 INFO (MainThread) [custom_components.tuya_v2.sensor] sensor add-> ['eb8b761d7ce9694fe8dwiq', 'ebe61ff5523e4ccd569xvb']
2021-07-19 23:44:17 INFO (MainThread) [custom_components.tuya_v2.binary_sensor] binary sensor init
2021-07-19 23:44:17 INFO (MainThread) [custom_components.tuya_v2.binary_sensor] binary sensor add->[]
2021-07-19 23:44:17 INFO (MainThread) [custom_components.tuya_v2.light] light init
2021-07-19 23:44:17 INFO (MainThread) [custom_components.tuya_v2.light] light add-> ['ebe61ff5523e4ccd569xvb']
2021-07-19 23:44:17 INFO (MainThread) [custom_components.tuya_v2.cover] cover init
2021-07-19 23:44:17 INFO (MainThread) [custom_components.tuya_v2.cover] cover add-> []
2021-07-19 23:44:17 INFO (MainThread) [custom_components.tuya_v2.fan] fan init
2021-07-19 23:44:17 INFO (MainThread) [custom_components.tuya_v2.fan] fan add-> []
2021-07-19 23:44:17 INFO (MainThread) [custom_components.tuya_v2.climate] climate init
2021-07-19 23:44:17 INFO (MainThread) [custom_components.tuya_v2.climate] climate add->[]
2021-07-19 23:44:17 INFO (MainThread) [custom_components.tuya_v2.humidifier] humidifier init
2021-07-19 23:44:17 INFO (MainThread) [custom_components.tuya_v2.humidifier] humidifier add-> []
2021-07-19 23:44:17 INFO (MainThread) [custom_components.tuya_v2.vacuum] vacuum init
2021-07-19 23:44:17 INFO (MainThread) [custom_components.tuya_v2.vacuum] vacuum add -> []
2021-07-19 23:44:17 INFO (MainThread) [custom_components.tuya_v2.select] select init
2021-07-19 23:44:17 INFO (MainThread) [custom_components.tuya_v2.select] select add-> []
2021-07-19 23:44:17 INFO (MainThread) [custom_components.tuya_v2.number] number init
2021-07-19 23:44:17 INFO (MainThread) [custom_components.tuya_v2.number] number add-> []
2021-07-19 23:44:17 DEBUG (MainThread) [custom_components.tuya_v2.light] brightness id->
ebe61ff5523e4ccd569xvb
work_mode->,
white,
; check true->,
False
2021-07-19 23:45:12 DEBUG (SyncWorker_0) [tuya iot] Request: method = POST, url = https://openapi.tuyaus.com/v1.0/devices/ebe61ff5523e4ccd569xvb/commands, params = None, body = {'commands': [{'code': 'switch_led', 'value': False}]}, headers = {'client_id': 'p9qsut9yaq89gv27amn1', 'sign': '974D76E81CD0E6869548E60945BE5EE4B80AA8B7F47ECC474D38846F9887C67B', 'sign_method': 'HMAC-SHA256', 'access_token': 'cee68addc3ce4228f08a937ccef3a18a', 't': '1626752712200', 'lang': 'en'}
2021-07-19 23:45:12 DEBUG (SyncWorker_0) [tuya iot] Response: {
"result": true,
"success": true,
"t": 1626752712329
}
2021-07-19 23:45:17 DEBUG (SyncWorker_0) [tuya iot] Request: method = POST, url = https://openapi.tuyaus.com/v1.0/devices/ebe61ff5523e4ccd569xvb/commands, params = None, body = {'commands': [{'code': 'switch_led', 'value': False}]}, headers = {'client_id': '', 'sign': '', 'sign_method': 'HMAC-SHA256', 'access_token': 'a', 't': '1626752717705', 'lang': 'en'}
2021-07-19 23:45:18 DEBUG (SyncWorker_0) [tuya iot] Response: {
"result": true,
"success": true,
"t": 1626752717818
}
2021-07-19 23:45:21 DEBUG (SyncWorker_0) [tuya iot] Request: method = POST, url = https://openapi.tuyaus.com/v1.0/devices/ebe61ff5523e4ccd569xvb/commands, params = None, body = {'commands': [{'code': 'switch_led', 'value': False}]}, headers = {'client_id': ', 'sign': '', 'sign_method': 'HMAC-SHA256', 'access_token': '', 't': '1626752721802', 'lang': 'en'}
2021-07-19 23:45:21 DEBUG (SyncWorker_0) [tuya iot] Response: {
"result": true,
"success": true,
"t": 1626752721904
}
2021-07-19 23:45:28 DEBUG (SyncWorker_4) [custom_components.tuya_v2.light] light kwargs-> {'hs_color': (225.0, 14.285714285714285)}
2021-07-19 23:45:28 DEBUG (SyncWorker_4) [custom_components.tuya_v2.light] brightness id->
ebe61ff5523e4ccd569xvb
work_mode->,
white,
; check true->,
False
2021-07-19 23:45:28 DEBUG (SyncWorker_0) [tuya iot] Request: method = POST, url = https://openapi.tuyaus.com/v1.0/devices/ebe61ff5523e4ccd569xvb/commands, params = None, body = {'commands': [{'code': 'switch_led', 'value': True}, {'code': 'colour_data_v2', 'value': '{"h": 225, "s": 143, "v": 16}'}, {'code': 'work_mode', 'value': 'colour'}]}, headers = {'client_id': '', 'lang': 'en'}
2021-07-19 23:45:28 DEBUG (SyncWorker_0) [tuya iot] Response: {
"result": true,
"success": true,
"t": 1626752728526
}
2021-07-19 23:45:29 DEBUG (SyncWorker_10) [custom_components.tuya_v2.light] light kwargs-> {'hs_color': (255.0, 57.14285714285714)}
2021-07-19 23:45:29 DEBUG (SyncWorker_10) [custom_components.tuya_v2.light] brightness id->
ebe61ff5523e4ccd569xvb
work_mode->,
white,
; check true->,
False
2021-07-19 23:45:29 DEBUG (SyncWorker_0) [tuya iot] Request: method = POST, url = https://openapi.tuyaus.com/v1.0/devices/ebe61ff5523e4ccd569xvb/commands, params = None, body = {'commands': [{'code': 'switch_led', 'value': True}, {'code': 'colour_data_v2', 'value': '{"h": 255, "s": 571, "v": 16}'}, {'code': 'work_mode', 'value': 'colour'}]}, headers = {'client_id': ', 'lang': 'en'}
2021-07-19 23:45:29 DEBUG (SyncWorker_0) [tuya iot] Response: {
"result": true,
"success": true,
"t": 1626752729489
}
2021-07-19 23:45:31 DEBUG (SyncWorker_2) [custom_components.tuya_v2.light] light kwargs-> {'hs_color': (270.0, 100.0)}
2021-07-19 23:45:31 DEBUG (SyncWorker_2) [custom_components.tuya_v2.light] brightness id->
ebe61ff5523e4ccd569xvb
work_mode->,
white,
; check true->,
False
2021-07-19 23:45:31 DEBUG (SyncWorker_0) [tuya iot] Request: method = POST, url = https://openapi.tuyaus.com/v1.0/devices/ebe61ff5523e4ccd569xvb/commands, params = None, body = {'commands': [{'code': 'switch_led', 'value': True}, {'code': 'colour_data_v2', 'value': '{"h": 270, "s": 1000, "v": 16}'}, {'code': 'work_mode', 'value': 'colour'}]}, headers = {'client_id': , 'lang': 'en'}
2021-07-19 23:45:31 DEBUG (SyncWorker_0) [tuya iot] Response: {
"result": true,
"success": true,
"t": 1626752731810
}
2021-07-19 23:45:32 DEBUG (SyncWorker_5) [custom_components.tuya_v2.light] light kwargs-> {'brightness': 117}
2021-07-19 23:45:32 DEBUG (SyncWorker_0) [tuya iot] Request: method = POST, url = https://openapi.tuyaus.com/v1.0/devices/ebe61ff5523e4ccd569xvb/commands, params = None, body = {'commands': [{'code': 'switch_led', 'value': True}, {'code': 'bright_value_v2', 'value': 464}]}, headers = {'client_id': '', 'lang': 'en'}
2021-07-19 23:45:32 DEBUG (SyncWorker_0) [tuya iot] Response: {
"result": true,
"success": true,
"t": 1626752732823
}
2021-07-19 23:45:35 DEBUG (SyncWorker_6) [custom_components.tuya_v2.light] light kwargs-> {'hs_color': (300.0, 85.71428571428571)}
2021-07-19 23:45:35 DEBUG (SyncWorker_6) [custom_components.tuya_v2.light] brightness id->
ebe61ff5523e4ccd569xvb
work_mode->,
white,
; check true->,
False
2021-07-19 23:45:35 DEBUG (SyncWorker_0) [tuya iot] Request: method = POST, url = https://openapi.tuyaus.com/v1.0/devices/ebe61ff5523e4ccd569xvb/commands, params = None, body = {'commands': [{'code': 'switch_led', 'value': True}, {'code': 'colour_data_v2', 'value': '{"h": 300, "s": 857, "v": 16}'}, {'code': 'work_mode', 'value': 'colour'}]}, headers = {'client_id': '', 'lang': 'en'}
2021-07-19 23:45:35 DEBUG (SyncWorker_0) [tuya iot] Response: {
"result": true,
"success": true,
"t": 1626752735209
}
2021-07-19 23:45:36 DEBUG (SyncWorker_11) [custom_components.tuya_v2.light] light kwargs-> {'hs_color': (285.0, 100.0)}
2021-07-19 23:45:36 DEBUG (SyncWorker_11) [custom_components.tuya_v2.light] brightness id->
ebe61ff5523e4ccd569xvb
work_mode->,
white,
; check true->,
False
2021-07-19 23:45:36 DEBUG (SyncWorker_0) [tuya iot] Request: method = POST, url = https://openapi.tuyaus.com/v1.0/devices/ebe61ff5523e4ccd569xvb/commands, params = None, body = {'commands': [{'code': 'switch_led', 'value': True}, {'code': 'colour_data_v2', 'value': '{"h": 285, "s": 1000, "v": 16}'}, {'code': 'work_mode', 'value': 'colour'}]}, headers = {'client_id': '', 'lang': 'en'}
2021-07-19 23:45:36 DEBUG (SyncWorker_0) [tuya iot] Response: {
"result": true,
"success": true,
"t": 1626752736901
}
2021-07-19 23:45:38 DEBUG (SyncWorker_5) [custom_components.tuya_v2.light] light kwargs-> {'hs_color': (165.0, 85.71428571428571)}
2021-07-19 23:45:38 DEBUG (SyncWorker_5) [custom_components.tuya_v2.light] brightness id->
ebe61ff5523e4ccd569xvb
work_mode->,
white,
; check true->,
False
2021-07-19 23:45:38 DEBUG (SyncWorker_0) [tuya iot] Request: method = POST, url = https://openapi.tuyaus.com/v1.0/devices/ebe61ff5523e4ccd569xvb/commands, params = None, body = {'commands': [{'code': 'switch_led', 'value': True}, {'code': 'colour_data_v2', 'value': '{"h": 165, "s": 857, "v": 16}'}, {'code': 'work_mode', 'value': 'colour'}]}, headers = {'client_id': '', 'lang': 'en'}
2021-07-19 23:45:38 DEBUG (SyncWorker_0) [tuya iot] Response: {
"result": true,
"success": true,
"t": 1626752738710
}
2021-07-19 23:45:39 DEBUG (SyncWorker_11) [custom_components.tuya_v2.light] light kwargs-> {'hs_color': (150.0, 85.71428571428571)}
2021-07-19 23:45:39 DEBUG (SyncWorker_11) [custom_components.tuya_v2.light] brightness id->
ebe61ff5523e4ccd569xvb
work_mode->,
white,
; check true->,
False
2021-07-19 23:45:39 DEBUG (SyncWorker_0) [tuya iot] Request: method = POST, url = https://openapi.tuyaus.com/v1.0/devices/ebe61ff5523e4ccd569xvb/commands, params = None, body = {'commands': [{'code': 'switch_led', 'value': True}, {'code': 'colour_data_v2', 'value': '{"h": 150, "s": 857, "v": 16}'}, {'code': 'work_mode', 'value': 'colour'}]}, headers = {'client_id': ', 'lang': 'en'}
2021-07-19 23:45:40 DEBUG (SyncWorker_0) [tuya iot] Response: {
"result": true,
"success": true,
"t": 1626752739989
}
2021-07-19 23:45:40 DEBUG (SyncWorker_7) [custom_components.tuya_v2.light] light kwargs-> {'hs_color': (150.0, 85.71428571428571)}
2021-07-19 23:45:40 DEBUG (SyncWorker_7) [custom_components.tuya_v2.light] brightness id->
ebe61ff5523e4ccd569xvb
work_mode->,
white,
; check true->,
False
2021-07-19 23:45:40 DEBUG (SyncWorker_0) [tuya iot] Request: method = POST, url = https://openapi.tuyaus.com/v1.0/devices/ebe61ff5523e4ccd569xvb/commands, params = None, body = {'commands': [{'code': 'switch_led', 'value': True}, {'code': 'colour_data_v2', 'value': '{"h": 150, "s": 857, "v": 16}'}, {'code': 'work_mode', 'value': 'colour'}]}, headers = {'client_id': '', 'lang': 'en'}
2021-07-19 23:45:40 DEBUG (SyncWorker_0) [tuya iot] Response: {
"result": true,
"success": true,
"t": 1626752740556
}
2021-07-19 23:45:42 DEBUG (SyncWorker_9) [custom_components.tuya_v2.light] light kwargs-> {'hs_color': (120.0, 100.0)}
2021-07-19 23:45:42 DEBUG (SyncWorker_9) [custom_components.tuya_v2.light] brightness id->
ebe61ff5523e4ccd569xvb
work_mode->,
white,
; check true->,
False
2021-07-19 23:45:42 DEBUG (SyncWorker_0) [tuya iot] Request: method = POST, url = https://openapi.tuyaus.com/v1.0/devices/ebe61ff5523e4ccd569xvb/commands, params = None, body = {'commands': [{'code': 'switch_led', 'value': True}, {'code': 'colour_data_v2', 'value': '{"h": 120, "s": 1000, "v": 16}'}, {'code': 'work_mode', 'value': 'colour'}]}, headers = {'client_id': '', 'lang': 'en'}
2021-07-19 23:45:42 DEBUG (SyncWorker_0) [tuya iot] Response: {
"result": true,
"success": true,
"t": 1626752742897
}
2021-07-19 23:45:45 DEBUG (SyncWorker_8) [custom_components.tuya_v2.light] light kwargs-> {'hs_color': (105.0, 100.0)}
2021-07-19 23:45:45 DEBUG (SyncWorker_8) [custom_components.tuya_v2.light] brightness id->
ebe61ff5523e4ccd569xvb
work_mode->,
white,
; check true->,
False
2021-07-19 23:45:45 DEBUG (SyncWorker_0) [tuya iot] Request: method = POST, url = https://openapi.tuyaus.com/v1.0/devices/ebe61ff5523e4ccd569xvb/commands, params = None, body = {'commands': [{'code': 'switch_led', 'value': True}, {'code': 'colour_data_v2', 'value': '{"h": 105, "s": 1000, "v": 16}'}, {'code': 'work_mode', 'value': 'colour'}]}, headers = {'client_id': '', 'lang': 'en'}
2021-07-19 23:45:45 DEBUG (SyncWorker_0) [tuya iot] Response: {
"result": true,
"success": true,
"t": 1626752745786
}
2021-07-19 23:45:48 DEBUG (SyncWorker_4) [custom_components.tuya_v2.light] light kwargs-> {'hs_color': (90.0, 100.0)}
2021-07-19 23:45:48 DEBUG (SyncWorker_4) [custom_components.tuya_v2.light] brightness id->
ebe61ff5523e4ccd569xvb
work_mode->,
white,
; check true->,
False
2021-07-19 23:45:48 DEBUG (SyncWorker_0) [tuya iot] Request: method = POST, url = https://openapi.tuyaus.com/v1.0/devices/ebe61ff5523e4ccd569xvb/commands, params = None, body = {'commands': [{'code': 'switch_led', 'value': True}, {'code': 'colour_data_v2', 'value': '{"h": 90, "s": 1000, "v": 16}'}, {'code': 'work_mode', 'value': 'colour'}]}, headers = {'client_id': '', 'lang': 'en'}
2021-07-19 23:45:48 DEBUG (SyncWorker_0) [tuya iot] Response: {
"result": true,
"success": true,
"t": 1626752748497
}
2021-07-19 23:45:49 DEBUG (SyncWorker_11) [custom_components.tuya_v2.light] light kwargs-> {'hs_color': (75.0, 100.0)}
2021-07-19 23:45:49 DEBUG (SyncWorker_11) [custom_components.tuya_v2.light] brightness id->
ebe61ff5523e4ccd569xvb
work_mode->,
white,
; check true->,
False
2021-07-19 23:45:49 DEBUG (SyncWorker_0) [tuya iot] Request: method = POST, url = https://openapi.tuyaus.com/v1.0/devices/ebe61ff5523e4ccd569xvb/commands, params = None, body = {'commands': [{'code': 'switch_led', 'value': True}, {'code': 'colour_data_v2', 'value': '{"h": 75, "s": 1000, "v": 16}'}, {'code': 'work_mode', 'value': 'colour'}]}, headers = {'client_id': '', 'lang': 'en'}
2021-07-19 23:45:49 DEBUG (SyncWorker_0) [tuya iot] Response: {
"result": true,
"success": true,
"t": 1626752749845
}
2021-07-19 23:45:50 DEBUG (SyncWorker_5) [custom_components.tuya_v2.light] light kwargs-> {'hs_color': (60.0, 100.0)}
2021-07-19 23:45:50 DEBUG (SyncWorker_5) [custom_components.tuya_v2.light] brightness id->
ebe61ff5523e4ccd569xvb
work_mode->,
white,
; check true->,
False
2021-07-19 23:45:50 DEBUG (SyncWorker_0) [tuya iot] Request: method = POST, url = https://openapi.tuyaus.com/v1.0/devices/ebe61ff5523e4ccd569xvb/commands, params = None, body = {'commands': [{'code': 'switch_led', 'value': True}, {'code': 'colour_data_v2', 'value': '{"h": 60, "s": 1000, "v": 16}'}, {'code': 'work_mode', 'value': 'colour'}]}, headers = {'client_id': ', 'lang': 'en'}
2021-07-19 23:45:50 DEBUG (SyncWorker_0) [tuya iot] Response: {
"result": true,
"success": true,
"t": 1626752750806
}
2021-07-19 23:45:52 DEBUG (SyncWorker_0) [custom_components.tuya_v2.light] light kwargs-> {'hs_color': (45.0, 100.0)}
2021-07-19 23:45:52 DEBUG (SyncWorker_0) [custom_components.tuya_v2.light] brightness id->
ebe61ff5523e4ccd569xvb
work_mode->,
white,
; check true->,
False
2021-07-19 23:45:52 DEBUG (SyncWorker_0) [tuya iot] Request: method = POST, url = https://openapi.tuyaus.com/v1.0/devices/ebe61ff5523e4ccd569xvb/commands, params = None, body = {'commands': [{'code': 'switch_led', 'value': True}, {'code': 'colour_data_v2', 'value': '{"h": 45, "s": 1000, "v": 16}'}, {'code': 'work_mode', 'value': 'colour'}]}, headers = {'client_id': '', 'lang': 'en'}
2021-07-19 23:45:52 DEBUG (SyncWorker_0) [tuya iot] Response: {
"result": true,
"success": true,
"t": 1626752752576
}
2021-07-19 23:45:56 DEBUG (SyncWorker_10) [custom_components.tuya_v2.light] light kwargs-> {'brightness': 3}
2021-07-19 23:45:56 DEBUG (SyncWorker_0) [tuya iot] Request: method = POST, url = https://openapi.tuyaus.com/v1.0/devices/ebe61ff5523e4ccd569xvb/commands, params = None, body = {'commands': [{'code': 'switch_led', 'value': True}, {'code': 'bright_value_v2', 'value': 21}]}, headers = {'client_id': '', 'lang': 'en'}
2021-07-19 23:45:56 DEBUG (SyncWorker_0) [tuya iot] Response: {
"result": true,
"success": true,
"t": 1626752756885
}
2021-07-19 23:45:57 DEBUG (SyncWorker_2) [custom_components.tuya_v2.light] light kwargs-> {'color_temp': 421}
2021-07-19 23:45:57 DEBUG (SyncWorker_2) [custom_components.tuya_v2.light] brightness id->
ebe61ff5523e4ccd569xvb
work_mode->,
white,
; check true->,
False
2021-07-19 23:45:57 DEBUG (SyncWorker_0) [tuya iot] Request: method = POST, url = https://openapi.tuyaus.com/v1.0/devices/ebe61ff5523e4ccd569xvb/commands, params = None, body = {'commands': [{'code': 'switch_led', 'value': True}, {'code': 'temp_value_v2', 'value': 227}, {'code': 'bright_value_v2', 'value': 25}]}, headers = {'client_id': ', 'lang': 'en'}
2021-07-19 23:45:57 DEBUG (SyncWorker_0) [tuya iot] Response: {
"result": true,
"success": true,
"t": 1626752757666
}
2021-07-19 23:45:58 DEBUG (SyncWorker_4) [custom_components.tuya_v2.light] light kwargs-> {'color_temp': 500}
2021-07-19 23:45:58 DEBUG (SyncWorker_4) [custom_components.tuya_v2.light] brightness id->
ebe61ff5523e4ccd569xvb
work_mode->,
white,
; check true->,
False
2021-07-19 23:45:58 DEBUG (SyncWorker_0) [tuya iot] Request: method = POST, url = https://openapi.tuyaus.com/v1.0/devices/ebe61ff5523e4ccd569xvb/commands, params = None, body = {'commands': [{'code': 'switch_led', 'value': True}, {'code': 'temp_value_v2', 'value': 0}, {'code': 'bright_value_v2', 'value': 25}]}, headers = {'client_id': '', 'lang': 'en'}
2021-07-19 23:45:58 DEBUG (SyncWorker_0) [tuya iot] Response: {
"result": true,
"success": true,
"t": 1626752758119
}


also, the hugoai table lamp the color picker you can pick color but it reproduces other color and in 1% brightness.

There in the logs theres a Teckin SP20 smart plug that you can see the device but when you press the switch to on, goes to on for a moment and goes to off, it turns on but it reports its off but it can not be turned off.

**Comment by thirteen37** [comment]
I'm seeing a similar issue, but I'm using T&H sensors.

```
2021-07-26 23:01:19 ERROR (Thread-4) [tuya iot] error while get mqtt config
2021-07-26 23:01:19 ERROR (Thread-4) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/site-packages/tuya_iot/openmq.py", line 173, in run
    time.sleep(self.mq_config.expireTime - 60)
AttributeError: 'TuyaOpenMQ' object has no attribute 'mq_config'
```

Let me know if it would be helpful for me to share logs too. I'm on 

* HA core-2021.7.4
* Tuya V2 v1.4.1
