### ISSUE TITLE
Version 1.3.1 - Connection Reset by Peer

### ISSUE THREAD

**Issue by willhaigh** [tuya/tuya-home-assistant#148]
When using 1.3.1 and attempting to set-up a new integration, I kept getting Unexpected Error. In the logs it was showing that the connection was reset by peer against URL https://openapi.tuyacn.com/v1.0/iot-01/associated-users/actions/authorized-login.

I installed 1.3.0 and selected Europe as the region and I have no issues against https://openapi.tuyaeu.com/v1.0/iot-01/associated-users/actions/authorized-login.

I then upgraded from 1.3.0 to 1.3.1 and all worked ok but upon removing and re-adding the tuya2 integration the error re-appeared, I have now switched back to 1.3.0.

![image](https://user-images.githubusercontent.com/2535754/125701372-4b6191e1-d9ac-43b6-a465-c4ba42592152.png)

**Version 1.3.1**

```
'2021-07-15 08:31:55 DEBUG (SyncWorker_2) [tuya iot] Request: method = POST, url = https://openapi.tuyacn.com/v1.0/iot-01/associated-users/actions/authorized-login, params = None, body = {'username': 'removed', 'password': 'removed', 'country_code': '61', 'schema': 'tuyaSmart'}, headers = {'client_id': 'removed', 'sign': 'removed', 'sign_method': 'HMAC-SHA256', 'access_token': '', 't': 'removed', 'lang': 'en', 'dev_lang': 'python', 'dev_version': '0.3.0', 'dev_channel': 'hass'}
2021-07-15 08:31:55 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
httplib_response = self._make_request(
File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
self._validate_conn(conn)
File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
conn.connect()
File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 411, in connect
self.sock = ssl_wrap_socket(
File "/usr/local/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
ssl_sock = _ssl_wrap_socket_impl(
File "/usr/local/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
File "/usr/local/lib/python3.9/ssl.py", line 500, in wrap_socket
return self.sslsocket_class._create(
File "/usr/local/lib/python3.9/ssl.py", line 1040, in _create
self.do_handshake()
File "/usr/local/lib/python3.9/ssl.py", line 1309, in do_handshake
self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
resp = conn.urlopen(
File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
retries = retries.increment(
File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 532, in increment
raise six.reraise(type(error), error, _stacktrace)
File "/usr/local/lib/python3.9/site-packages/urllib3/packages/six.py", line 769, in reraise
raise value.with_traceback(tb)
File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
httplib_response = self._make_request(
File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
self._validate_conn(conn)
File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
conn.connect()
File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 411, in connect
self.sock = ssl_wrap_socket(
File "/usr/local/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
ssl_sock = _ssl_wrap_socket_impl(
File "/usr/local/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
File "/usr/local/lib/python3.9/ssl.py", line 500, in wrap_socket
return self.sslsocket_class._create(
File "/usr/local/lib/python3.9/ssl.py", line 1040, in _create
self.do_handshake()
File "/usr/local/lib/python3.9/ssl.py", line 1309, in do_handshake
self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))'
```

**Version 1.3.0**

```
2021-07-15 08:30:46 DEBUG (SyncWorker_3) [tuya iot] Request: method = POST, url = https://openapi.tuyaeu.com/v1.0/iot-01/associated-users/actions/authorized-login, params = None, body = {'username': 'removed', 'password': 'removed', 'country_code': '61', 'schema': 'tuyaSmart'}, headers = {'client_id': 'removed', 'sign': 'removed', 'sign_method': 'HMAC-SHA256', 'access_token': '', 't': 'removed', 'lang': 'en', 'dev_lang': 'python', 'dev_version': '0.3.0', 'dev_channel': 'hass'}
2021-07-15 08:30:47 DEBUG (SyncWorker_3) [tuya iot] Response: {
"result": {
"access_token": "removed",
"expire_time": 7200,
"refresh_token": "removed",
"uid": "removed"
},
"success": true,
"t": 1626301847519
}
```

**Comment by willhaigh** [comment]
Resolved - attempted upgrade at a later date
