### ISSUE TITLE
Support for Treatlife 2 in 1 Dimmer Switch (Fan & Light)

### ISSUE THREAD

**Issue by stuffmattdoes** [tuya/tuya-home-assistant#16]
Hey folks!

So I've recently purchased a [Treatlife 2 in 1 Dimmer Switch](https://www.amazon.com/gp/product/B086PQ7CHH?pf_rd_r=1B1WBDHK8BD9A1DXRNJ5&pf_rd_p=5ae2c7f8-e0c6-4f35-9071-dc3240e894a8&pd_rd_r=cc4a3fd1-ff17-4538-95ff-edd94681cba3&pd_rd_w=78XmF&pd_rd_wg=11w4N&ref_=pd_gw_unk) to use with Home Assistant. As with many similar smart devices, I've incorporated it into my Home Assistant setup by first pairing the device with the Smart Life app, and then installing the Tuya integration into Home Assistant to import all my Smart Life devices.

I would expect the Home Assistant integration to expose control of the light dimmer and fan dimmer independently as it does in the Smart Life app; however, HA only shows ON/OFF for the fan component. At this time I have not yet been able to remotely control it either, nor does it update the fan on/off status.

What would it take to support this? This 2-in-1 smart dimmer switch is extraordinarily helpful and I'd certainly like to keep it. I'd be happy to help development/testing in any way that I can.

Thank you!
Matthew M.

**Comment by tsutsuku** [comment]
@stuffmattdoes Can you provide the device's info from home assistant's terminal log, which may like this:
[tuya-openapi] Request: method = GET, url = https://openapi.tuyaus.com/v1.0/users/xxxxxxxxxxxxx/devices, params = None, body = None, headers = {'client_id': 'sign': 'sign_method': 'HMAC-SHA256', 'access_token': 't': '1623992694924', 'lang': 'en'}
[tuya-openapi] Response: {
  "result": [
    {
      "active_time": 1623457548,
      "biz_type": 18,
      "category": "wsdcg",
      "create_time": 1623457548,
      "icon": "smart/icon/ay1558597489826VMjh1/c78381c006bd14beaa408dca2ef9bb7d.png",
      "name": "Garage temp 2",
      "online": true,
      "owner_id": "xxxxxxxxxxxxxxxx",
      "product_id": "vvldcafpaiwnh3t3",
      "product_name": "Temperature Humidity Sensor",
      "status": [
        {
          "code": "va_temperature",
          "value": 236
        },
        {
          "code": "va_humidity",
          "value": 46
        },
        {
          "code": "battery_state",
          "value": "high"
        }
      ],
      "sub": false,
      "update_time": 1623991720,
    },

**Comment by paullj1** [comment]
I have this supported in my firmware for TreatLife devices here:
[https://github.com/paullj1/TreatLife-HomeKit](https://github.com/paullj1/TreatLife-HomeKit) 

The key was to expose the device as one accessory with multiple services.  Pretty easy with the SDK I was using.

**Comment by stuffmattdoes** [comment]
@paullj1 thanks for stopping by! I've checked out your repo prior to this. Really impressive work. At the moment, I'd like to avoid flashing since it's a bit more involved than I may be capable of doing, though I won't write it off completely.

**Comment by stuffmattdoes** [comment]
@tsutsuku Here's what I've found in `/config/home-assistant.log`:

```
2021-06-19 12:15:46 ERROR (MainThread) [homeassistant.components.fan] Error adding entities for domain fan with platform tuya
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 383, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 588, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 614, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/usr/src/homeassistant/homeassistant/components/tuya/fan.py", line 75, in async_added_to_hass
    self.speeds.extend(self._tuya.speed_list())
  File "/usr/local/lib/python3.8/site-packages/tuyaha/devices/fan.py", line 12, in speed_list
    for i in range(speed_level):
TypeError: 'NoneType' object cannot be interpreted as an integer
2021-06-19 12:15:46 ERROR (MainThread) [homeassistant.components.fan] Error while setting up tuya platform for fan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 258, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 383, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 588, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 614, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/usr/src/homeassistant/homeassistant/components/tuya/fan.py", line 75, in async_added_to_hass
    self.speeds.extend(self._tuya.speed_list())
  File "/usr/local/lib/python3.8/site-packages/tuyaha/devices/fan.py", line 12, in speed_list
    for i in range(speed_level):
TypeError: 'NoneType' object cannot be interpreted as an integer
```

It doesn't look quite like what you have, though. Perhaps there is another log I can reference?

**Comment by stuffmattdoes** [comment]
@tsutsuku I was able to query the Tuya API itself directly via `https://px1.tuyaus.com/homeassistant/auth.do`

```
{
    'header': { 'code': 'SUCCESS', 'payloadVersion': 1 },
    'payload': {
        'devices': [{
            'data': {
                'online': True,
                'state': 'false'
            },
            'dev_type': 'fan',
            'ha_type': 'fan',
            'icon': 'https://images.tuyaus.com/smart/icon/ay14906729310721fNjn/1568862398d42329fe9d0.jpg',
            'id': '43823346e868e769a9af',
            'name': 'Fan & Light'
        }],
        'scenes': []
    }
}
```

**Comment by tsutsuku** [comment]
@stuffmattdoes It looks like you install the tuya integration, which is the old version.
Please install the tuya v2 integration.
https://github.com/tuya/tuya-home-assistant#installation

**Comment by stuffmattdoes** [comment]
@tsutsuku I have just installed the custom integration for Tuya v2 following the steps in the link you provided. 

It still seems most features from the Treatlife switch are still missing, although I am now able to switch the fan on and off (I was not previously). That is all at the moment.

<img width="450" alt="Screen Shot 2021-06-21 at 2 39 22 AM" src="https://user-images.githubusercontent.com/12943795/122719212-e57cd900-d23b-11eb-832b-0b368f1ec800.png">

Here's the new log output from `/config/home-assistant.log`:
```
2021-06-21 02:37:20 ERROR (MainThread) [homeassistant.components.climate] Error adding entities for domain climate with platform tuya_v2
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 383, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 499, in _async_add_entity
    capabilities=entity.capability_attributes,
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 190, in capability_attributes
    ATTR_HVAC_MODES: self.hvac_modes,
  File "/config/custom_components/tuya_v2/climate.py", line 261, in hvac_modes
    modes = json.loads(self.tuya_device.function.get(DPCODE_MODE, {}).values).get(
  File "/usr/local/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not builtin_function_or_method
2021-06-21 02:37:20 ERROR (MainThread) [homeassistant.components.climate] Error while setting up tuya_v2 platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 258, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 383, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 499, in _async_add_entity
    capabilities=entity.capability_attributes,
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 190, in capability_attributes
    ATTR_HVAC_MODES: self.hvac_modes,
  File "/config/custom_components/tuya_v2/climate.py", line 261, in hvac_modes
    modes = json.loads(self.tuya_device.function.get(DPCODE_MODE, {}).values).get(
  File "/usr/local/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not builtin_function_or_method
2021-06-21 02:41:52 WARNING (MainThread) [homeassistant.helpers.state] Integration scene does not support reproduce state
```

**Comment by tsutsuku** [comment]
@stuffmattdoes Can you provide your device's specifications from home assistant's log. like I wrote before:
https://github.com/tuya/tuya-home-assistant/issues/16#issuecomment-864497575

So I can get the problem.

**Comment by stuffmattdoes** [comment]
I explored the Tuya developer platform a bit, and was able to see this device as well as the controls exposed. It appears to have no knowledge of the lightbulb dimmer component. I wonder if this may be a dead end? Or perhaps there is a way we can extend the Tuya API?

<img width="750" alt="Screen Shot 2021-06-21 at 1 26 21 PM" src="https://user-images.githubusercontent.com/12943795/122805950-b6945080-d297-11eb-9994-057ee8388cee.png">

**Comment by tsutsuku** [comment]
> @tsutsuku the log snippet I pasted above is from `/config/home-assistant.log`. Is there a different log I can reference?

Yes. When you start home assistant from terminal command. More log you can found in the terminal.

**Comment by paullj1** [comment]
That API screenshot seems off to me.  Are you sure you have the right switch?  This particular switch exposes 7 functions in the hardware (which I have sort of documented [here](https://github.com/paullj1/TreatLife-HomeKit/wiki#ds03)).  The fan speed sort of makes sense, and this particular implementation only supports 4 speeds instead of the available 26, but the light should definitely be there, and I’d expect to see the timers as well?  Doesn’t the app use the same API? It can control all of those things.

**Comment by stuffmattdoes** [comment]
@paullj1 I was mistaken - I actually have [this switch by Esmlfe](https://www.amazon.com/dp/B08PD39NLF?psc=1&ref=ppx_yo2_dt_b_product_details). I mistakenly referenced the switch by TreatLife in this issue. I recalled at the time of purchase, the Treatlife being out of inventory so I went with this one. As far as I can tell, this appears to be the same switch under a different brand. Regardless, I'm still interested in getting to the bottom of this!

@tsutsuku I'm unfamiliar with running Home Assistant from terminal, and I have not found any helpful resources. Could you point me in the direction of obtaining terminal output like you're suggesting?

**Comment by tsutsuku** [comment]
@stuffmattdoes 
like this https://www.home-assistant.io/installation/linux#create-the-virtual-environment

**Comment by paullj1** [comment]
Wow, that looks like the exact same switch. The good news is all the manufacturers of these devices rely heavily on Tuya for their software stacks. I’d be willing to bet you could use the TreatLife app to control it exactly the same way.  That might help validate the dpIDs are the same, and that you’d have the same functionality as the TreatLife version.

**Comment by stuffmattdoes** [comment]
@tsutsuku I installed HASS with the all-in-one, not the containerized version. Is there another way to access the device interaction logs?

**Comment by tsutsuku** [comment]
@stuffmattdoes  https://github.com/tuya/tuya-home-assistant/wiki/How-to-Get-the-Log

**Comment by stuffmattdoes** [comment]
@tsutsuku thanks! Finally have some relevant log info:

I believe this is the request/response for initializing Tuya in Home Assistant:
```
2021-07-06 12: 50: 24 DEBUG (Thread-3) [tuya iot] Request:
    method = POST,
    url = https: //openapi.tuyaus.com/v1.0/iot-03/open-hub/access-config,
    params = None,
    body = {
        'uid: [redacted],
        'link_id': [redacted],
        'link_type': 'mqtt',
        'topics': 'device',
        'msg_encrypted_version': '1.0'
    }, headers = {
        'client_id': [redacted],
        'sign': [redacted],
        'sign_method': 'HMAC-SHA256',
        'access_token': [redacted],
        't': '1625590224402',
        'lang': 'en'
    }
2021-07-06 12: 50: 24 DEBUG (SyncWorker_0) [tuya iot] Request:
    method = GET,
    url = https: //openapi.tuyaus.com/v1.0/users/az1608774759087zoqSR/devices,
    params = None,
    body = None,
    headers = {
        'client_id': [redacted],
        'sign': [redacted],
        'sign_method': 'HMAC-SHA256',
        'access_token': [redacted],
        't': '1625590224420',
        'lang':'en'
    }
2021-07-06 12: 50: 24 DEBUG (Thread-3) [tuya iot] Response: {
    "result": {
        "client_id": [redacted],
        "expire_time": 7200,
        "password": [redacted],
        "sink_topic": {
            "device": "cloud/token/out/{device_id}"
        },
        "source_topic": {
            "device": [redacted]
        },
        "url": "ssl://m1.tuyaus.com:8883",
        "username": [redacted]
    },
    "success": true,
    "t": 1625590224513
}
2021-07-06 12: 50: 24 DEBUG (Thread-3) [tuya iot] connecting ssl: //m1.tuyaus.com:8883
2021-07-06 12: 50: 24 DEBUG (SyncWorker_0) [tuya iot] Response: {
    "result": [
        {
            "active_time": 1624571410,
            "biz_type": 18,
            "category": "fs",
            "create_time": 1622228399,
            "icon": "smart/icon/ay14906729310721fNjn/a590ccd0538ad889c8cd8d7c78242368.jpg",
            "id": "43823346e868e769a9af",
            "ip": [redacted],
            "lat": "37.44231",
            "local_key": [redacted],
            "lon": "-77.530914",
            "name": "Fan & Light",
            "online": true,
            "owner_id": [redacted],
            "product_id": "gvfmw8c8n92umpax",
            "product_name": "",
            "status": [
                {
                    "code": "switch",
                    "value": false
                },
                {
                    "code": "fan_speed",
                    "value": "2"
                }
            ],
            "sub": false,
            "time_zone": "-05:00",
            "uid": "az1608774759087zoqSR",
            "update_time": 1625589145,
            "uuid": "43823346e868e769a9af"
        }
    ],
    "success": true,
    "t": 1625590224833
}
```

And here is the interaction when I toggle the light entity via the Smart Life App.
* Note that the fan values are shown, but Home Assistant still appears to have no knowledge of the light component:

```
2021-07-06 13:44:31 DEBUG (Thread-4) [tuya iot] _on_log: Received PUBLISH (d0, q0, r0, m0), 'cloud/token/in/cdb923e6d6839af5baf464662a2ca490', ... (284 bytes)
2021-07-06 13:44:31 DEBUG (Thread-4) [tuya iot] payload-> b' {
    "data": "6ZPs8LscE24a7mTz97pvoFu5z2SFlxn8ZPEMZl79qz44TMdhzWmNVrWdcQK6HujLkIi84IxLy3sxz9EkEqg55WteZobYd84G6YUicBZNo1Jk6N2MjFpk/HQK7Kt3Df9NeNYFJT7A4GIfifmcJPHVSac5H+YW8fszGgbDVy2SK0scCTd5iutX4uJM6xJOUaDK",
    "protocol": 4,
    "pv": "2.0",
    "sign": [redacted],
    "t":1625593470
}'
2021-07-06 13:44:31 DEBUG (Thread-4) [tuya iot] on_message: {
    'data': {
        'dataId': 'b947cdec-9dde-4417-a3d5-47ea2bcda3b2',
        'devId': '43823346e868e769a9af',
        'productKey': 'gvfmw8c8n92umpax',
        'status': [{'9': True}]
    }, 
    'protocol': 4, 
    'pv': '2.0', 
    'sign': [redacted] 
    't': 1625593470
}
2021-07-06 13:44:31 DEBUG (Thread-4) [tuya iot] mq receive-> {
    'data': {
        'dataId': 'b947cdec-9dde-4417-a3d5-47ea2bcda3b2',
        'devId': '43823346e868e769a9af',
        'productKey': 'gvfmw8c8n92umpax',
        'status': [{'9': True}]
    }, 
    'protocol': 4, 
    'pv': '2.0', 
    'sign': [redacted] 
    't': 1625593470
}
2021-07-06 13:44:31 DEBUG (Thread-4) [tuya iot] mq _on_device_report-> [{'9': True}]
2021-07-06 13:44:31 DEBUG (Thread-4) [custom_components.tuya_v2] _update--><custom_components.tuya_v2._init_tuya_sdk.<locals>.DeviceListener object at 0x6e86b658>;->>{
    'switch': False,
    'fan_speed': '2'
}
```

I'm looked at [this wiki](https://github.com/tuya/tuya-home-assistant/wiki/How-to-Develop-a-New-Driver) regarding how to add a driver for the device, but I'm not sure if a new driver is necessary. Seems simply adding support for the `light` entity type would suffice.

**Comment by tsutsuku** [comment]
@stuffmattdoes This device needs to standardize, which in the clouds. Also, integration needs to add functions.
So I think we will fix it in the next release.

**Comment by stuffmattdoes** [comment]
@tsutsuku digging a bit deeper, I've found that parameter `'9'` in the response body is related to toggling the lights, while parameter `'10'` is related to the light brightness, presumably a value from 0-255.

### Toggling light
```
2021-07-06 22:26:25 DEBUG (Thread-772) [tuya iot] on_message: {
    'data': {
        'dataId': '9565db76-c13f-439c-8cf8-28c82cec3557',
        'devId': [redated],
        'productKey': 'gvfmw8c8n92umpax',
        'status': [
            { '9': True }
        ]
    }, 
    'protocol': 4, 
    'pv': '2.0', 
    'sign': '[redated]',
    't': 1625624785
}
```

## Light brightness
```
2021-07-06 22:34:05 DEBUG (Thread-772) [tuya iot] on_message: {
    'data': {
        'dataId': 'da2a5de9-7925-421e-9b5c-ec95cbe65528', 
        'devId': [redated], 
        'productKey': 'gvfmw8c8n92umpax', 
        'status': [
            { '10': 220 }
        ]
    }, 
    'protocol': 4, 
    'pv': '2.0', 
    'sign': '9a4698111d1e557ec013842d4d605917', 
    't': 1625625245
}
```

**Comment by stuffmattdoes** [comment]
@tsutsuku any updates?

**Comment by tsutsuku** [comment]
@stuffmattdoes "standardize" is done. Try again and provide your device specifications.

**Comment by chadbaum** [comment]
Hi all, I have the Treatlife Fan/Light combo switch and am on the latest version 1.41.  I still only see fan entities being created from the devices.

![image](https://user-images.githubusercontent.com/4358977/126986536-4c899c5a-aba5-4b8d-b8ce-438a7a3c6dc6.png)

**Comment by wills721** [comment]
Any update on this? Would prefer a non-flashing solution -- I use HomeKit and Alexa (works in Alexa which uses the WebAPI).  A solution that works with homebridge-tuya-web.
