### ISSUE TITLE
KeyError after update to v1.4.0

### ISSUE THREAD

**Issue by carlosvroque** [tuya/tuya-home-assistant#195]
**Describe the bug**
The integration fails during setup, so none of the devices are available.

**Expected behavior**

Reverting back to V1.3.2 works normally.

**Home Assistant Version**
- 2021.7.4

**Additional context**
Add any other context or logs about the problem here.
```

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/tuya_v2/__init__.py:81
Integration: Tuya v2 (documentation)
First occurred: 08:12:39 (1 occurrences)
Last logged: 08:12:39

Error setting up entry my@mail.com for tuya_v2
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/tuya_v2/__init__.py", line 290, in async_setup_entry
    success = await _init_tuya_sdk(hass, entry)
  File "/config/custom_components/tuya_v2/__init__.py", line 118, in _init_tuya_sdk
    entry_data = entry_decrypt(hass, entry, init_entry_data)
  File "/config/custom_components/tuya_v2/__init__.py", line 81, in entry_decrypt
    if init_entry_data[XOR_KEY]:
KeyError: '00oo00'
```

**Comment by sebadv** [comment]
Ok, so I'm not the only one ;-)

**Comment by Sthopeless** [comment]
re-login the integration worked for me

**Comment by FelipeMartini** [comment]
Yes you must remove and reinstall this to region again and will work

**Comment by carlosvroque** [comment]
I updated to v1.4 again, removed the integration, restarted and managed to login again without any issues. 

So I'll close the issue and leave this here as solution.
