### ISSUE TITLE
Error setting up entry 2XXXXXXXXX for tuya_v2

### ISSUE THREAD

**Issue by apokha1** [tuya/tuya-home-assistant#198]
**Describe the bug**
I have migrated from Tuya's home assistant version to Tuya V2 using HACS installation. Everything worked like a charm for a couple of days and now today, after I restarted my instance of Docker deployed HA, I have been getting an error. I tried to re-install the custom component again, but to no avail.

**Expected behavior**
I expected the component to start as normal and I'd be able to access the devices and entities, but it doesn't load. 

**Screenshots**
![image](https://user-images.githubusercontent.com/38929421/126812239-08e8133a-afeb-4a55-b2b9-3ecc1048d84c.png)

**Home Assistant Version**
- 2021.7.3

**Logger: homeassistant.config_entries
Source: custom_components/tuya_v2/__init__.py:81
Integration: Tuya v2 (documentation)
First occurred: 11:14:50 AM (1 occurrences)
Last logged: 11:14:50 AM

```
Error setting up entry 2XXXXXXXXX for tuya_v2
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/tuya_v2/__init__.py", line 290, in async_setup_entry
    success = await _init_tuya_sdk(hass, entry)
  File "/config/custom_components/tuya_v2/__init__.py", line 118, in _init_tuya_sdk
    entry_data = entry_decrypt(hass, entry, init_entry_data)
  File "/config/custom_components/tuya_v2/__init__.py", line 81, in entry_decrypt
    if init_entry_data[XOR_KEY]:
KeyError: '00oo00'
```

**Comment by carlosvroque** [comment]
Hello! I've had the same issue (#195). All you need to do is delete Tuyav2 the integration page, restart HA and then add the integration again.

You can safely delete the integration as the devices will be created again with the exact same ids.

**Comment by pmd5700** [comment]
I'm having the same issue.

@carlosvroque > Hello! I've had the same issue (#195). All you need to do is delete Tuya v2 the integration page, restart HA and then add the integration again.
> 
> You can safely delete the integration as the devices will be created again with the exact same ids.
I tried that, but I keep getting "Invalid authentication"

**Comment by tsutsuku** [comment]
Try v1.4.1
