### ISSUE TITLE
Error adding entities for domain climate

### ISSUE THREAD

**Issue by undulattice** [tuya/tuya-home-assistant#206]
**Describe the bug**
I've installed the add-on via HACS and started the integration.
My heater is picked up (only device currently in the account), but I get the following error in the Home Assistant log.

```
Logger: homeassistant.components.climate
Source: custom_components/tuya_v2/climate.py:353
Integration: Climate (documentation, issues)
First occurred: 12:41:02 (2 occurrences)
Last logged: 12:41:02

Error adding entities for domain climate with platform tuya_v2
Error while setting up tuya_v2 platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 383, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 499, in _async_add_entity
    capabilities=entity.capability_attributes,
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 219, in capability_attributes
    ATTR_HVAC_MODES: self.hvac_modes,
  File "/config/custom_components/tuya_v2/climate.py", line 353, in hvac_modes
    modes = json.loads(self.tuya_device.function.get(DPCODE_MODE, {}).values).get(
  File "/usr/local/lib/python3.9/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not builtin_function_or_method
```

**Home Assistant Version**
2021.7.4

**Device info (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-home-assistant/wiki/How-to-get-the-log)):**
```
{
"active_time": 1617993963,
"biz_type": 0,
"category": "qn",
"create_time": 1617993963,
"icon": "smart/icon/ay1552870032702eJ0IG/a8ff9eef234e031814fa398cc31a7052.png",
"id": "03417203483fda8e9b93",
"ip": "90.196.89.46",
"lat": "51.68708899517353",
"local_key": "20d5ef9f122c815f",
"lon": "-3.440796438182727",
"model": "CHX-20GR-B",
"name": "Heater",
"online": true,
"owner_id": "1092741",
"product_id": "o0gwmghg17a7tqjh",
"product_name": "Q086-Q094",
"status": [
{
"code": "switch",
"value": true
},
{
"code": "temp_set",
"value": 18
},
{
"code": "temp_current",
"value": 19
},
{
"code": "lock",
"value": false
},
{
"code": "countdown_left",
"value": 0
}
],
"sub": false,
"time_zone": "+00:00",
"uid": "eu1524423823147WE5is",
"update_time": 1627007377,
"uuid": "03417203483fda8e9b93"
}
```
**Device specifications (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-home-assistant/wiki/How-to-get-the-log)):**
```
2021-07-24 12:54:46 DEBUG (SyncWorker_0) [tuya iot] Request: method = GET, url = https://openapi.tuyaeu.com/v1.0/devices/03417203483fda8e9b93/specifications, params = None, body = None, headers = {'client_id': '4jgqv7euar5ehcku1utl', 'sign': '0EC3869257F80962EAC4F83E8C26EEB1E64B83831FDE8ACBE14AC4449F30DD21', 'sign_method': 'HMAC-SHA256', 'access_token': '3e8a7dabc5fd37c6ce891fb06d739ede', 't': '1627127686348', 'lang': 'en'}
2021-07-24 12:54:46 DEBUG (SyncWorker_0) [tuya iot] Response: {
"result": {
"category": "qn",
"functions": [
{
"code": "switch",
"type": "Boolean",
"values": "{}"
},
{
"code": "temp_set",
"type": "Integer",
"values": "{\"unit\":\"℃\",\"min\":10,\"max\":49,\"scale\":0,\"step\":1}"
},
{
"code": "lock",
"type": "Boolean",
"values": "{}"
}
],
"status": [
{
"code": "switch",
"type": "Boolean",
"values": "{}"
},
{
"code": "temp_set",
"type": "Integer",
"values": "{\"unit\":\"℃\",\"min\":10,\"max\":49,\"scale\":0,\"step\":1}"
},
{
"code": "temp_current",
"type": "Integer",
"values": "{\"unit\":\"℃\",\"min\":-9,\"max\":49,\"scale\":0,\"step\":1}"
},
{
"code": "lock",
"type": "Boolean",
"values": "{}"
},
{
"code": "countdown_left",
"type": "Integer",
"values": "{\"unit\":\"min\",\"min\":0,\"max\":1440,\"scale\":0,\"step\":1}"
}
]
},
"success": true,
"t": 1627127686406
}
2021-07-24 12:54:46 DEBUG (Thread-5) [tuya iot] Response: {
"result": {
"client_id": "cloud_3367b8f2dd9a53b4ed686a0a1d738d60",
"expire_time": 7200,
"password": "ecdf3cecce389bf928f83996d96d6acb",
"sink_topic": {
"device": "cloud/token/out/{device_id}"
},
"source_topic": {
"device": "cloud/token/in/1759877b5bc702161c19b36f1171e95c"
},
"url": "ssl://m1.tuyaeu.com:8883",
"username": "cloud_1759877b5bc702161c19b36f1171e95c"
},
"success": true,
"t": 1627127686474
}
```

**Comment by gvssr** [comment]
Getting a similar error to this one with my own climate device:

**Error adding entities for domain climate with platform tuya_v2**
```
Error adding entities for domain climate with platform tuya_v2
Error while setting up tuya_v2 platform for climate
```

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 383, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 499, in _async_add_entity
    capabilities=entity.capability_attributes,
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 219, in capability_attributes
    ATTR_HVAC_MODES: self.hvac_modes,
  File "/config/custom_components/tuya_v2/climate.py", line 353, in hvac_modes
    modes = json.loads(self.tuya_device.function.get(DPCODE_MODE, {}).values).get(
  File "/usr/local/lib/python3.9/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not builtin_function_or_method
```

**Comment by c0m3r** [comment]
Same issue here as well:

2021-07-26 11:14:51 ERROR (MainThread) [homeassistant.components.climate] Error while setting up tuya_v2 platform for climate
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 258, in _async_setup_platform
await asyncio.gather(*pending)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 383, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 499, in _async_add_entity
capabilities=entity.capability_attributes,
File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 219, in capability_attributes
ATTR_HVAC_MODES: self.hvac_modes,
File "/config/custom_components/tuya_v2/climate.py", line 353, in hvac_modes
modes = json.loads(self.tuya_device.function.get(DPCODE_MODE, {}).values).get(
File "/usr/local/lib/python3.9/json/__init__.py", line 339, in loads
raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not builtin_function_or_method

**Comment by checksummaster** [comment]
Same problem with a thermostat for electric floor heater (no HVAC).
The bug seem in the malformed  (or maybe inexistant) JSON that describe HVAC modes.  Should the function return an empty array if the JSON is not good?

**Comment by tsutsuku** [comment]
@undulattice Try v1.5.0.
