### ISSUE TITLE
Post most recent update 2 days ago 

### ISSUE THREAD

**Issue by menocode** [tuya/tuya-home-assistant#212]
Integration worked fine post the last update two days ago - July 22/23rd.

Now I receive this error 

```This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/tuya_v2/__init__.py:81 
Integration: Tuya v2 (documentation) 
First occurred: 1:12:47 AM (1 occurrences) 
Last logged: 1:12:47 AM

Error setting up entry yosef@friedfamily.com for tuya_v2
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/tuya_v2/__init__.py", line 290, in async_setup_entry
    success = await _init_tuya_sdk(hass, entry)
  File "/config/custom_components/tuya_v2/__init__.py", line 118, in _init_tuya_sdk
    entry_data = entry_decrypt(hass, entry, init_entry_data)
  File "/config/custom_components/tuya_v2/__init__.py", line 81, in entry_decrypt
    if init_entry_data[XOR_KEY]:
KeyError: '00oo00'
```

```
System Health

version: core-2021.7.4
installation_type: Home Assistant OS
dev: false
hassio: true
docker: true
virtualenv: false
python_version: 3.9.5
os_name: Linux
os_version: 5.10.17-v8
arch: aarch64
timezone: Asia/Jerusalem


GitHub API: ok
Github API Calls Remaining: 4230
Installed Version: 1.13.2
Stage: running
Available Repositories: 910
Installed Repositories: 61


logged_in: true
subscription_expiration: August 22, 2021, 3:00 AM
relayer_connected: true
remote_enabled: true
remote_connected: true
alexa_enabled: true
google_enabled: false
can_reach_cert_server: ok
can_reach_cloud_auth: ok
can_reach_cloud: ok


host_os: Home Assistant OS 6.1
update_channel: stable
supervisor_version: supervisor-2021.06.8
docker_version: 20.10.6
disk_total: 116.7 GB
disk_used: 9.4 GB
healthy: true
supported: true
board: rpi4-64
supervisor_api: ok
version_api: ok
installed_addons: File editor (5.3.3), Home Assistant Google Drive Backup (0.104.3), Terminal & SSH (9.1.3), Log Viewer (0.11.1), Node-RED (9.2.1), WireGuard (0.5.0), Visual Studio Code (3.6.0), MariaDB (2.4.0), Grocy (0.15.0), Samba share (9.3.1), Spotify Connect (0.9.0)


dashboards: 2
resources: 35
views: 17
mode: storage


api_endpoint_reachable: ok

```

**Comment by tsutsuku** [comment]
Try v1.4.1
