### ISSUE TITLE
Error new update integration stop working

### ISSUE THREAD

**Issue by milandzuris** [tuya/tuya-home-assistant#214]
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/tuya_v2/__init__.py:81
Integration: Tuya v2 (documentation)
First occurred: 01:56:50 (1 occurrences)
Last logged: 01:56:50

Error setting up entry Tuya V2 for tuya_v2
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/tuya_v2/__init__.py", line 290, in async_setup_entry
    success = await _init_tuya_sdk(hass, entry)
  File "/config/custom_components/tuya_v2/__init__.py", line 118, in _init_tuya_sdk
    entry_data = entry_decrypt(hass, entry, init_entry_data)
  File "/config/custom_components/tuya_v2/__init__.py", line 81, in entry_decrypt
    if init_entry_data[XOR_KEY]:
KeyError: '00oo00'

new version

**Comment by Martynhsmith** [comment]
I think this is the same issue as #209

**Comment by tsutsuku** [comment]
Try v1.4.1.

**Comment by tsutsuku** [comment]
@Martynhsmith Have your problem solved?

**Comment by Martynhsmith** [comment]
Yes, thank you
