### ISSUE TITLE
Failed to upgrade and re-install: Unknown error occurred

### ISSUE THREAD

**Issue by thetastate1** [tuya/tuya-home-assistant#220]
**Describe the bug**
Authentication is flakey. Integration is solid once authenticated. Additional authentication defect seems to have been introduced in 1.4 or just part of any upgrade.

"Unknown error occurred" is not defined nor described in the wiki and faq.

When installing v1.3 I had "Unknown error occurred" constantly over the 4 days of trying. I logged a defect here. Without changing any authentication details it magically started working one morning and had worked fine until I decided to upgrade to v1.4. After upgrading to v1.4 the integration would appear in HA and show the correct number of entities but none of the entities were available and the integration noted "Failed to set up: check the logs". This error remained after 12 HA restarts. I then rolled back to 1.32 which worked for a few hours then reverted back to the "Failed to set up" error. Following the experience of others here I deleted the integration and reinstalled v1.4 from HACS. 

Now using the same authentication credentials as before I have "Unknown error occurred" again.

Interestingly and perhaps not co-incidentally I received an email from Tuya today with the subject "Contract expiry renewal reminder". The message was:
合约到期提醒

尊敬的客户，
您的VOICE_DEVICE_CONTR20210710133725合约，于2021-08-10即将到期，若您仍需使用，请您重新续订，以免影响正常使用，谢谢！如有疑问请拨打400-881-8611或联系在线客服。

Standard Tuya integration continues to work fine and is rock solid.

**Expected behavior**
Authentication and install of this integration should behave as per the wiki.

It should be as reliable as the standard Tuya integration.

**Screenshots**

**Home Assistant Version**
2021.7.4

** LOG when installing 1.4 from scratch**

021-07-25 20:47:34 INFO (MainThread) [custom_components.tuya_v2.config_flow] TuyaConfigFlow.async_step_user start, is_import= False
2021-07-25 20:47:34 INFO (MainThread) [custom_components.tuya_v2.config_flow] TuyaConfigFlow.async_step_user start, user_input= None
2021-07-25 20:48:19 INFO (MainThread) [custom_components.tuya_v2.config_flow] TuyaConfigFlow.async_step_user start, is_import= False
2021-07-25 20:48:19 INFO (MainThread) [custom_components.tuya_v2.config_flow] TuyaConfigFlow.async_step_user start, user_input= {'password': 'pass', 'access_id': 'aid', 'access_secret': 'asecret', 'tuya_app_type': 'tuyaSmart', 'country_code': '61', 'username': 'xx@hotmail.com'}
2021-07-25 20:48:19 INFO (SyncWorker_5) [custom_components.tuya_v2.config_flow] TuyaConfigFlow._try_login start, user_input: {'password': 'pass', 'access_id': 'aid', 'access_secret': 'sec', 'tuya_app_type': 'tuyaSmart', 'country_code': '61', 'username': 'xx@hotmail.com', 'tuya_project_type': 0}

**Log from after installation successfully installed then upgraded**

2021-07-25 19:34:48 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry xx@hotmail.com for tuya_v2
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/homeassistant/config_entries.py", line 293, in async_setup
result = await component.async_setup_entry(hass, self) # type: ignore
File "/home//.homeassistant/custom_components/tuya_v2/__init__.py", line 290, in async_setup_entry
success = await _init_tuya_sdk(hass, entry)
File "/home//.homeassistant/custom_components/tuya_v2/__init__.py", line 118, in _init_tuya_sdk
entry_data = entry_decrypt(hass, entry, init_entry_data)
File "/home//.homeassistant/custom_components/tuya_v2/__init__.py", line 81, in entry_decrypt
if init_entry_data[XOR_KEY]:
KeyError: '00oo00'

**Comment by thetastate1** [comment]
Authentication randomly started working again when installing the integration. 

The standard Tuya integration authenticates just fine.

I've noticed logging into the Tuya IoT platform is also unreliable for me. Sometimes several attempts at login are required including the captcha puzzle piece. Credentials never change it just randomly works.
