### ISSUE TITLE
update 1.4 and 1.4.1 breaks the integration.

### ISSUE THREAD

**Issue by RudyDevroey** [tuya/tuya-home-assistant#242]
Deze fout is ontstaan door een aangepaste integratie.

Logger: homeassistant.config_entries
Source: custom_components/tuya_v2/__init__.py:102
Integration: Tuya v2 (documentation)
First occurred: 18:16:52 (1 occurrences)
Last logged: 18:16:52

Error setting up entry rudy12767@gmail.com for tuya_v2
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/tuya_v2/__init__.py", line 290, in async_setup_entry
    success = await _init_tuya_sdk(hass, entry)
  File "/config/custom_components/tuya_v2/__init__.py", line 118, in _init_tuya_sdk
    entry_data = entry_decrypt(hass, entry, init_entry_data)
  File "/config/custom_components/tuya_v2/__init__.py", line 102, in entry_decrypt
    user_input_encrpt = aes.cbc_encrypt(cbc_key, cbc_iv, json.dumps(init_entry_data))
  File "/usr/local/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type mappingproxy is not JSON serializable

**Comment by tsutsuku** [comment]
@RudyDevroey Try v1.4.1 again. We fixed this error this morning.

**Comment by Damian666** [comment]
reinstalling 1.4.1 did the trick for me :)

**Comment by GazTheGeek** [comment]
Was already on 1.4.1 I started having problem last night AEST with my Lovelace buttons not working on an Arlec Tuya smart plug. Node-Red automations were fine as were HomeKit automations but Lovelace buttons did not work. I re-authorised the notification service on Tuya IOT still nothing. So I reinstalled the HACS integration and its all working fine now.

Thanks team for your hard work on this integration it a major game changer! I will be stocking up on Tuya enabled devices as soon as the integration has local access. Thanks

**Comment by pluskal** [comment]
@tsutsuku, could you please increment the patch number any time you release it? 

Rebuilding under the same version number poses difficulty with updates. HACS notifies only on "updates" and does not have a build-in reinstall feature. It may be complicated and worrisome for some people to uninstall and install a component (e.g., configuration persistence concerns).

**Comment by zlinoliver** [comment]
@pluskal sorry for the inconvenience, we have released a new tag of v1.4.2 for the bug fix.Please check if it works for you.

**Comment by pluskal** [comment]
Awesome! Thanks, works like a charm.
