### ISSUE TITLE
Support for  Gorenje 2000EWP Panel convection heater

### ISSUE THREAD

**Issue by Zaknin** [tuya/tuya-home-assistant#259]
**Both devices work fine with Tuya v1 integration, Tuya v2 creates devices, but there is no entities, i have 2 heaters, different revisions, but both work with Tuya v1 and do not with Tuya v2**

Brand \Model
- Gorenje
- Optiheat 2000EWP

- Optiheat

**Device info 

**Heater 1**

    "result": [
{
"active_time": 1606235282,
"biz_type": 0,
"category": "qn",
"create_time": 1606235282,
"icon": "smart/icon/1470624702_0.jpeg",
"id": "XXX",
"ip": "XXX",
"lat": "XXX",
"local_key": "XXX",
"lon": "XXX",
"name": "Small room heater",
"online": true,
"owner_id": "XXX",
"product_id": "ynjanlglr4qa6dxf",
"product_name": "Panel heater",
"status": [
{
"code": "switch",
"value": true
},
{
"code": "temp_set",
"value": 19
},
{
"code": "temp_current",
"value": 27
}
},

**Heater 2**

{
"active_time": 1605191295,
"biz_type": 0,
"category": "qn",
"create_time": 1541259484,
"icon": "smart/icon/qn.png",
"id": "XXX",
"ip": "XXX",
"lat": "XXX",
"local_key": "XXX",
"lon": "XXX",
"model": "根据产品情况输入",
"name": "Heater",
"online": false,
"owner_id": "XXX",
"product_id": "G200UVIiNv5AafpA",
"product_name": "ＰＡＮＥＬ　ＨＥＡＴＥＲ",
"status": [
{
"code": "temp_set",
"value": 23
},
{
"code": "temp_current",
"value": 24
},
{
"code": "lock",
"value": false
},
{
"code": "switch",
"value": false
}

**Device specifications 

**Heater  1**

{
"result": {
"category": "qn",
"functions": [
{
"code": "switch",
"type": "Boolean",
"values": "{}"
},
{
"code": "temp_set",
"type": "Integer",
"values": "{\"unit\":\"℃\",\"min\":5,\"max\":40,\"scale\":0,\"step\":1}"
}
],
"status": [
{
"code": "switch",
"type": "Boolean",
"values": "{}"
},
{
"code": "temp_set",
"type": "Integer",
"values": "{\"unit\":\"℃\",\"min\":5,\"max\":40,\"scale\":0,\"step\":1}"
},
{
"code": "temp_current",
"type": "Integer",
"values": "{\"unit\":\"℃\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
}
]
},
"success": true,
"t": 1627477551097
}

**Heater 2**

{
"result": {
"category": "qn",
"functions": [
{
"code": "temp_set",
"type": "Integer",
"values": "{\"unit\":\"℃\",\"min\":15,\"max\":35,\"scale\":0,\"step\":1}"
},
{
"code": "lock",
"type": "Boolean",
"values": "{}"
},
{
"code": "switch",
"type": "Boolean",
"values": "{}"
}
],
"status": [
{
"code": "temp_set",
"type": "Integer",
"values": "{\"unit\":\"℃\",\"min\":15,\"max\":35,\"scale\":0,\"step\":1}"
},
{
"code": "temp_current",
"type": "Integer",
"values": "{\"unit\":\"℃\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
},
{
"code": "lock",
"type": "Boolean",
"values": "{}"
},
{
"code": "switch",
"type": "Boolean",
"values": "{}"
}
]
},
"success": true,
"t": 1627477551304
}

**Comment by Zaknin** [comment]
Here is content of logged error

Logger: homeassistant.components.climate
Source: custom_components/tuya_v2/climate.py:353
Integration: Climate (documentation, issues)
First occurred: 2:00:51 PM (2 occurrences)
Last logged: 2:00:54 PM

    Error adding entities for domain climate with platform tuya_v2
    Error while setting up tuya_v2 platform for climate

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 383, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 499, in _async_add_entity
    capabilities=entity.capability_attributes,
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 219, in capability_attributes
    ATTR_HVAC_MODES: self.hvac_modes,
  File "/config/custom_components/tuya_v2/climate.py", line 353, in hvac_modes
    modes = json.loads(self.tuya_device.function.get(DPCODE_MODE, {}).values).get(
  File "/usr/local/lib/python3.9/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not builtin_function_or_method

**Comment by tsutsuku** [comment]
#206 #266 same error.

**Comment by thewolf-oz** [comment]
I get the same with a different 'qn' category panel heater (Arlec heater from Australia)
