### ISSUE TITLE
Error doing job: Task exception was never retrieved

### ISSUE THREAD

**Issue by colinnewman2000** [tuya/tuya-home-assistant#266]
Hi,

I have recently installed the V2 integration and am getting the error below in my log.

If you need anything else from me to investigate, please let me know.

Best regards

Colin

Logger: homeassistant
Source: custom_components/tuya_v2/climate.py:353 
Integration: Tuya v2 (documentation) 
First occurred: 10:18:35 (58 occurrences) 
Last logged: 11:35:12

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 406, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 450, in _async_write_ha_state
    attr = self.capability_attributes
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 219, in capability_attributes
    ATTR_HVAC_MODES: self.hvac_modes,
  File "/config/custom_components/tuya_v2/climate.py", line 353, in hvac_modes
    modes = json.loads(self.tuya_device.function.get(DPCODE_MODE, {}).values).get(
  File "/usr/local/lib/python3.9/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not builtin_function_or_method

**Comment by mloebl** [comment]
Same issue here too. I have 2 Wifi Temperature Sensors and 1 WiFI Humidity sensor if that helps.

**Comment by tsutsuku** [comment]
We will fix this bug in next release version.

**Comment by tsutsuku** [comment]
@colinnewman2000 Check v1.5.0.

**Comment by colinnewman2000** [comment]
Resolved in 1.5.0. Excellent.
