### ISSUE TITLE
New device: RGB LED strip (dd) incorrectly identified as a light (dj)

### ISSUE THREAD

**Issue by Krytten** [tuya/tuya-home-assistant#270]
**Device normal info**
- Brand: SingHong
- Model: RGB Strip

**Device info**
{
"active_time": 1627346744,
"biz_type": 18,
"category": "dj",
"create_time": 1556644686,
"icon": "smart/icon/1467167733_0.png",
"id": "71573400840d8e8e081e",
"ip": "***********",
"lat": "**********",
"local_key": "1ed8eb7f50739446",
"lon": "***********",
"model": "冠欣宏-RGB灯带",
"name": "TV",
"online": true,
"owner_id": "2424370",
"product_id": "ALrQFlmIs5wYSZyS",
"product_name": "SingHong RGB Strip",
"status": [
{
"code": "switch_led",
"value": true
},
{
"code": "work_mode",
"value": "colour"
},
{
"code": "bright_value",
"value": 40
},
{
"code": "temp_value",
"value": 255
},
{
"code": "colour_data",
"value": "{\"h\":24.0,\"s\":255.0,\"v\":255.0}"
},
{
"code": "scene_data",
"value": "{\"h\":0.0,\"s\":0.0,\"v\":0.0}"
},
{
"code": "flash_scene_1",
"value": "{\"bright\":255,\"frequency\":80,\"hsv\":[{\"h\":120.0,\"s\":255.0,\"v\":255.0}],\"temperature\":255}"
},
{
"code": "flash_scene_2",
"value": "{\"bright\":255,\"frequency\":128,\"hsv\":[{\"h\":0.0,\"s\":255.0,\"v\":255.0},{\"h\":120.0,\"s\":255.0,\"v\":255.0},{\"h\":240.0,\"s\":255.0,\"v\":255.0},{\"h\":0.0,\"s\":0.0,\"v\":0.0},{\"h\":0.0,\"s\":0.0,\"v\":0.0},{\"h\":0.0,\"s\":0.0,\"v\":0.0}],\"temperature\":255}"
},
{
"code": "flash_scene_3",
"value": "{\"bright\":255,\"frequency\":80,\"hsv\":[{\"h\":0.0,\"s\":255.0,\"v\":255.0}],\"temperature\":255}"
},
{
"code": "flash_scene_4",
"value": "{\"bright\":255,\"frequency\":5,\"hsv\":[{\"h\":0.0,\"s\":255.0,\"v\":255.0},{\"h\":120.0,\"s\":255.0,\"v\":255.0},{\"h\":60.0,\"s\":255.0,\"v\":255.0},{\"h\":300.0,\"s\":255.0,\"v\":255.0},{\"h\":240.0,\"s\":255.0,\"v\":255.0},{\"h\":0.0,\"s\":0.0,\"v\":0.0}],\"temperature\":255}"
}
],
"sub": false,
"time_zone": "+00:00",
"uid": "eu1543191336182Af1pS",
"update_time": 1627489074,
"uuid": "71573400840d8e8e081e"
}

**Device specifications **

[tuya iot] Request: method = GET, url = https://openapi.tuyaeu.com/v1.0/devices/71573400840d8e8e081e/specifications, params = None, body = None, headers = {'client_id': '************************', 'sign': '**********************', 'sign_method': 'HMAC-SHA256', 'access_token': '*************************', 't': '1627492075227', 'lang': 'en'}
2021-07-28 18:07:55 DEBUG (Thread-3) [tuya iot] Response: {
"result": {
"client_id": "cloud_43877cff567943ede5a7c0093442f96b",
"expire_time": 7200,
"password": "*******************",
"sink_topic": {
"device": "cloud/token/out/{device_id}"
},
"source_topic": {
"device": "cloud/token/in/4d5731ed1cb7e5a210c9df79e15b8ff5"
},
"url": "ssl://m1.tuyaeu.com:8883",
"username": "cloud_4d5731ed1cb7e5a210c9df79e15b8ff5"
},
"success": true,
"t": 1627492075297
}
2021-07-28 18:07:55 DEBUG (Thread-3) [tuya iot] connecting ssl://m1.tuyaeu.com:8883
2021-07-28 18:07:55 DEBUG (SyncWorker_1) [tuya iot] Response: {
"result": {
"category": "dj",
"functions": [
{
"code": "switch_led",
"type": "Boolean",
"values": "{}"
},
{
"code": "work_mode",
"type": "Enum",
"values": "{\"range\":[\"white\",\"colour\"]}"
},
{
"code": "colour_data",
"type": "Json",
"values": "{\"h\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}"
},
{
"code": "scene_data",
"type": "Json",
"values": "{\"h\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}"
},
{
"code": "flash_scene_1",
"type": "Json",
"values": "{\"h\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}"
},
{
"code": "flash_scene_2",
"type": "Json",
"values": "{\"h\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}"
},
{
"code": "flash_scene_3",
"type": "Json",
"values": "{\"h\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}"
},
{
"code": "flash_scene_4",
"type": "Json",
"values": "{\"h\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}"
}
],
"status": [
{
"code": "switch_led",
"type": "Boolean",
"values": "{}"
},
{
"code": "work_mode",
"type": "Enum",
"values": "{\"range\":[\"white\",\"colour\"]}"
},
{
"code": "bright_value",
"type": "Integer",
"values": "{\"min\":25,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}"
},
{
"code": "colour_data",
"type": "Json",
"values": "{\"h\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}"
},
{
"code": "scene_data",
"type": "Json",
"values": "{\"h\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}"
},
{
"code": "flash_scene_1",
"type": "Json",
"values": "{\"h\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}"
},
{
"code": "flash_scene_2",
"type": "Json",
"values": "{\"h\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}"
},
{
"code": "flash_scene_3",
"type": "Json",
"values": "{\"h\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}"
},
{
"code": "flash_scene_4",
"type": "Json",
"values": "{\"h\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}"
},
{
"code": "temp_value",
"type": "Integer",
"values": "{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}"
}
]
},
"success": true,
"t": 1627492075303
}

**Comment by tsutsuku** [comment]
According to your category, your device's category is a light though it's a led strip.

**Comment by Krytten** [comment]
The device is shown as unavailable in HA, and the following error is shown in the logs:

```
2021-07-30 17:46:45 ERROR (MainThread) [homeassistant.components.light] Error adding entities for domain light with platform tuya_v2
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 383, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 588, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 666, in add_to_platform_finish
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 419, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 455, in _async_write_ha_state
attr.update(self.state_attributes or {})
File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 851, in state_attributes
data[ATTR_BRIGHTNESS] = self.brightness
File "/config/custom_components/tuya_v2/light.py", line 236, in brightness
old_range = self._tuya_brightness_range()
File "/config/custom_components/tuya_v2/light.py", line 259, in _tuya_brightness_range
bright_value = json.loads(
File "/usr/local/lib/python3.9/json/__init__.py", line 339, in loads
raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not builtin_function_or_method
```
