### ISSUE TITLE
I am getting an "unknown error" trying to add integration

### ISSUE THREAD

**Issue by adamjs83** [tuya/tuya-home-assistant#272]
TimeoutError: [Errno 110] Operation timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fd6e266e8e0>: Failed to establish a new connection: [Errno 110] Operation timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='openapi.tuyacn.com', port=443): Max retries exceeded with url: /v1.0/iot-01/associated-users/actions/authorized-login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd6e266e8e0>: Failed to establish a new connection: [Errno 110] Operation timed out'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 77, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 155, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 63, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 109, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 202, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 260, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/tuya_v2/config_flow.py", line 137, in async_step_user
    response = await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/tuya_v2/config_flow.py", line 94, in _try_login
    response = api.login(
  File "/usr/local/lib/python3.9/site-packages/tuya_iot/openapi.py", line 194, in login
    else self.post(
  File "/usr/local/lib/python3.9/site-packages/tuya_iot/openapi.py", line 305, in post
    return self.__request("POST", path, None, params)
  File "/usr/local/lib/python3.9/site-packages/tuya_iot/openapi.py", line 248, in __request
    response = self.session.request(
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='openapi.tuyacn.com', port=443): Max retries exceeded with url: /v1.0/iot-01/associated-users/actions/authorized-login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd6e266e8e0>: Failed to establish a new connection: [Errno 110] Operation timed out'))

**Comment by xbmcnut** [comment]
Me too from NZ and I note that access to the Tuya developer console from NZ is very slow to load too. Will provide logs tomorrow

**Comment by xbmcnut** [comment]
Under 1.4.1 with country code 64. Also tried country code +64, 44, +44, 1 and +1.
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 77, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 155, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 63, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 109, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 202, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 260, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/tuya_v2/config_flow.py", line 137, in async_step_user
    response = await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/tuya_v2/config_flow.py", line 94, in _try_login
    response = api.login(
  File "/usr/local/lib/python3.9/site-packages/tuya_iot/openapi.py", line 194, in login
    else self.post(
  File "/usr/local/lib/python3.9/site-packages/tuya_iot/openapi.py", line 305, in post
    return self.__request("POST", path, None, params)
  File "/usr/local/lib/python3.9/site-packages/tuya_iot/openapi.py", line 248, in __request
    response = self.session.request(
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='openapi.tuyacn.com', port=443): Max retries exceeded with url: /v1.0/iot-01/associated-users/actions/authorized-login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fed5f5ec1f0>: Failed to establish a new connection: [Errno 110] Operation timed out'))
```

**Comment by tsutsuku** [comment]
change api.endpoint = "https://openapi.tuyacn.com" to  api.endpoint = "https://openapi.tuyaeu.com"
<img width="1104" alt="WeChatWorkScreenshot_ab3e9ad5-2da4-4737-a1b5-4e8f2b757b0a" src="https://user-images.githubusercontent.com/18442047/127795430-3856bfb8-1713-44fb-9842-8edadbc4be5d.png">

**Comment by xbmcnut** [comment]
I can confirm the making the data centre change to https://openapi.tuyaeu.com allowed me to connect from NZ instantly. However, I now get the following error. I have my three devices; one heater and two floor thermostats but no entities, even after a HA restart.
```
2021-08-02 20:45:56 ERROR (Thread-6) [tuya iot] error while get mqtt config
2021-08-02 20:45:56 ERROR (Thread-6) [root] Uncaught thread exception
Traceback (most recent call last):
File "/usr/local/lib/python3.9/threading.py", line 954, in _bootstrap_inner
self.run()
File "/usr/local/lib/python3.9/site-packages/tuya_iot/openmq.py", line 173, in run
time.sleep(self.mq_config.expireTime - 60)
AttributeError: 'TuyaOpenMQ' object has no attribute 'mq_config'
2021-08-02 20:45:57 ERROR (MainThread) [homeassistant.components.climate] Error adding entities for domain climate with platform tuya_v2
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 383, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 499, in _async_add_entity
capabilities=entity.capability_attributes,
File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 219, in capability_attributes
ATTR_HVAC_MODES: self.hvac_modes,
File "/config/custom_components/tuya_v2/climate.py", line 353, in hvac_modes
modes = json.loads(self.tuya_device.function.get(DPCODE_MODE, {}).values).get(
File "/usr/local/lib/python3.9/json/__init__.py", line 339, in loads
raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not builtin_function_or_method
```

**Comment by tsutsuku** [comment]
There are bugs in climate which we will fix in the next release.

**Comment by adamjs83** [comment]
> change api.endpoint = "https://openapi.tuyacn.com" to api.endpoint = "https://openapi.tuyaeu.com"
> <img alt="WeChatWorkScreenshot_ab3e9ad5-2da4-4737-a1b5-4e8f2b757b0a" width="1104" src="https://user-images.githubusercontent.com/18442047/127795430-3856bfb8-1713-44fb-9842-8edadbc4be5d.png">

Where do I make that change?

**Comment by xbmcnut** [comment]
> 
> 
> There are bugs in climate which we will fix in the next release.

Thanks for letting me know. Very professional. Looking forward to the next release.

**Comment by craigmate** [comment]
I also had this same error (I live in austrialia) and after modifing the api.endpoint file, it worked perfectly..

**Comment by xbmcnut** [comment]
Seems the Kogan panel heater appear under 1.5 nut there is no on/off control.
