### ISSUE TITLE
Robot Vacuum Not Working

### ISSUE THREAD

**Issue by MarkWattTech** [tuya/tuya-home-assistant#29]
The new integration for 1.3 adds support for Tuya Robot Vacs. Mine has added successfully but errors if any commands (Clean, stop, return home) are issued.

Battery level is being reported but the robot is stuck is constantly reporting its status as "Cleaning".

**See Log :**

`[547960602336] 'TuyaDeviceManager' object has no attribute 'sendCommands'
[547960602336] Error handling message: Unknown error
Traceback (most recent call last):

  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 760, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/vacuum/__init__.py", line 363, in async_start
    await self.hass.async_add_executor_job(self.start)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/tuya_v2/vacuum.py", line 163, in start
    self.tuya_device_manager.sendCommands(
AttributeError: 'TuyaDeviceManager' object has no attribute 'sendCommands'`

**Comment by tsutsuku** [comment]
@MarkWattTech This problem fixed, can you try branch master again?

**Comment by MarkWattTech** [comment]
@tsutsuku thanks for the quick update. Unfortunately the robot is now showing as unavailable.

I also think the versioning number is incorrect as the update now shows as V1.2 instead of V1.3 (and in HA HACS update it shows an update 1.3 to 1.2)

Cheers.

**Comment by tsutsuku** [comment]
@MarkWattTech Try again?

**Comment by MarkWattTech** [comment]
@tsutsuku commands and version now correct and working 👍 .

The status of the Vacuum is still not updating thought (e.g. Docked, Cleaning). It stays in cleaning.

**Comment by Kodash889** [comment]
Would changing: `DPCODE_STATUS = "status"` to `DPCODE_STATUS = "mode"` resolve this?

**Comment by MarkWattTech** [comment]
@Kodash889 I tried this but it's still stuck on "Cleaning"

**Comment by Kodash889** [comment]
@MarkWattTech That's a shame! I came to the above conclusion by looking in API Explorer -> Get Device Status and changing the state till I found something I wanted :/

**Comment by tsutsuku** [comment]
@MarkWattTech Can you provide your device's specification from the log?

**Comment by Diondelpino** [comment]
I’m also having the same issue vacuum constantly reports state as cleaning.

**Comment by MarkWattTech** [comment]
@tsutsuku sorry for the delay!

`2021-07-05 10:52:44 DEBUG (Thread-5) [tuya iot] Response: {
"code": 28841101,
"msg": "No permissions. This API is not subscribed.",
"success": false,
"t": 1625478764351
}
2021-07-05 10:52:44 ERROR (Thread-5) [tuya iot] error while get mqtt config
2021-07-05 10:52:44 DEBUG (SyncWorker_1) [tuya iot] Response: {
"result": [
{
"active_time": 1625405926,
"biz_type": 18,
"category": "sd",
"create_time": 1612018829,
"icon": "smart/icon/ay1525342233337A874A/1483d61cc5ace09ab8d4e3ba886c1302.png",
"id": "xxxxxxxxxx",
"ip": "86.xxxxxxx",
"lat": "xxxxxxxx",
"local_key": "xxxxxxxxx",
"lon": "xxxxxxxxxx",
"model": "BG800(Bagotte F9070)",
"name": "Tracker",
"online": false,
"owner_id": "xxxxxxxx",
"product_id": "xxxxxxxx",
"product_name": "BG800",
"status": [
{
"code": "power",
"value": true
},
{
"code": "power_go",
"value": false
},
{
"code": "mode",
"value": "standby"
},
{
"code": "direction_control",
"value": "stop"
},
{
"code": "electricity_left",
"value": 10
},
{
"code": "edge_brush",
"value": 75
},
{
"code": "roll_brush",
"value": 88
},
{
"code": "filter",
"value": 75
},
{
"code": "reset_edge_brush",
"value": false
},
{
"code": "reset_roll_brush",
"value": false
},
{
"code": "reset_filter",
"value": false
},
{
"code": "seek",
"value": false
},
{
"code": "clean_record",
"value": "20210701161201901900495"
},
{
"code": "clean_area",
"value": 387
},
{
"code": "clean_time",
"value": 40
}
],`

**Comment by Random483** [comment]
if it helps, here's my log entry too:
`[
    {
      "active_time": 1624529878,
      "biz_type": 18,
      "category": "sd",
      "create_time": 1624529878,
      "icon": "smart/icon/ay1542254159262ZB6ee/d4527a36ed6b5ad995c827f81013446c.png",
      "id": "*****",
      "ip": "***.***.***.***",
      "lat": "***",
      "local_key": "***",
      "lon": "***",
      "name": "Rover",
      "online": true,
      "owner_id": "***",
      "product_id": "***",
      "product_name": "M201",
      "status": [
        {
          "code": "power",
          "value": true
        },
        {
          "code": "power_go",
          "value": false
        },
        {
          "code": "mode",
          "value": "standby"
        },
        {
          "code": "direction_control",
          "value": "foward"
        },
        {
          "code": "electricity_left",
          "value": 100
        },
        {
          "code": "seek",
          "value": true
        },
        {
          "code": "clean_record",
          "value": ""
        }
      ]`

And instructions available for my device are as follows (according to my device on iot.tuya.com)

`{
  "result": {
    "category": "sd",
    "functions": [
      {
        "code": "power",
        "desc": "power",
        "name": "power",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "power_go",
        "desc": "power go",
        "name": "power go",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "mode",
        "desc": "mode",
        "name": "mode",
        "type": "Enum",
        "values": "{\"range\":[\"standby\",\"smart\",\"wall_follow\",\"spiral\",\"chargego\"]}"
      },
      {
        "code": "direction_control",
        "desc": "direction control",
        "name": "direction control",
        "type": "Enum",
        "values": "{\"range\":[\"backward\",\"turn_left\",\"turn_right\",\"stop\"]}"
      },
      {
        "code": "seek",
        "desc": "seek",
        "name": "seek",
        "type": "Boolean",
        "values": "{}"
      }
    ]
  },
  "success": true,
  "t": 1626793740064
}`

**Comment by dougiteixeira** [comment]
> @Kodash889 I tried this but it's still stuck on "Cleaning"

@Kodash889 This problem fixed in #427, can you try branch master again?

**Comment by Kodash889** [comment]
> > @Kodash889 I tried this but it's still stuck on "Cleaning"
> 
> @Kodash889 This problem fixed in #427, can you try branch master again?

@dougiteixeira tried the latest master and same issue unfortunately

**Comment by dougiteixeira** [comment]
> @dougiteixeira tried the latest master and same issue unfortunately

Can you send your robot vacuum Standard Status Set in the debug device API IoT?

For example:
<html>
<body>


Code | Type | Values
-- | -- | --
power | Boolean | "{true,false}"
fault | Bitmap | {   "label": [     "edge_sweep",     "middle_sweep",     "left_wheel",     "right_wheel",     "garbage_box",     "land_check",     "collision"   ] }
electricity_left | Integer | {   "unit": "％",   "min": 0,   "max": 100,   "scale": 0,   "step": 1 }
power_go | Boolean | "{true,false}"
direction_control | Enum | {   "range": [     "backward",     "turn_left",     "turn_right",     "stop"   ] }
mode | Enum | {   "range": [     "standby",     "smart",     "spiral",     "single",     "wall_follow",     "chargego"   ] }
status | Enum | {   "range": [     "standby",     "sleep",     "charging"   ] }
suction | Enum | {   "range": [     "normal"   ] }
voice_switch | Boolean | "{true,false}"
clean_area | Integer | {   "unit": "",   "min": 0,   "max": 1000,   "scale": 0,   "step": 1 }
clean_time | Integer | {   "unit": "",   "min": 0,   "max": 300,   "scale": 0,   "step": 1 }
clean_record | String | {   "maxlen": 255 }


</body>
</html>

**Comment by Kodash889** [comment]
> > @dougiteixeira tried the latest master and same issue unfortunately
> 
> @Kodash889 Can you send your robot vacuum Standard Status Set in the debug device API IoT?
> 
> For example:
> 
<Truncated>

@dougiteixeira Please see below:  For what it's worth. I don't mind making the adjustment manually each time an update is merged? 

<html>
<body>


Code | Type | Values
-- | -- | --
power | Boolean | "{true,false}"
power_go | Boolean | "{true,false}"
mode | Enum | {   "range": [     "standby",     "smart",     "chargego",     "random",     "wall_follow",     "spiral"   ] }
direction_control | Enum | {   "range": [     "forward",     "backward",     "turn_left",     "turn_right",     "stop"   ] }
electricity_left | Integer | {   "unit": "%",   "min": 0,   "max": 100,   "scale": 0,   "step": 1 }
seek | Boolean | "{true,false}"
clean_record | String | {   "maxlen": 255 }
clean_area | Integer | {   "unit": "㎡",   "min": 0,   "max": 9999,   "scale": 0,   "step": 1 }
clean_time | Integer | {   "unit": "min",   "min": 0,   "max": 9999,   "scale": 0,   "step": 1 }
fault | Bitmap | {   "label": [     "edge_sweep",     "middle_sweep",     "left_wheel",     "right_wheel",     "garbage_box",     "land_check",     "collision"   ]


</body>
</html>

**Comment by dougiteixeira** [comment]
> I note that 'status' is missing in the code column for my device.

@Kodash889 
Strange! Without the status code it won't work in this integration, you can even create a custom code for you to replace manually, but it won't have all the features.

Just confirming, these codes are from the Standard Status Set tab?
![image](https://user-images.githubusercontent.com/31328123/133852977-4e162db9-4d19-4d32-b37b-31de1d93debc.png)

**Comment by Kodash889** [comment]
> > I note that 'status' is missing in the code column for my device.
> 
> @Kodash889
> Strange! Without the status code it won't work in this integration, you can even create a custom code for you to replace manually, but it won't have all the features.
> 
> Just confirming, these codes are from the Standard Status Set tab?
> ![image](https://user-images.githubusercontent.com/31328123/133852977-4e162db9-4d19-4d32-b37b-31de1d93debc.png)

Yup it's the Standard Status Set tab :(

I don't mind making the manual change tbh.
