### ISSUE TITLE
[tuya iot] error while get mqtt config

### ISSUE THREAD

**Issue by HawkUser** [tuya/tuya-home-assistant#320]
**Describe the bug**
Home Assistant latest integration, getting:
2021-08-06 23:56:56 ERROR (Thread-5) [tuya iot] error while get mqtt config
2021-08-06 23:56:56 ERROR (Thread-5) [root] Uncaught thread exception
Traceback (most recent call last):
File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
self.run()
File "/usr/local/lib/python3.9/site-packages/tuya_iot/openmq.py", line 173, in run
time.sleep(self.mq_config.expireTime - 60)
AttributeError: 'TuyaOpenMQ' object has no attribute 'mq_config'

**Expected behavior**
The device added after adding the integration, but status updates not working.

**Home Assistant Version**
2021.8.2

**Comment by christippett** [comment]
I had the same issue, I resolved it by enabling the "Device status notification" API in the Tuya IoT platform. If you haven't already I'd give that a go.

![Screenshot - Safari app - 2021-08-09 3 20 03](https://user-images.githubusercontent.com/7218120/128657265-83513f43-1c9b-4d50-b47e-ce3e6ad253ce.png)

**Comment by MickW69** [comment]
All my devices were working fine, now the status updates seem to have stopped, if I reload the integration or reboot HA then they work for a minute or so, then stop.
I already have the device status notification enabled in the IoT platform, have had it for weeks.

**Comment by MickW69** [comment]
Logger: root
Source: helpers/entity.py:604
First occurred: August 17, 2021, 7:12:18 PM (7 occurrences)
Last logged: 7:10:54 AM

Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3452, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1779, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1181, in loop
    rc = self.loop_read(max_packets)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1572, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 2310, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 2936, in _packet_handle
    return self._handle_publish()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3216, in _handle_publish
    self._handle_on_message(message)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3444, in _handle_on_message
    self.on_message(self, self._userdata, message)
  File "/usr/local/lib/python3.9/site-packages/tuya_iot/openmq.py", line 157, in _on_message
    listener(msgDict)
  File "/usr/local/lib/python3.9/site-packages/tuya_iot/device.py", line 175, in on_message
    self._on_device_report(data["devId"], data["status"])
  File "/usr/local/lib/python3.9/site-packages/tuya_iot/device.py", line 196, in _on_device_report
    self.__update_device(device)
  File "/usr/local/lib/python3.9/site-packages/tuya_iot/device.py", line 183, in __update_device
    listener.update_device(device)
  File "/config/custom_components/tuya_v2/__init__.py", line 164, in update_device
    ha_device.schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 604, in schedule_update_ha_state
    self.hass.add_job(self.async_update_ha_state(force_refresh))  # type: ignore
AttributeError: 'NoneType' object has no attribute 'add_job'

**Comment by tsutsuku** [comment]
I think something wrong after the integration start. Can you provide the full log after reboot HA?

**Comment by e1z0** [comment]
Same prob
```
2021-09-17 23:40:37,565] [tuya-openmq] error while get mqtt config
2021-09-17 23:40:37 ERROR (Thread-3) [tuya iot] error while get mqtt config
2021-09-17 23:40:37 ERROR (Thread-3) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/site-packages/tuya_iot/openmq.py", line 173, in run
    time.sleep(self.mq_config.expireTime - 60)
AttributeError: 'TuyaOpenMQ' object has no attribute 'mq_config'

```

Home Assistant 2021.9.6

Led strip lights are working fine, just this error accours...

**Comment by HawkUser** [comment]
> Same prob
> 
> ```
> 
> 2021-09-17 23:40:37,565] [tuya-openmq] error while get mqtt config
> 
> 2021-09-17 23:40:37 ERROR (Thread-3) [tuya iot] error while get mqtt config
> 
> 2021-09-17 23:40:37 ERROR (Thread-3) [root] Uncaught thread exception
> 
> Traceback (most recent call last):
> 
>   File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
> 
>     self.run()
> 
>   File "/usr/local/lib/python3.9/site-packages/tuya_iot/openmq.py", line 173, in run
> 
>     time.sleep(self.mq_config.expireTime - 60)
> 
> AttributeError: 'TuyaOpenMQ' object has no attribute 'mq_config'
> 
> 
> 
> ```
> 
> 
> 
> Home Assistant 2021.9.6
> 
> 
> 
> Led strip lights are working fine, just this error accours...

Hi

This comment solved me the problem

https://github.com/tuya/tuya-home-assistant/issues/320#issuecomment-894926742

**Comment by e1z0** [comment]
> > Same prob
> > ```
> > 
> > 2021-09-17 23:40:37,565] [tuya-openmq] error while get mqtt config
> > 
> > 2021-09-17 23:40:37 ERROR (Thread-3) [tuya iot] error while get mqtt config
> > 
> > 2021-09-17 23:40:37 ERROR (Thread-3) [root] Uncaught thread exception
> > 
> > Traceback (most recent call last):
> > 
> >   File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
> > 
> >     self.run()
> > 
> >   File "/usr/local/lib/python3.9/site-packages/tuya_iot/openmq.py", line 173, in run
> > 
> >     time.sleep(self.mq_config.expireTime - 60)
> > 
> > AttributeError: 'TuyaOpenMQ' object has no attribute 'mq_config'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Home Assistant 2021.9.6
> > Led strip lights are working fine, just this error accours...
> 
> Hi
> 
> This comment solved me the problem
> 
> [#320 (comment)](https://github.com/tuya/tuya-home-assistant/issues/320#issuecomment-894926742)

I have enabled this already :)
