### ISSUE TITLE
Add support for Proscenic 808C Humidifier

### ISSUE THREAD

**Issue by RHeynsZa** [tuya/tuya-home-assistant#36]
I'm not sure if [this humidifier](https://www.proscenic.com/808c-humidifier-p0134.html) is special, or the humidifier support might be broken.

I have the humidifier on Smart Life, and I can see it in the cloud as follows:

![image](https://user-images.githubusercontent.com/58415372/124140718-038ed880-da89-11eb-9448-90a2f1413dfe.png)

But after adding the integration, I just see 2 entities

![image](https://user-images.githubusercontent.com/58415372/124140897-31741d00-da89-11eb-9d6e-44a34d374bff.png)

A light and a general humidifier entity (which has a target humidity value) 
![image](https://user-images.githubusercontent.com/58415372/124141049-5799bd00-da89-11eb-99a8-0d9e8fcaf36b.png)

Neither seem to do anything. 

Im pretty new to the Tuya integration, so please let me know if I'm missing anything

**Comment by tsutsuku** [comment]
@RHeynsZa Can you provide the device's specifications?
https://github.com/tuya/tuya-home-assistant/wiki/How-to-get-the-log

**Comment by RHeynsZa** [comment]
I only see this error in the logs:
```
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
await handler.job.target(service_call)
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
await self.hass.helpers.service.entity_service_call(
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
future.result() # pop exception if have
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 760, in async_request_call
await coro
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
await result
File "/usr/src/homeassistant/homeassistant/components/humidifier/__init__.py", line 161, in async_set_humidity
await self.hass.async_add_executor_job(self.set_humidity, humidity)
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/usr/src/homeassistant/homeassistant/components/humidifier/__init__.py", line 157, in set_humidity
raise NotImplementedError()
NotImplementedError
```

What do you need in terms of specification? I did send the link to the product in the initial comment

**Comment by tsutsuku** [comment]
@RHeynsZa  Get it, I think we can fix it soon.

**Comment by tsutsuku** [comment]
@RHeynsZa Try v1.3.1
