### ISSUE TITLE
No ‘On’ hvac_mode for Smart Heater (climate). Only ‘off’ mode available. Also, cannot control the entity from Lovelace. 

### ISSUE THREAD

**Issue by sabuosba** [tuya/tuya-home-assistant#360]
**Describe the bug**
I cannot turn my smart heater on. I can only turn it off. Only hvac_mode ‘off’ is available. 

Also, cannot control entity from Lovelace interface. It is shown as entity not available

**Expected behavior**
The expected behaviour is to be able to turn my heater on or off. Currently, I have to turn my heater on via Tuya app then I am able to turn it off from HA. 

**Screenshots**
![IMG_0319](https://user-images.githubusercontent.com/23610045/129462149-db5586e4-0da6-4791-8d8a-d541495c8089.jpeg)

![IMG_0320](https://user-images.githubusercontent.com/23610045/129462169-fa4740ef-76d2-436a-8d4a-6880dd1120a9.jpeg)

**Home Assistant Version**
- e.g. 2021.8.1

**Device info (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-home-assistant/wiki/How-to-get-the-log)):**

{
      "active_time": 1628434176,
      "biz_type": 0,
      "category": "qn",
      "create_time": 1568603095,
      "icon": "smart/icon/1470624702_0.jpeg",
      "id": "1450705068c63adecfe3",
      "ip": "***",
      "lat": "***",
      "local_key": "***",
      "lon": "***",
      "model": "PH-ET07EA",
      "name": "Suhail’s Heater",
      "online": true,
      "owner_id": "35037950",
      "product_id": "KA15MYUVDs3P1R0J",
      "product_name": "Panel heater",
      "status": [
        {
          "code": "switch",
          "value": true
        },
        {
          "code": "lock",
          "value": false
        },
        {
          "code": "temp_set",
          "value": 22
        },
        {
          "code": "temp_current",
          "value": 23
        },
        {
          "code": "mode",
          "value": "high"
        }
      ],
      "sub": false,
      "time_zone": "+10:00",
      "uid": "***",
      "update_time": 1628978429,
      "uuid": "1450705068c63adecfe3"
    },

**Device specifications (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-home-assistant/wiki/How-to-get-the-log)):**
Same device's id, like this:

2021-08-15 09:09:13 DEBUG (SyncWorker_3) [tuya iot] Request: method = GET, url = https://openapi.tuyaeu.com/v1.0/devices/1450705068c63adecfe3/specifications, params = None, body = None, t = 1628982553194
2021-08-15 09:09:13 DEBUG (SyncWorker_3) [tuya iot] Response: {
"result": {
"category": "qn",
"functions": [
{
"code": "mode",
"type": "Enum",
"values": "{\"range\":[\"low\",\"high\"]}"
},
{
"code": "temp_set",
"type": "Integer",
"values": "{\"unit\":\"℃\",\"min\":15,\"max\":35,\"scale\":0,\"step\":1}"
},
{
"code": "lock",
"type": "Boolean",
"values": "{}"
},
{
"code": "switch",
"type": "Boolean",
"values": "{}"
}
],
"status": [
{
"code": "mode",
"type": "Enum",
"values": "{\"range\":[\"low\",\"high\"]}"
},
{
"code": "temp_current",
"type": "Integer",
"values": "{\"unit\":\"℃\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
},
{
"code": "temp_set",
"type": "Integer",
"values": "{\"unit\":\"℃\",\"min\":15,\"max\":35,\"scale\":0,\"step\":1}"
},
{
"code": "lock",
"type": "Boolean",
"values": "{}"
},
{
"code": "switch",
"type": "Boolean",
"values": "{}"
}
]
},
"success": true,
"t": 1628982553354
}

**Additional context**

This error was found in the log before adding the the logger to the yams.config file: 

2021-08-15 08:32:24 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 451, in async_update_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 498, in _async_write_ha_state
state = self._stringify_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 470, in _stringify_state
state = self.state
File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 210, in state
return self.hvac_mode
File "/config/custom_components/tuya_v2/climate.py", line 361, in hvac_mode
return TUYA_HVAC_TO_HA[self.tuya_device.status.get(DPCODE_MODE)]
KeyError: 'high'

**Comment by ferg-1964** [comment]
Same issue. My heater will turn on using Auto though. I wrote a script to turn it on:

heater_on:
  alias: Heater ON
  sequence:
  - service: climate.set_hvac_mode
    target:
      device_id: 180a5cc2122bbd37a8e11a6d9d8450b6
    data:
      hvac_mode: auto
  mode: single
  icon: mdi:radiator

Note the service - climate.set_hvac_mode. 

When compiling your script in UI and selecting the service climate.set_hvac_mode.  you'll be offered a checkbox: 
HVAC mode  - then a a space to add data - New value of operation mode. Enter "Auto"

Don't forget to select you heater as a device or entity. 

Hope this works for you.

**Comment by sabuosba** [comment]
Thanks for leaving a comment. I tired adding the script but I get an error saying 

Message malformed: extra keys not allowed @ data['heater_on']

I had noticed that my 'off' button works.

**Comment by ferg-1964** [comment]
iI think you may have some format/indent issues. Mine looks like this:

alias: Heater ON
sequence:
  - service: climate.set_hvac_mode
    target:
      device_id: 180a5cc2122bbd37a8e11a6d9d8450b6
    data:
      hvac_mode: auto
mode: single
icon: mdi:radiator

![script](https://user-images.githubusercontent.com/68699991/130366448-2f56aafd-a7ca-4c15-a02d-d4724e9adafd.png)
