### ISSUE TITLE
switch device not functioning

### ISSUE THREAD

**Issue by kbarendrecht** [tuya/tuya-home-assistant#39]
The only device currently attached to my Tuya developer account doesnt work good.
When using the entity toggle on the lovelace dashboard it only works the verry first time, after that it only switches the toggle and returns back to its previous state, without actually switching the light.

![toggle](https://user-images.githubusercontent.com/18546657/124138167-abef6d80-da86-11eb-8e85-a58035cad140.gif)

logs shows these errors;

```log
Logger: root
Source: /usr/src/homeassistant/homeassistant/bootstrap.py:315
First occurred: 15:55:28 (1 occurrences)
Last logged: 15:55:28

Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/site-packages/tuya_iot/openmq.py", line 173, in run
    time.sleep(self.mq_config.expireTime - 60)
AttributeError: 'TuyaOpenMQ' object has no attribute 'mq_config'

Logger: tuya iot
Source: /usr/local/lib/python3.8/site-packages/tuya_iot/openmq.py:178
First occurred: 15:55:28 (1 occurrences)
Last logged: 15:55:28

error while get mqtt config
```

and `config/home-assistant.log` shows;
```
2021-07-01 15:55:28 ERROR (Thread-4) [tuya iot] error while get mqtt config
2021-07-01 15:55:28 ERROR (Thread-4) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/site-packages/tuya_iot/openmq.py", line 173, in run
    time.sleep(self.mq_config.expireTime - 60)
AttributeError: 'TuyaOpenMQ' object has no attribute 'mq_config'

**Comment by tsutsuku** [comment]
@kbarendrecht It seems something wrong with the TuyaOpenMQ connect, Can you provide more logs?

**Comment by kbarendrecht** [comment]
@tsutsuku This is all there is in the Home Assistant UI; Configuration -> Logs. Is there somewhere I could find more?

```
2021-07-01 21:03:12 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration tuya_v2 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-07-01 21:03:17 ERROR (Thread-5) [tuya iot] error while get mqtt config
2021-07-01 21:03:17 ERROR (Thread-5) [root] Uncaught thread exception
Traceback (most recent call last):
File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
self.run()
File "/usr/local/lib/python3.8/site-packages/tuya_iot/openmq.py", line 173, in run
time.sleep(self.mq_config.expireTime - 60)
AttributeError: 'TuyaOpenMQ' object has no attribute 'mq_config'

**Comment by kbarendrecht** [comment]
I have uninstalled the custom_component from HACS, then deleted the integration, then installed and set up the integration. Still have the same problem. Could it have something to do with the device type showing up as 'video camera' while it shows as 'switch' in the tuya IOT platform? (it is a switch)
![image](https://user-images.githubusercontent.com/18546657/124385981-56120400-dcd8-11eb-8a07-0b8736a373e5.png)
![image](https://user-images.githubusercontent.com/18546657/124385985-5d391200-dcd8-11eb-976a-c4943503bfae.png)

**Comment by tsutsuku** [comment]
@kbarendrecht  Try v1.3.1.

**Comment by kbarendrecht** [comment]
@tsutsuku Still the same.

**Comment by kbarendrecht** [comment]
@tsutsuku This is working now, thanks to the new setup guide 😄
The problem was not having the `Device status notification API`.
