### ISSUE TITLE
Tuya_v2 added but there are no devices. I can see all my devices in loT Platform

### ISSUE THREAD

**Issue by advertisingfree** [tuya/tuya-home-assistant#392]
**Describe the bug**
Tuya v2 has no device. I can see all my devices in loT Platform and old tuya has all devices.
**Expected behavior**
There should be a list of devices under Tuya_v2

**Screenshots**
![image](https://user-images.githubusercontent.com/52855795/130227376-27da1866-faba-4ac7-b639-747303ec9896.png)

**Home Assistant Version**
- 2021.1.5
- Tuya v2 - v1.5.0

Logger: homeassistant.config_entries
Source: C:\Users\adver\AppData\Roaming\Python\Python37\site-packages\homeassistant\config_entries.py:264
First occurred: 9:09:27 PM (1 occurrences)
Last logged: 9:09:27 PM

Error setting up entry xxx@hotmail.com for tuya_v2
Traceback (most recent call last):
  File "C:\Users\adver\AppData\Roaming\Python\Python37\site-packages\homeassistant\config_entries.py", line 236, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "C:\Users\adver\AppData\Roaming\.homeassistant\custom_components\tuya_v2\__init__.py", line 295, in async_setup_entry
    success = await _init_tuya_sdk(hass, entry)
  File "C:\Users\adver\AppData\Roaming\.homeassistant\custom_components\tuya_v2\__init__.py", line 207, in _init_tuya_sdk
    await cleanup_device_registry(hass)
  File "C:\Users\adver\AppData\Roaming\.homeassistant\custom_components\tuya_v2\__init__.py", line 224, in cleanup_device_registry
    device_registry = hass.helpers.device_registry.async_get(hass)
  File "C:\Users\adver\AppData\Roaming\Python\Python37\site-packages\homeassistant\loader.py", line 591, in __getattr__
    value = getattr(self._module, attr)
AttributeError: module 'homeassistant.helpers.device_registry' has no attribute 'async_get'
**Additional context**
I have removed and installed older version but the issue persists

**Comment by Omnimercador** [comment]
I have the same with a HA installation on Synology Debian.

**Comment by tsutsuku** [comment]
Update Home Assistant to lastest version.

**Comment by advertisingfree** [comment]
I thought it was already up to date. Anyway, I rebuilt my computer and reinstalled everything.

Everything is working as expected. Thank you.
