### ISSUE TITLE
Smart plug not working

### ISSUE THREAD

**Issue by marcos-acpc** [tuya/tuya-home-assistant#396]
**Describe the bug**
Smart plug dont work, its detected upon inhttps://github.com/tuya/tuya-home-assistant/wiki/How-to-get-the-logstallation but after beeing used the fisrt time on a lovelace switch it stops to to work/update state.

**Expected behavior**
swiith on/off and report state

**Screenshots**
![image](https://user-images.githubusercontent.com/47359588/130304415-26c293d9-f2bc-44d4-9643-caebe6272986.png)

**Home Assistant Version**
Home Assistant 2021.8.8

**Device info (please complete the following information, which can be found in [log]()):**
like this:
2021-08-21 00:33:52 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-08-21 00:33:52 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration tuya_v2 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-08-21 00:33:55 ERROR (Thread-3) [tuya iot] error while get mqtt config
2021-08-21 00:33:55 ERROR (Thread-3) [root] Uncaught thread exception
Traceback (most recent call last):
File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
self.run()
File "/usr/local/lib/python3.9/site-packages/tuya_iot/openmq.py", line 173, in run
time.sleep(self.mq_config.expireTime - 60)
AttributeError: 'TuyaOpenMQ' object has no attribute 'mq_config'
2021-08-21 00:33:58 ERROR (MainThread) [custom_components.hacs] tellerbop/havistapool - Repository is archived.

**Comment by tsutsuku** [comment]
Check this https://github.com/tuya/tuya-home-assistant/discussions/113

**Comment by marcos-acpc** [comment]
it worked thanks
