### ISSUE TITLE
'NoneType' object has no attribute 'add_job'

### ISSUE THREAD

**Issue by tomhash2** [tuya/tuya-home-assistant#401]
**Describe the bug**
When trying to turn on smart socket, switch in HA doesn't goes on but socket turns on. Error appears in log and no tuya device is working any more from HA.

**Home Assistant Version**
2021.8.8

2021-08-20 12:21:27 DEBUG (Thread-5) [tuya iot] on_message: {'data': {'dataId': '0cde8efc-3ebb-4284-bdd6-42e4e4771710', 'devId': '002616442462ab482690', 'productKey': '*************', 'st
atus': [{'1': True, 'code': 'switch_1', 't': '1629454886', 'value': True}]}, 'protocol': 4, 'pv': '2.0', 'sign': '6d5c7b977334a07142a642e03a1e18df', 't': 1629454886}
2021-08-20 12:21:27 DEBUG (Thread-5) [tuya iot] mq receive-> {'data': {'dataId': '0cde8efc-3ebb-4284-bdd6-42e4e4771710', 'devId': '002616442462ab482690', 'productKey': '**************', 's
tatus': [{'1': True, 'code': 'switch_1', 't': '1629454886', 'value': True}]}, 'protocol': 4, 'pv': '2.0', 'sign': '6d5c7b977334a07142a642e03a1e18df', 't': 1629454886}
2021-08-20 12:21:27 DEBUG (Thread-5) [tuya iot] mq _on_device_report-> [{'1': True, 'code': 'switch_1', 't': '1629454886', 'value': True}]
2021-08-20 12:21:27 DEBUG (Thread-5) [custom_components.tuya_v2] _update--><custom_components.tuya_v2._init_tuya_sdk.<locals>.DeviceListener object at 0x7ff6a3cf54f0>;->>{'switch_1': True, '
countdown_1': 0, 'add_ele': 2, 'cur_current': 184, 'cur_power': 419, 'cur_voltage': 2324}
2021-08-20 12:21:27 DEBUG (Thread-5) [tuya iot] _on_log: Caught exception in on_message: 'NoneType' object has no attribute 'add_job'
2021-08-20 12:21:27 ERROR (Thread-5) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3452, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1779, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1181, in loop
    rc = self.loop_read(max_packets)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1572, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 2310, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 2936, in _packet_handle
    return self._handle_publish()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3216, in _handle_publish
    self._handle_on_message(message)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3444, in _handle_on_message
    self.on_message(self, self._userdata, message)
  File "/usr/local/lib/python3.9/site-packages/tuya_iot/openmq.py", line 157, in _on_message
    listener(msgDict)
  File "/usr/local/lib/python3.9/site-packages/tuya_iot/device.py", line 175, in on_message
    self._on_device_report(data["devId"], data["status"])
  File "/usr/local/lib/python3.9/site-packages/tuya_iot/device.py", line 196, in _on_device_report
    self.__update_device(device)
  File "/usr/local/lib/python3.9/site-packages/tuya_iot/device.py", line 183, in __update_device
    listener.update_device(device)
  File "/config/custom_components/tuya_v2/__init__.py", line 164, in update_device
    ha_device.schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 604, in schedule_update_ha_state
    self.hass.add_job(self.async_update_ha_state(force_refresh))  # type: ignore
AttributeError: 'NoneType' object has no attribute 'add_job'

**Comment by tomhash2** [comment]
Same here #375...

**Comment by tsutsuku** [comment]
@tomhash2 Can you create a ticket and provide your account info through it? Then we can track it.

**Comment by tomhash2** [comment]
I have created a ticket and provided necessary info about my account.
