### ISSUE TITLE
Light swtch turns off right away even if light turns on

### ISSUE THREAD

**Issue by Jezza991** [tuya/tuya-home-assistant#409]
**Describe the bug**
Havent looked at others but this light when clicked on overview page light turns on then the blue switch turns back off

**Expected behavior**
blue switch should stay on to indicate light is on

**Screenshots**

**Home Assistant Version**
2021.8.8

**Device info (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-home-assistant/wiki/How-to-get-the-log)):**
like this:
This doesn't look light what was here sorry if its wrong

2021-08-24 19:19:24 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 451, in async_update_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 500, in _async_write_ha_state
attr.update(self.state_attributes or {})
File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 872, in state_attributes
data[ATTR_COLOR_TEMP] = self.color_temp
File "/config/custom_components/tuya_v2/light.py", line 296, in color_temp
new_range = self._tuya_temp_range()
File "/config/custom_components/tuya_v2/light.py", line 322, in _tuya_temp_range
temp_value = json.loads(
File "/usr/local/lib/python3.9/json/__init__.py", line 339, in loads
raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not builtin_function_or_method

**Device specifications (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-home-assistant/wiki/How-to-get-the-log)):**
Same device's id, like this:
{
  "result": {
    "active_time": 1617229992,
    "biz_type": 0,
    "category": "dj",
    "create_time": 1544083087,
    "icon": "smart/icon/15176375065n1lxde7uvynulccdc1rau4n29_0.png",
    "id": "",
    "ip": "",
    "lat": "",
    "local_key": "",
    "lon": "",
    "model": "I002338 I002339",
    "name": "living room light",
    "online": true,
    "owner_id": "",
    "product_id": "awkemi7dd28sv3wA",
    "product_name": "Genio RGBW Bulb",
    "status": [
      {
        "code": "switch_led",
        "value": false
      },
      {
        "code": "work_mode",
        "value": "white"
      },
      {
        "code": "bright_value",
        "value": 255
      },
      {
        "code": "temp_value",
        "value": 255
      },
      {
        "code": "colour_data",
        "value": "{\"h\":51.0,\"s\":255.0,\"v\":255.0}"
      },
      {
        "code": "scene_data",
        "value": "{\"h\":37.5,\"s\":255.0,\"v\":189.0}"
      },
      {
        "code": "flash_scene_1",
        "value": "{\"bright\":255,\"frequency\":80,\"hsv\":[{\"h\":120.0,\"s\":255.0,\"v\":255.0}],\"temperature\":255}"
      },
      {
        "code": "flash_scene_2",
        "value": "{\"bright\":255,\"frequency\":128,\"hsv\":[{\"h\":0.0,\"s\":255.0,\"v\":255.0},{\"h\":120.0,\"s\":255.0,\"v\":255.0},{\"h\":240.0,\"s\":255.0,\"v\":255.0},{\"h\":0.0,\"s\":0.0,\"v\":0.0},{\"h\":0.0,\"s\":0.0,\"v\":0.0},{\"h\":0.0,\"s\":0.0,\"v\":0.0}],\"temperature\":255}"
      },
      {
        "code": "flash_scene_3",
        "value": "{\"bright\":255,\"frequency\":80,\"hsv\":[{\"h\":0.0,\"s\":255.0,\"v\":255.0}],\"temperature\":255}"
      },
      {
        "code": "flash_scene_4",
        "value": "{\"bright\":255,\"frequency\":5,\"hsv\":[{\"h\":0.0,\"s\":255.0,\"v\":255.0},{\"h\":120.0,\"s\":255.0,\"v\":255.0},{\"h\":60.0,\"s\":255.0,\"v\":255.0},{\"h\":300.0,\"s\":255.0,\"v\":255.0},{\"h\":240.0,\"s\":255.0,\"v\":255.0},{\"h\":0.0,\"s\":0.0,\"v\":0.0}],\"temperature\":255}"
      }
    ],
    "sub": false,
    "time_zone": "+10:00",
    "uid": "eu1595042920960xyoEn",
    "update_time": 1629557210,
    "uuid": "16201510807d3a391641"
  },
  "success": true,
  "t": 1629797524659
}

**Additional context**
Add any other context or logs about the problem here.

**Comment by solairx** [comment]
I have same issue with similar device

**Comment by nuno-azevedo** [comment]
I have the same problem as well.

**Comment by tsutsuku** [comment]
@Jezza991 Can you provide your device specifications? The log you have provided is device info.

**Comment by Jezza991** [comment]
> device specifications? The log you have provided is device info.

This maybe?

{
  "result": {
    "category": "dj",
    "functions": [
      {
        "code": "switch_led",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "bright_value",
        "type": "Integer",
        "values": "{\"min\":25,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}"
      },
      {
        "code": "work_mode",
        "type": "Enum",
        "values": "{\"range\":[\"white\",\"colour\"]}"
      },
      {
        "code": "colour_data",
        "type": "Json",
        "values": "{\"h\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}"
      },
      {
        "code": "scene_data",
        "type": "Json",
        "values": "{\"h\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}"
      },
      {
        "code": "flash_scene_1",
        "type": "Json",
        "values": "{\"h\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}"
      },
      {
        "code": "flash_scene_2",
        "type": "Json",
        "values": "{\"h\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}"
      },
      {
        "code": "flash_scene_3",
        "type": "Json",
        "values": "{\"h\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}"
      },
      {
        "code": "flash_scene_4",
        "type": "Json",
        "values": "{\"h\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}"
      }
    ],
    "status": [
      {
        "code": "switch_led",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "work_mode",
        "type": "Enum",
        "values": "{\"range\":[\"white\",\"colour\"]}"
      },
      {
        "code": "bright_value",
        "type": "Integer",
        "values": "{\"min\":25,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}"
      },
      {
        "code": "colour_data",
        "type": "Json",
        "values": "{\"h\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}"
      },
      {
        "code": "scene_data",
        "type": "Json",
        "values": "{\"h\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}"
      },
      {
        "code": "flash_scene_1",
        "type": "Json",
        "values": "{\"h\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}"
      },
      {
        "code": "flash_scene_2",
        "type": "Json",
        "values": "{\"h\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}"
      },
      {
        "code": "flash_scene_3",
        "type": "Json",
        "values": "{\"h\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}"
      },
      {
        "code": "flash_scene_4",
        "type": "Json",
        "values": "{\"h\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}"
      },
      {
        "code": "temp_value",
        "type": "Integer",
        "values": "{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1629861093715
}

**Comment by Jezza991** [comment]
@tsutsuku I have added the Device Status Notification api after connecting Ha, Tuya v2 & Tuya dev site together

**Comment by Jezza991** [comment]
unsure how to test that this is fixed. its been more than 2 days. and in HA its still doing the same thing

**Comment by Czechmarty** [comment]
Was this ever fixed I have the same problem with ALL my linked devices.

**Comment by Czechmarty** [comment]
So here is what I have done and hope this will have somebody...
Deleted TuyaV2 integration
Went back to Tyya IoT Web and resubcribed to the Device status notification (order and purchase for $0)
Deleted linked Tuya (SL) apps from all projects
Added only SL app to this V2 project (I used to have local Tuya before).
Went back and reinstalled Tuya V2 in HA.
That fixed the "stuck" toggle switches.
