### ISSUE TITLE
Current, Voltage and Current Power sensors not created

### ISSUE THREAD

**Issue by madtech360** [tuya/tuya-home-assistant#449]
**Describe the bug**
Current, Voltage and Current Power sensors are not added to the Socket with Energy Monitoring.

Expected behavior
The device created should have the Current, Voltage and Power Entities

Screenshots
N/A

Home Assistant Version
core-2021.8.8 running on RPi4

**Logs from HA:**
**Device Property:**
"result": [
{
"active_time": 1630073221,
"biz_type": 18,
"category": "cz",
"create_time": 1630073221,
"icon": "smart/icon/ay1566213486844mN9sD/2b1c6043b8352cff8c721efc6f914a0a.png",
"id": "***",
"ip": "***",
"lat": "***",
"local_key": "***",
"lon": "***",
"model": "",
"name": "Heater",
"online": true,
"owner_id": "***",
"product_id": "egzqvwetxozt5dqo",
"product_name": "16A Smart Plug",
"status": [
{
"code": "switch_1",
"value": false
},
{
"code": "countdown_1",
"value": 0
},
{
"code": "add_ele",
"value": 50
},
{
"code": "cur_current",
"value": 0
},
{
"code": "cur_power",
"value": 0
},
{
"code": "cur_voltage",
"value": 2575
}
],
"sub": false,
"time_zone": "+05:30",
"uid": "***",
"update_time": 1630911012,
"uuid": "22335856c4dd57221f10"
}
],

Device Spec from Log:
"result": {
"category": "cz",
"functions": [
{
"code": "switch_1",
"type": "Boolean",
"values": "{}"
},
{
"code": "countdown_1",
"type": "Integer",
"values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
}
],
"status": [
{
"code": "switch_1",
"type": "Boolean",
"values": "{}"
},
{
"code": "countdown_1",
"type": "Integer",
"values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
},
{
"code": "add_ele",
"type": "Integer",
"values": "{\"unit\":\"kwh\",\"min\":0,\"max\":50000,\"scale\":3,\"step\":100}"
},
{
"code": "cur_current",
"type": "Integer",
"values": "{\"unit\":\"mA\",\"min\":0,\"max\":30000,\"scale\":0,\"step\":1}"
},
{
"code": "cur_power",
"type": "Integer",
"values": "{\"unit\":\"W\",\"min\":0,\"max\":50000,\"scale\":1,\"step\":1}"
},
{
"code": "cur_voltage",
"type": "Integer",
"values": "{\"unit\":\"V\",\"min\":0,\"max\":5000,\"scale\":1,\"step\":1}"
}
]
},
"success": true,
"t": 1631017315978
}

**Below Error while setting by the sensor:**
2021-09-07 17:51:57 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up tuya_v2 platform for sensor
Traceback (most recent call last):
File "/srv/ha/lib/python3.8/site-packages/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
await asyncio.shield(task)
File "/home/ha/.homeassistant/custom_components/tuya_v2/sensor.py", line 143, in async_setup_entry
await async_discover_device(device_ids)
File "/home/ha/.homeassistant/custom_components/tuya_v2/sensor.py", line 130, in async_discover_device
entities = await hass.async_add_executor_job(_setup_entities, hass, dev_ids)
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/home/ha/.homeassistant/custom_components/tuya_v2/sensor.py", line 357, in _setup_entities
TuyaHaSensor(
File "/home/ha/.homeassistant/custom_components/tuya_v2/sensor.py", line 474, in __init__
self._attr_name = self.tuya_device.name + "_" + self._attr_device_class
**AttributeError: 'TuyaHaSensor' object has no attribute 'tuya_device'**

I have HA core-2021.8.8 running a RPi 4.

**Comment by madtech360** [comment]
I was able to resolve Attribute Error of the issue by moving the initialization code in TuyaHaSensor class before trying to access the attribute.

**super().__init__(device, device_manager)**

But I am still having all three sensors being added. The current sensor gets added and remaining two sensors (voltage and power) are ignored as they are getting generated with the same ids. I tried updating the code, still no success. Continuing to tweak the code. 

**Any help is appreciated**

class TuyaHaSensor(TuyaHaDevice, SensorEntity):
    """Tuya Sensor Device."""

    def __init__(
        self,
        device: TuyaDevice,
        device_manager: TuyaDeviceManager,
        sensor_type: str,
        sensor_code: str,
        sensor_unit: str,
    ) -> None:
        """Init TuyaHaSensor."""
        self._code = sensor_code
        self._attr_device_class = sensor_type
        self._attr_name = self.tuya_device.name + "_" + self._attr_device_class
        self._attr_unique_id = f"{super().unique_id}{self._code}"
        self._attr_unit_of_measurement = sensor_unit
        self._attr_available = True
        super().__init__(device, device_manager)

For now I have disabled adding Current and Voltage sensor, as all I need is the power sensor. As as been reported in multiple places, the power sensor does not get updated frequently and gets updated only if the SmartLife/Tuya app open with Ele tab open. 

So unless the Power status is updated whenever there is a change, it cannot be used to calculate energy consumption.

**Comment by madtech360** [comment]
Resolved the duplicate entity issue by making changes TuyaHaSensor class as shown below

class TuyaHaSensor(TuyaHaDevice, SensorEntity):
    """Tuya Sensor Device."""

    def __init__(
        self,
        device: TuyaDevice,
        device_manager: TuyaDeviceManager,
        sensor_type: str,
        sensor_code: str,
        sensor_unit: str,
    ) -> None:
        """Init TuyaHaSensor."""

        super().__init__(device, device_manager)
        self._code = sensor_code
        self._attr_device_class = sensor_type
        #self._attr_name = device.name + "_" + self._attr_device_class
        #self._attr_unique_id = f"{device.id}{self._code}"
        self._attr_unit_of_measurement = sensor_unit
        self._attr_available = True
        #super().__init__(device, device_manager)

    @property
    def unique_id(self):
        """Return a unique ID."""
        return f"{super().unique_id}{self._code}"

    @property
    def name(self):
        """Return the name of the sensor."""
        return self.tuya_device.name + "_" + self._attr_device_class

    @property
    def state(self) -> StateType:
        """Return the state of the sensor."""
        if self.tuya_device.category == "zndb" and self._code.startswith("phase_"):
            __value = json.loads(self.tuya_device.status.get(self._code[:7])).get(
                self._code[8:]
            )
            return __value

        __value = self.tuya_device.status.get(self._code)
        if self.tuya_device.status_range.get(self._code).type == "Integer":
            __value_range = json.loads(
                self.tuya_device.status_range.get(self._code).values
            )
            __state = (__value) * 1.0 / (10 ** __value_range.get("scale"))
            if __value_range.get("scale") == 0:
                return int(__state)
            return f"%.{__value_range.get('scale')}f" % __state
        return ""

The current way of adding name and entity id was not working and may be someone should make the above changes so the sensors will be added correctly.
