### ISSUE TITLE
Tuya V2 Switch icon toggles back within seconds

### ISSUE THREAD

**Issue by Segran** [tuya/tuya-home-assistant#515]
**Describe the bug**
With Tuya V2 integration the Tuya Smart switches symbol do not stay in the user selected mode/position, within a couple of seconds it toggles back to the original mode/position - however, the Smart Switch relay stays as selected (on or off). This is not the case with the older Tuya integration, here the switch symbol stays as it should.
**Expected behavior**

The switch symbol/icon should stay in the position the user have selected until the user issues new command.

**Screenshots**
Have a video demonstrating this: 
https://user-images.githubusercontent.com/5622873/135678662-595f50a1-fd1c-4491-98f0-daa13d48c5f6.MOV

**Home Assistant Version**
- e.g. 2021.4.6

**Device info (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-home-assistant/wiki/How-to-get-the-log)):**
like this:
2021-10-01 20:42:14 WARNING (MainThread) [homeassistant.loader] You are using a custom integration blitzortung which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-01 20:42:14 WARNING (MainThread) [homeassistant.loader] You are using a custom integration panasonic_cc which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-01 20:42:14 WARNING (MainThread) [homeassistant.loader] You are using a custom integration nordpool which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-01 20:42:14 WARNING (MainThread) [homeassistant.loader] You are using a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-01 20:42:14 WARNING (MainThread) [homeassistant.loader] You are using a custom integration automower which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-01 20:42:14 WARNING (MainThread) [homeassistant.loader] You are using a custom integration audiconnect which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-01 20:42:14 WARNING (MainThread) [homeassistant.loader] You are using a custom integration nibe which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-01 20:42:14 WARNING (Recorder) [homeassistant.components.recorder.migration] Database is about to upgrade. Schema version: 18
2021-10-01 20:42:17 WARNING (MainThread) [homeassistant.loader] You are using a custom integration panasonic_ac which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-01 20:42:22 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up nordpool platform for sensor
Traceback (most recent call last):
  File "/Users/MiniMac/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity_platform.py", line 205, in _async_setup_platform
    await asyncio.shield(task)
  File "/Users/MiniMac/.homeassistant/custom_components/nordpool/sensor.py", line 121, in async_setup_entry
    _dry_setup(hass, config, async_add_devices)
  File "/Users/MiniMac/.homeassistant/custom_components/nordpool/sensor.py", line 96, in _dry_setup
    sensor = NordpoolSensor(
  File "/Users/MiniMac/.homeassistant/custom_components/nordpool/sensor.py", line 178, in __init__
    self._ad_template = cv.template(self._ad_template)
  File "/Users/MiniMac/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/config_validation.py", line 541, in template
    raise vol.Invalid("template value is None")
voluptuous.error.Invalid: template value is None
2021-10-01 20:42:24 ERROR (MainThread) [custom_components.hacs] Task setup_sensor failed: 'ConfigEntries' object has no attribute 'async_setup_platforms'
2021-10-01 20:42:24 ERROR (MainThread) [snitun.client.client_peer] Challenge/Response error with SniTun server
2021-10-01 20:42:24 ERROR (MainThread) [hass_nabucasa.remote] Connection problem to snitun server
2021-10-01 20:42:24 WARNING (MainThread) [homeassistant.loader] You are using a custom integration tuya_v2 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-01 20:42:25 WARNING (MainThread) [homeassistant.loader] You are using a custom integration husqvarna_automower which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-10-01 20:42:42 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Rapsv10' for gogogate2 integration not ready yet: Error communicating with API: ; Retrying in background
2021-10-01 20:42:44 WARNING (MainThread) [homeassistant.components.climate] Setup of climate platform nibe is taking over 10 seconds.
2021-10-01 20:42:44 WARNING (MainThread) [homeassistant.components.water_heater] Setup of water_heater platform nibe is taking over 10 seconds.
2021-10-01 20:42:44 WARNING (MainThread) [homeassistant.components.fan] Setup of fan platform nibe is taking over 10 seconds.
2021-10-01 20:42:53 WARNING (MainThread) [homeassistant.components.homekit] The bridge HASS Bridge 26E0 has entity lock.audi_a4_allroad_2018_door_lock. For best performance, and to prevent unexpected unavailability, create and pair a separate HomeKit instance in accessory mode for this entity
2021-10-01 20:42:53 ERROR (MainThread) [pyhap.characteristic] TargetHeatingCoolingState: value=0 is an invalid value.
2021-10-01 20:42:54 WARNING (MainThread) [homeassistant.components.esphome] Can't connect to ESPHome API for esp32cam2 (192.168.1.219): Timeout while connecting to ('192.168.1.219', 6053)
2021-10-01 20:47:32 ERROR (Thread-9) [tuya iot] error while get mqtt config
2021-10-01 20:47:32 ERROR (Thread-9) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/Users/MiniMac/.pyenv/versions/3.8.6/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Users/MiniMac/homeassistant/lib/python3.8/site-packages/tuya_iot/openmq.py", line 173, in run
    time.sleep(self.mq_config.expireTime - 60)
AttributeError: 'TuyaOpenMQ' object has no attribute 'mq_config'
2021-10-01 20:47:32 ERROR (MainThread) [homeassistant.setup] Setup failed for select: Integration not found.
2021-10-01 21:03:03 ERROR (MainThread) [homeassistant.components.upnp] Unexpected error fetching F@st5370e Telia data: Error during async_call(), status: 403, body: <html><body><h1>403 Forbidden</h1></body></html>
Traceback (most recent call last):
  File "/Users/MiniMac/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/update_coordinator.py", line 173, in _async_refresh
    self.data = await self._async_update_data()
  File "/Users/MiniMac/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/update_coordinator.py", line 143, in _async_update_data
    return await self.update_method()
  File "/Users/MiniMac/homeassistant/lib/python3.8/site-packages/homeassistant/components/upnp/device.py", line 156, in async_get_traffic_data
    values = await asyncio.gather(
  File "/Users/MiniMac/homeassistant/lib/python3.8/site-packages/async_upnp_client/profiles/igd.py", line 103, in async_get_total_bytes_sent
    result = await action.async_call()
  File "/Users/MiniMac/homeassistant/lib/python3.8/site-packages/async_upnp_client/client.py", line 560, in async_call
    raise UpnpError(
async_upnp_client.client.UpnpError: Error during async_call(), status: 403, body: <html><body><h1>403 Forbidden</h1></body></html>
2021-10-01 21:30:33 ERROR (MainThread) [homeassistant.components.upnp] Unexpected error fetching F@st5370e Telia data: Error during async_call(), status: 403, body: <html><body><h1>403 Forbidden</h1></body></html>
Traceback (most recent call last):
  File "/Users/MiniMac/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/update_coordinator.py", line 173, in _async_refresh
    self.data = await self._async_update_data()
  File "/Users/MiniMac/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/update_coordinator.py", line 143, in _async_update_data
    return await self.update_method()
  File "/Users/MiniMac/homeassistant/lib/python3.8/site-packages/homeassistant/components/upnp/device.py", line 156, in async_get_traffic_data
    values = await asyncio.gather(
  File "/Users/MiniMac/homeassistant/lib/python3.8/site-packages/async_upnp_client/profiles/igd.py", line 113, in async_get_total_packets_received
    result = await action.async_call()
  File "/Users/MiniMac/homeassistant/lib/python3.8/site-packages/async_upnp_client/client.py", line 560, in async_call
    raise UpnpError(
async_upnp_client.client.UpnpError: Error during async_call(), status: 403, body: <html><body><h1>403 Forbidden</h1></body></html>

> [``](

- 

- [ ] @ #1. url

)

**Comment by nfrawley93** [comment]
Likely similar to my issue posted here. Might want to try and see if any of these fix the issue. Although they did not fix mine.

#496

**Comment by Segran** [comment]
nfrawley93 - yes, it is exactly what you posted in 496. And no, none of the suggestions had any effect. 

To further clarify:
The switch operates perfectly well when controlled by Automations, but the switch icon/GUI in Lovelace lives it’s own life vompletely detached from the true state of the switch.

**Comment by burnworld3d** [comment]
Same as with mine #419

**Comment by GazTheGeek** [comment]
I had the same problem. Tried a bunch of things. Reinstalled the integration in HACS and in HA. Nothing. The with would turn off/on ok using smart life app but nothing in Lovelace. Eventually I just unplugged the smart switch and plugged it back in again. Works fine again. Go figure.

**Comment by almico** [comment]
Similar issue here, except that even Automations are unable to change the state of the switch.

**Comment by kurankat** [comment]
> I had the same problem. Tried a bunch of things. Reinstalled the integration in HACS and in HA. Nothing. The with would turn off/on ok using smart life app but nothing in Lovelace. Eventually I just unplugged the smart switch and plugged it back in again. Works fine again. Go figure.

Same for me. Hard power cycle fixed this same problem.

**Comment by shlomosv1** [comment]
same with me the he switch symbol/icon toggles back within second... HELP....

**Comment by jypsie** [comment]
Similar problem here (only one of the many). Switch toggles back (I also have: switch not making it into HA, RGB leds can not be controlled in HA anymore, switch reaction time verrrrrry slow, etc....)

**Comment by GazTheGeek** [comment]
> Similar problem here (only one of the many). Switch toggles back (I also have: switch not making it into HA, RGB leds can not be controlled in HA anymore, switch reaction time verrrrrry slow, etc....)

Try cycling the device if that doesn't work try re-pairing it with your app.

**Comment by aceonce** [comment]
Tried re-pairing it w/ app, no luck

**Comment by nfrawley93** [comment]
I have a similar problem. I have tried both cycle and re-pair too no avail.

**Comment by shlomosv1** [comment]
smithbill17,

"This issue needs escalated as it could result in incorrect operation of electrical devices"

 very nice descirbed ,and  most important very risky !!! with some kinds of devices.

**Comment by aceonce** [comment]
This method only works for single function switch, not multi-functions such as Fan/Lamp combo switch.

**Comment by Segran** [comment]
Just saw this on tuya website….

Does Tuya support Home Assistant?
Last Updated on：
2021-09-26 11:46:14
Currently the previously Tuya products that supported Home Assistant will continue to support it. But the newer Tuya Products do not support Home Assistant any more, if you want to let them support Home Assistant you should develop by yourself. For details about integrat Home Assistant, please visit: https://www.home-assistant.io/components/tuya/. <https://www.home-assistant.io/components/tuya/>

Crap - I just bought a new double outdoor socket with tuya switches….

**Comment by smithbill17** [comment]
This issue has been open 8days now. There's plenty details, evidence & information relating to the issue and calls for it to be backed-out & reverted to the previous integration (there was nothing wrong with the previous integration, why are we replacing it!?), but so far, there has not been a single comment from the Tuya developers who created this integration, never mind any updates with regard to a fix!

**Comment by alexlopezcifuentes** [comment]
> I'm also now getting this issue.
> 
> Switches shown in HomeAssistant do not match the physical state of the device. Some appear on, when in fact they are off.
> 
> If I toggle a light switch, the lamp will come on (and remain on) but the toggle switch changes back to off in HomeAssistant. The SmartLife app shows the correct device status. Also, the old 'Local Tuya' integration which I still use on a 2nd HomeAssistant installation, shows the correct device status (the 'Local Tuya' integration uses local device IP addresses & device identifiers).
> 
> I have noticed if I toggle the device on in HomeAssistant, then immediately toggle it off, BEFORE it appears to toggle itself off in HomeAssistant, then the device in fact switches off. So the control actions still seem to work, it's just the HomeAssistant switch toggle display does not match the actual device status.
> 
> This issue needs escalated as it could result in incorrect operation of electrical devices.
> 
> (also want to comment here that the setup of this integration with registering for a Tuya API account etc etc is _horrendous_ - the whole procedure needs _vastly_ simplified because the current process is bordering on unworkable)

This is exactly the behaviour I have been dealing with when using two Switches. I already had the "Device Status Notification" but is not working either.

**Comment by smithbill17** [comment]
There doesn't seem to be any progress happening on this issue.

I am *STILL* consistently getting this "switch back" issue happening on Home Assistant 2021.11.4

**Comment by Segran** [comment]
I’m using Local Tuya and after 2011.1 it’s working perfectly,  have tried the new Tuya integration as well and it also works. Think you need to update the Integration in Hacs…

Skickat från min iPad

**Comment by smithbill17** [comment]
The Tuya integration is not a HACS integration. It's part of Home Assistants main integration library.

And as per the official documentation: "_Tuya officially maintains this integration._" Well they are doing a *seriously* bad job if it!

Give us back the old Tuya integration that didn't require IoT developer platform accounts - at least it actually *worked*!!

**Comment by Segran** [comment]
Tuya stopper maintaining the TUYA V2 integration in September, and V2 never worked properly. You’ll find all the info about the new Tuya integration as well as how to install Local Tuya on this site and on Utube. And both new Tuya integration ARE installed via Hacs. 

RTFM!

Skickat från min iPad

**Comment by smithbill17** [comment]
The Tuya integration I have this 'switch back' issue with, is the one installed from the HomeAssistant Integrations page - which is presumably the one which Tuya support? It's also the integration offered by HomeAssistants 'auto discovery' process.

I previously used LocalTuya, it works well, but everytime you reset & configure the Tuya smart device (perhaps on changing WiFi password) it changes the device key/ID and you have to jump through 'hoops' to redetermine what it should be so you can manually re-add it to configuration.yaml

Where is the "new Tuya" integration in HACS? When I search HACS for Tuya, I only get LocalTuya.  And why would the "new Tuya" integration not be included within HomeAssistants integration library? HACS integrations are unofficial & not entirely supported integrations? So presumably the 'official' Tuya integration in HomeAssistants integration library (ie. this one) is the one we should be using and is supported (badly) by Tuya themselves?

**Comment by alexlopezcifuentes** [comment]
@smithbill17 In my case, with the new Home Assistant version (2021.11.4), this issue seems to be fixed. I am using the Tuya integration from HA nothing from HACS.

**Comment by smithbill17** [comment]
Yes, I too am using Home Assistant 2021.11.4 with the integration installed from the HA library of integrations (nothing from HACS) and I definitely do get this ghostly automatic 'switch back' happening on my configured Tuya SmartPlugs.

The issue is exactly as described in the opening description of this issue - you press the HA switch to control the SmartPlug and it actually operates the SmartPlug & the HA switch is updated. But within 1or2 seconds, the HA switch *appears* to switch back to its previous state (without actually operating the SmartPlug). So if you switch something ON, it goes on, but the HA switch changes back to showing OFF.  The converse is also true, if you switch something OFF, it goes off, but the HA switch then mysteriously flips back to showing ON.

Sometimes, after a minute or two, the HA switches corrects themselves. But sometimes they seem to be 'stuck' in the wrong position and a HA restart is required to restore things correctly.
