### ISSUE TITLE
No devices detected when switched to the official integration

### ISSUE THREAD

**Issue by strasharo** [tuya/tuya-home-assistant#530]
**Describe the bug**
Removed the integration from HACS and unconfigured it and replaced it with the official one. No devices were detected there.

**Expected behavior**
I should be able to use the devices which were present in the HACS version of the integration.

**Screenshots**
![image](https://user-images.githubusercontent.com/3337997/136266969-e5f8cc98-3ad0-48a3-9e98-f8800d4eb645.png)

**Home Assistant Version**
core-2021.10.0

**Device info (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-home-assistant/wiki/How-to-get-the-log)):**
Two mcs door switches.

**Additional context**
Add any other context or logs about the problem here.
In the official version there's no choice to pick which app was used to set the devices, I suspect it might be picking Smart life instead of Tuya.

**Comment by jasonmadigan** [comment]
Seeing the same issue

**Comment by Zettaga** [comment]
I'm also suffering from this issue, none of my dimmer switches are listed.

**Comment by Rayeliint** [comment]
I too have difficulties, have gone from 39 devices down to 33 after upgrading. Also changed all the entities ID

**Comment by djk314** [comment]
Same here but i can't login into Developpers console, it's busy and my log say : 

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/tuya/__init__.py", line 59, in async_setup_entry
    success = await _init_tuya_sdk(hass, entry)
  File "/usr/src/homeassistant/homeassistant/components/tuya/__init__.py", line 71, in _init_tuya_sdk
    auth_type = AuthType(entry.data[CONF_AUTH_TYPE])
KeyError: 'auth_type'

**Comment by Arakon** [comment]
I just found out that just cause the devices are listed on the cloud page does NOT neccessarily mean that the correct region is used for the cloud setup. My devices show under "Central Europe", but Tuya v2 only sees them when I set it to "Western Europe".

**Comment by dannycb1987** [comment]
> > Guys you need to add authorizations in IOT Platform... Only then devices will be seen by HA.
> 
> Of course I have added authorizations in IOT platform, but integration recognizes only one of my two tuya devices - 1ch switch. The second one - 2ch switch - just not found. :( On Tuya IOT platform there are both devices recognized and both shown as "online".

Exactly what I was thinking. Tuya definitely made some changes. Two days ago every scene I created in the Tuya app showed up in HA after a restart. Now zero. Hope they will fix it asap.

**Comment by gabry1609** [comment]
> > Guys you need to add authorizations in IOT Platform... Only then devices will be seen by HA.
> 
> Of course I have added authorizations in IOT platform, but integration recognizes only one of my two tuya devices - 1ch switch. The second one - 2ch switch - just not found. :( On Tuya IOT platform there are both devices recognized and both shown as "online".

Same here. My IOT already had that authorization but I still can't see any of my devices. Hope for a quick fix...

**Comment by tomaszekn** [comment]
Same in my HA. Tuya integration added to Home Assistant but without devices/entities. From the project on iot.tuya.com all devices are visible and active. No errors in log files.

**Comment by andrewdp69** [comment]
Mine is the same - it puts down the Tuya Scenes but not the devices/entities...

**Comment by kintaroju** [comment]
I too have the same similar problem. I have these light switches that was the most recent addition to my Tuya collection and they don't show up in HA using the new Tuya integration.

https://community.home-assistant.io/t/tuya-integration-issue-since-2021-10-new-version/345200

I have 27 devices, light bulbs, switches and dimmer switches. The only 3 that failed to show up in the new integration was my new dimmer light switches. I know for a fact the original integration worked like a charm and showed all 27 devices instead of 24 with the new integration.

I think the new Tuya integration needs a bit more polishing.

**Comment by tomaszekn** [comment]
> Same in my HA. Tuya integration added to Home Assistant but without devices/entities. From the project on iot.tuya.com all devices are visible and active. No errors in log files.

I've just added 4 API's to the project on iot.tuya.com ("Smart Home Devices Management", "Authorization", "General Equipment Management", "Device Log Query") and my integration is working now (with all devices and entities). I don't know which of API's has fixed the problem but I have no time to check it now :-)

**Comment by mkono87** [comment]
> > Same in my HA. Tuya integration added to Home Assistant but without devices/entities. From the project on iot.tuya.com all devices are visible and active. No errors in log files.
> 
> I've just added 4 API's to the project on iot.tuya.com ("Smart Home Devices Management", "Authorization", "General Equipment Management", "Device Log Query") and my integration is working now (with all devices and entities). I don't know which of added API's has fixed the problem but I have no time to check it now :-) If somebody recognizes the proper one - please report.

The only one I didnt have was Device Log Query but did fix the issue. Do you have any dimmer switches?

**Comment by Zettaga** [comment]
> > > Same in my HA. Tuya integration added to Home Assistant but without devices/entities. From the project on iot.tuya.com all devices are visible and active. No errors in log files.
> > 
> > 
> > I've just added 4 API's to the project on iot.tuya.com ("Smart Home Devices Management", "Authorization", "General Equipment Management", "Device Log Query") and my integration is working now (with all devices and entities). I don't know which of added API's has fixed the problem but I have no time to check it now :-) If somebody recognizes the proper one - please report.
> 
> The only one I didnt have was Device Log Query but did fix the issue. Do you have any dimmer switches?

My only tuya devices are dimmer switches, and this API trick did not work for me.

**Comment by balronu** [comment]
I have created a new project. I've been seeing my devices ever since. I can also switch it on, but Tuya does not reply that the device is switched on. With that I can no longer turn it off. Are all sockets.

**Comment by musicatwrk** [comment]
Seeing this issue as well, 4/5 devices imported, but the newest one in tuya is not imported.

**Comment by strasharo** [comment]
So according to @zlinoliver the sensor platform is not supported in Tuya integration(core-2021.10.0) yet
https://github.com/home-assistant/core/issues/57251#issuecomment-939391002

Guess we'll have to stick with core-2021.9.7 for now.

**Comment by tomaszekn** [comment]
> > > Same in my HA. Tuya integration added to Home Assistant but without devices/entities. From the project on iot.tuya.com all devices are visible and active. No errors in log files.
> > 
> > 
> > I've just added 4 API's to the project on iot.tuya.com ("Smart Home Devices Management", "Authorization", "General Equipment Management", "Device Log Query") and my integration is working now (with all devices and entities). I don't know which of added API's has fixed the problem but I have no time to check it now :-) If somebody recognizes the proper one - please report.
> 
> The only one I didnt have was Device Log Query but did fix the issue. Do you have any dimmer switches?

No, I don't.

**Comment by kintaroju** [comment]
Just for the sake of things, I've submitted a ticket with the Tuya IoT site and see if they can shed any light on our issue

**Comment by Docas09** [comment]
With TUYA v2 I had all the door sensors and motion sensors, with this official integration everything disappeared, only the switches remain.
There are only 32 sensors...
All devices are there in the IoT, but they don't pass the sensors to the Home Assistant
It's too early to install, I had to go back to TUYA v2

**Comment by kintaroju** [comment]
Hi All,

Surprisingly Tuya support replied to me with an answer about the integration, below is the link for supported devices on the current integration:

https://github.com/tuya/tuya-home-assistant/wiki/Supported-Device-Category?_source=f5f782752be3c4a9157ec47514d6091b

I am now waiting to see if they plan to add more devices in the future.

**Comment by Aligatorru** [comment]
Hi there! I live in Moscow, my region in Tuya IoT Platform - Central Europe. I have 28 Tuya devices, all of them showing in IoT Tuya.  after update skill in HA I see only 12 devices. Half of my lights switches not supported.. it’s bad(

**Comment by kintaroju** [comment]
> Hi there! I live in Moscow, my region in Tuya IoT Platform - Central Europe. I have 28 Tuya devices, all of them showing in IoT Tuya. after update skill in HA I see only 12 devices. Half of my lights switches not supported.. it’s bad(

hey you have to wait for the 2021.11 update which should be releasing soon by the look of things

**Comment by OverByThere** [comment]
2021.11 has fixed this for me (just updated docker).

**Comment by kintaroju** [comment]
> 2021.11 has fixed this for me (just updated docker).

ditto, they just removed it from beta, and updated to the latest version, it shows up in HA, hooray!. Thanks frenck for updating the code and the other developers!

**Comment by strasharo** [comment]
My mcs sensors showed up after updating to core-2021.11.0 . Thanks a lot!

**Comment by ramoncio** [comment]
Sorry to bump this old thread, but it is still not working for me. I add the Tuya integration and account data, but no devices get detected, I have tried choosing different countries near Spain.
localtuya works fine with many devices, but it lacks camera support.
Here is a debug from tuya-iot component:

2022-09-12 10:50:30.826 INFO (MainThread) [homeassistant.setup] Setting up tuya
2022-09-12 10:50:30.826 INFO (MainThread) [homeassistant.setup] Setup of domain tuya took 0.0 seconds
2022-09-12 10:50:30.853 DEBUG (SyncWorker_9) [tuya_iot] Request: method = POST,                 url = https://openapi.tuyaeu.com/v1.0/iot-03/users/login,                params = None,                body = {'username': 'MYEMAIL@MYDOMAIN.COM', 'password': '***'},                t = 1662972630853
2022-09-12 10:50:31.656 DEBUG (SyncWorker_9) [tuya_iot] Response: {
2022-09-12 10:50:31.754 DEBUG (MainThread) [tuya_iot] start
2022-09-12 10:50:31.760 DEBUG (Thread-3) [tuya_iot] Request: method = POST,                 url = https://openapi.tuyaeu.com/v1.0/iot-03/open-hub/access-config,                params = None,                body = {'uid': '***', 'link_id': '***', 'link_type': 'mqtt', 'topics': 'device', 'msg_encrypted_version': '2.0'},                t = 1662972631760
2022-09-12 10:50:31.765 DEBUG (SyncWorker_0) [tuya_iot] Request: method = GET,                 url = https://openapi.tuyaeu.com/v1.0/iot-02/assets/-1/sub-assets,                params = {'asset_id': '-1', 'last_row_key': '', 'page_size': 100},                body = None,                t = 1662972631765
2022-09-12 10:50:31.908 DEBUG (SyncWorker_0) [tuya_iot] Response: {
2022-09-12 10:50:31.972 DEBUG (SyncWorker_0) [tuya_iot] Request: method = GET,                 url = https://openapi.tuyaeu.com/v1.0/iot-02/assets/1522414273347845/devices,                params = {'last_row_key': '', 'page_size': 100},                body = None,                t = 1662972631972
2022-09-12 10:50:32.066 DEBUG (Thread-3) [tuya_iot] Response: {
    "url": "ssl://m1.tuyaeu.com:8883",
2022-09-12 10:50:32.067 DEBUG (Thread-3) [tuya_iot] connecting ssl://m1.tuyaeu.com:8883
2022-09-12 10:50:32.135 DEBUG (SyncWorker_0) [tuya_iot] Response: {
2022-09-12 10:50:32.148 DEBUG (SyncWorker_0) [tuya_iot] Request: method = GET,                 url = https://openapi.tuyaeu.com/v1.0/iot-02/assets/1522414273347845/sub-assets,                params = {'asset_id': '1522414273347845', 'last_row_key': '', 'page_size': 100},                body = None,                t = 1662972632148
2022-09-12 10:50:32.290 DEBUG (Thread-3) [tuya_iot] _on_log: Sending CONNECT (u1, p1, wr0, wq0, wf0, c1, k60) client_id=b'cloud_8e37500d86d77440cb5ae34f832b2aff'
2022-09-12 10:50:32.319 DEBUG (SyncWorker_0) [tuya_iot] Response: {
2022-09-12 10:50:32.336 DEBUG (Thread-4 (_thread_main)) [tuya_iot] _on_log: Received CONNACK (0, 0)
2022-09-12 10:50:32.359 DEBUG (Thread-4 (_thread_main)) [tuya_iot] connect flags->{'session present': 0}, rc->0
2022-09-12 10:50:32.382 DEBUG (Thread-4 (_thread_main)) [tuya_iot] _on_log: Sending SUBSCRIBE (d0, m1) [(b'cloud/token/in/67231c8fa59e77daa8d38af330e56ca9', 0)]
2022-09-12 10:50:32.438 INFO (MainThread) [homeassistant.components.alarm_control_panel] Setting up alarm_control_panel.tuya
2022-09-12 10:50:32.444 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up binary_sensor.tuya
2022-09-12 10:50:32.445 DEBUG (Thread-4 (_thread_main)) [tuya_iot] _on_log: Received SUBACK
2022-09-12 10:50:32.446 DEBUG (Thread-4 (_thread_main)) [tuya_iot] _on_subscribe: 1
2022-09-12 10:50:32.447 INFO (MainThread) [homeassistant.components.button] Setting up button.tuya
2022-09-12 10:50:32.451 INFO (MainThread) [homeassistant.components.camera] Setting up camera.tuya
2022-09-12 10:50:32.457 INFO (MainThread) [homeassistant.components.climate] Setting up climate.tuya
2022-09-12 10:50:32.463 INFO (MainThread) [homeassistant.components.cover] Setting up cover.tuya
2022-09-12 10:50:32.466 INFO (MainThread) [homeassistant.components.fan] Setting up fan.tuya
2022-09-12 10:50:32.472 INFO (MainThread) [homeassistant.components.humidifier] Setting up humidifier.tuya
2022-09-12 10:50:32.481 INFO (MainThread) [homeassistant.components.light] Setting up light.tuya
2022-09-12 10:50:32.484 INFO (MainThread) [homeassistant.components.number] Setting up number.tuya
2022-09-12 10:50:32.487 INFO (MainThread) [homeassistant.components.scene] Setting up scene.tuya
2022-09-12 10:50:32.491 INFO (MainThread) [homeassistant.components.select] Setting up select.tuya
2022-09-12 10:50:32.498 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.tuya
2022-09-12 10:50:32.502 INFO (MainThread) [homeassistant.components.siren] Setting up siren.tuya
2022-09-12 10:50:32.506 INFO (MainThread) [homeassistant.components.switch] Setting up switch.tuya
2022-09-12 10:50:32.509 INFO (MainThread) [homeassistant.components.vacuum] Setting up vacuum.tuya
2022-09-12 10:51:32.967 DEBUG (Thread-4 (_thread_main)) [tuya_iot] _on_log: Sending PINGREQ
2022-09-12 10:51:33.009 DEBUG (Thread-4 (_thread_main)) [tuya_iot] _on_log: Received PINGRESP


My diagnostics:

{
  "home_assistant": {
    "installation_type": "Home Assistant Supervised",
    "version": "2022.9.2",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.5",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/Madrid",
    "os_name": "Linux",
    "os_version": "4.9.269",
    "supervisor": "2022.08.6",
    "host_os": "CoreELEC (official): 19.5-Matrix_rc2",
    "docker_version": "19.03.15",
    "chassis": "",
    "run_as_root": true
  },
  "custom_components": {
    "meross_lan": {
      "version": "2.6.1",
      "requirements": []
    },
    "localtuya": {
      "version": "4.1.0",
      "requirements": []
    },
    "hacs": {
      "version": "1.27.2",
      "requirements": [
        "aiogithubapi>=22.2.4"
      ]
    }
  },
  "integration_manifest": {
    "domain": "tuya",
    "name": "Tuya",
    "documentation": "https://www.home-assistant.io/integrations/tuya",
    "requirements": [
      "tuya-iot-py-sdk==0.6.6"
    ],
    "dependencies": [
      "ffmpeg"
    ],
    "codeowners": [
      "@Tuya",
      "@zlinoliver",
      "@frenck"
    ],
    "config_flow": true,
    "iot_class": "cloud_push",
    "dhcp": [
      {
        "macaddress": "105A17*"
      },
      {
        "macaddress": "10D561*"
      },
      {
        "macaddress": "1869D8*"
      },
      {
        "macaddress": "381F8D*"
      },
      {
        "macaddress": "508A06*"
      },
      {
        "macaddress": "68572D*"
      },
      {
        "macaddress": "708976*"
      },
      {
        "macaddress": "7CF666*"
      },
      {
        "macaddress": "84E342*"
      },
      {
        "macaddress": "D4A651*"
      },
      {
        "macaddress": "D81F12*"
      }
    ],
    "loggers": [
      "tuya_iot"
    ],
    "is_built_in": true
  },
  "data": {
    "endpoint": "https://openapi.tuyaeu.com",
    "auth_type": 1,
    "country_code": "34",
    "app_type": "",
    "mqtt_connected": true,
    "disabled_by": null,
    "disabled_polling": false,
    "devices": []
  }
}

Is this component supposed to be working properly with latest homeassistant? Does it work with Tuya cameras?
Thank you!
