### ISSUE TITLE
WiFi Light Controller not working in HA (works on every other platform)

### ISSUE THREAD

**Issue by stats2909** [tuya/tuya-home-assistant#539]
**Describe the bug**
The device appears in the Tuya App and IoT platform as expected. The Tuya skill and device works seamlessly. However, the device is brought into HA vi the integration but does not function.   

Turning the light (controller) on results in the switch remaining in the 'On' position for a second then reverting to 'Off'.  The light shows no activity.

**Expected behavior**
Light to come on and off as commanded by the switch created via the HA integration.

**Screenshots**
Device info
![image](https://user-images.githubusercontent.com/16725444/136585018-2a958ccd-69ae-4a49-807a-71183c106a09.png)

Top two rows results of HA requests to turn on... lower two are requests via Tuya App
![image](https://user-images.githubusercontent.com/16725444/136585626-9965e1e1-1c1f-421b-b7be-cf2c231b24d4.png)

Device in HA
![image](https://user-images.githubusercontent.com/16725444/136588129-e56b60dd-9913-4bea-9e55-8037918098fb.png)

**Home Assistant Version**
core-2021.10.1
supervisor-2021.09.6

**HA Error Logs**
No errors logged in HA

**Additional context**
All 6 API Authorisations completed as directed in the installation instructions.

**Comment by stats2909** [comment]
Reboot of HA has no generated the following:

![image](https://user-images.githubusercontent.com/16725444/136990218-72a410bf-4cde-404b-844a-563498ae30f0.png)


Logger: homeassistant.config_entries
Source: components/tuya/__init__.py:86
First occurred: 09:57:47 (1 occurrences)
Last logged: 09:57:47

Error setting up entry matthew.bonsall@gmail.com for tuya
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f97cc3190>: Failed to establish a new connection: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='openapi.tuyaeu.com', port=443): Max retries exceeded with url: /v1.0/iot-01/associated-users/actions/authorized-login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f97cc3190>: Failed to establish a new connection: [Errno -3] Try again'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/tuya/__init__.py", line 59, in async_setup_entry
    success = await _init_tuya_sdk(hass, entry)
  File "/usr/src/homeassistant/homeassistant/components/tuya/__init__.py", line 86, in _init_tuya_sdk
    response = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/tuya_iot/openapi.py", line 208, in connect
    response = self.post(
  File "/usr/local/lib/python3.9/site-packages/tuya_iot/openapi.py", line 324, in post
    return self.__request("POST", path, None, body)
  File "/usr/local/lib/python3.9/site-packages/tuya_iot/openapi.py", line 267, in __request
    response = self.session.request(
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='openapi.tuyaeu.com', port=443): Max retries exceeded with url: /v1.0/iot-01/associated-users/actions/authorized-login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f97cc3190>: Failed to establish a new connection: [Errno -3] Try again'))
