### ISSUE TITLE
Cover entity unavailable

### ISSUE THREAD

**Issue by emilinsweden** [tuya/tuya-home-assistant#54]
Zemismart cover motor with Wi-Fi is not working.

2021-07-03 22:59:17 ERROR (MainThread) [homeassistant.components.cover] Error adding entities for domain cover with platform tuya_v2
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 383, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 588, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 666, in add_to_platform_finish
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 419, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 453, in _async_write_ha_state
state = self._stringify_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 425, in _stringify_state
state = self.state
File "/usr/src/homeassistant/homeassistant/components/cover/__init__.py", line 208, in state
closed = self.is_closed
File "/usr/src/homeassistant/homeassistant/components/cover/__init__.py", line 265, in is_closed
return self._attr_is_closed
AttributeError: 'TuyaHaCover' object has no attribute '_attr_is_closed'

**Comment by kebel87** [comment]
same error for me, using Quoya (Zemismart) cover.

**Comment by edufabra** [comment]
Here is my error log when I've added the plugin and detected my YH002 device:

```
Error adding entities for domain cover with platform tuya_v2
Error while setting up tuya_v2 platform for cover
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 383, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 588, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 615, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 368, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 402, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 374, in _stringify_state
    state = self.state
  File "/usr/src/homeassistant/homeassistant/components/cover/__init__.py", line 192, in state
    closed = self.is_closed
  File "/usr/src/homeassistant/homeassistant/components/cover/__init__.py", line 244, in is_closed
    raise NotImplementedError()
NotImplementedError
```

**Comment by rickroetenberg** [comment]
Here is my error log (Device:RD Intelligent BlindMotor)

Logger: homeassistant.components.cover
Source: components/cover/__init__.py:244
Integration: Cover (documentation, issues)
First occurred: 9:12:54 AM (8 occurrences)
Last logged: 9:16:04 AM

Error adding entities for domain cover with platform tuya_v2
Error while setting up tuya_v2 platform for cover
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 383, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 588, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 615, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 368, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 402, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 374, in _stringify_state
    state = self.state
  File "/usr/src/homeassistant/homeassistant/components/cover/__init__.py", line 192, in state
    closed = self.is_closed
  File "/usr/src/homeassistant/homeassistant/components/cover/__init__.py", line 244, in is_closed
    raise NotImplementedError()
NotImplementedError

**Comment by tsutsuku** [comment]
@rickroetenberg @edufabra  Get it. We will fix it soon.
