### ISSUE TITLE
Fan shows as unavailable as of v1.6 (KeyError: 'mode')

### ISSUE THREAD

**Issue by gvssr** [tuya/tuya-home-assistant#587]
**Describe the bug**
While the fan was working partially in v1.5, as of v1.6 my fan entity shows up as unavailable. Shows the following error:

```
Logger: homeassistant.components.fan
Source: custom_components/tuya_v2/fan.py:211
Integration: Fan (documentation, issues)
First occurred: October 15, 2021, 18:37:04 (2 occurrences)
Last logged: October 15, 2021, 18:37:04

Error adding entities for domain fan with platform tuya_v2
Error while setting up tuya_v2 platform for fan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 587, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 682, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 456, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 491, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 620, in state_attributes
    data[ATTR_SPEED] = self.speed
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 462, in speed
    preset_mode = self.preset_mode
  File "/config/custom_components/tuya_v2/fan.py", line 211, in preset_mode
    return self.tuya_device.status[DPCODE_MODE]
KeyError: 'mode'
```

**Expected behavior**
A working fan entity with at least on/off and speed controls. The way it worked in v.15 can be seen here: #340 

**Screenshots**
![image](https://user-images.githubusercontent.com/61377476/137588448-3892cd5a-b0cc-4c14-a547-d014cc87514f.png)

**Home Assistant Version**
2021.10.4

**Device info (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-home-assistant/wiki/How-to-get-the-log)):**
like this:
```
{
"active_time": 1628696958,
"biz_type": 0,
"category": "fs",
"create_time": 1628696958,
"icon": "smart/icon/001441070657466AAETE/a3de89a299843127e4d716cd35e5fd4e.png",
"id": "ebbc7c0bf2c73d0e33d7xp",
"ip": "***",
"lat": "***",
"local_key": "***",
"lon": "***",
"model": "DXCF14/15",
"name": "Whisper Flex Ultimate",
"online": true,
"owner_id": "34993017",
"product_id": "cjsa4k7tqbpuyq3l",
"product_name": "",
"status": [
{
"code": "switch",
"value": false
},
{
"code": "fan_speed_percent",
"value": 1
},
{
"code": "temp",
"value": 17
}
],
"sub": false,
"time_zone": "+02:00",
"uid": "***",
"update_time": 1634031730,
"uuid": "00588b1fb206c170"
}
```

**Device specifications (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-home-assistant/wiki/How-to-get-the-log)):**
Same device's id, like this:
```
2021-10-16 15:02:03 DEBUG (SyncWorker_2) [tuya iot] Request: method = GET, url = https://openapi.tuyaus.com/v1.0/devices/ebbc7c0bf2c73d0e33d7xp/specifications, params = None, body = None, t = 1634389323950
2021-10-16 15:02:03 DEBUG (Thread-4) [tuya iot] _on_log: Received SUBACK
2021-10-16 15:02:03 DEBUG (Thread-4) [tuya iot] _on_subscribe: 1
2021-10-16 15:02:04 DEBUG (SyncWorker_2) [tuya iot] Response: {
"result": {
"category": "fs",
"functions": [
{
"code": "switch",
"type": "Boolean",
"values": "{}"
},
{
"code": "fan_speed_percent",
"type": "Integer",
"values": "{\"min\":\"1\",\"max\":\"30\",\"scale\":\"0\",\"step\":\"1\"}"
},
{
"code": "temp",
"type": "Integer",
"values": "{\"unit\":\"℃\",\"min\":\"17\",\"max\":\"28\",\"scale\":\"0\",\"step\":\"1\"}"
}
],
"status": [
{
"code": "switch",
"type": "Boolean",
"values": "{}"
},
{
"code": "fan_speed_percent",
"type": "Integer",
"values": "{\"min\":\"1\",\"max\":\"30\",\"scale\":\"0\",\"step\":\"1\"}"
},
{
"code": "temp",
"type": "Integer",
"values": "{\"unit\":\"℃\",\"min\":\"17\",\"max\":\"28\",\"scale\":\"0\",\"step\":\"1\"}"
}
]
},
"success": true,
"t": 1634389324061
}
```

**Comment by gvssr** [comment]
Closing this at this repo is no longer maintained and it's been fixed in HA core
