### ISSUE TITLE
Error adding fan to home assisatant

### ISSUE THREAD

**Issue by Kranzy** [tuya/tuya-home-assistant#68]
I get the following error when adding a Skyfan fan to home assistant. The device shows up but no control for either on/off or speed.

```
2021-07-04 12:26:21 ERROR (Thread-18) [tuya iot] error while get mqtt config
2021-07-04 12:26:21 ERROR (Thread-18) [root] Uncaught thread exception
Traceback (most recent call last):
File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
self.run()
File "/usr/local/lib/python3.8/site-packages/tuya_iot/openmq.py", line 173, in run
time.sleep(self.mq_config.expireTime - 60)
AttributeError: 'TuyaOpenMQ' object has no attribute 'mq_config'

Error adding entities for domain fan with platform tuya_v2
Error while setting up tuya_v2 platform for fan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 383, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 499, in _async_add_entity
    capabilities=entity.capability_attributes,
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 506, in capability_attributes
    attrs[ATTR_SPEED_LIST] = self.speed_list
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 488, in speed_list
    speeds += self.preset_modes
  File "/config/custom_components/tuya_v2/fan.py", line 139, in preset_modes
    data = json.loads(self.tuya_device.function.get(DPCODE_MODE, {}).values).get(
  File "/usr/local/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not builtin_function_or_method
```

**Comment by tsutsuku** [comment]
@Kranzy Can you provide more logs?

**Comment by Kranzy** [comment]
Yeah I am happy to. Which logs do you need? Just the Home Assistant logs?

I did a restart and these are the details from the HA log relating to Tuya v2:

```
2021-07-06 07:31:02 ERROR (Thread-18) [tuya iot] error while get mqtt config
2021-07-06 07:31:02 ERROR (Thread-18) [root] Uncaught thread exception
Traceback (most recent call last):
File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
self.run()
File "/usr/local/lib/python3.8/site-packages/tuya_iot/openmq.py", line 173, in run
time.sleep(self.mq_config.expireTime - 60)
AttributeError: 'TuyaOpenMQ' object has no attribute 'mq_config'

2021-07-06 07:31:03 ERROR (MainThread) [homeassistant.components.fan] Error adding entities for domain fan with platform tuya
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 383, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 588, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 614, in add_to_platform_finish
await self.async_added_to_hass()
File "/usr/src/homeassistant/homeassistant/components/tuya/fan.py", line 75, in async_added_to_hass
self.speeds.extend(self._tuya.speed_list())
File "/usr/local/lib/python3.8/site-packages/tuyaha/devices/fan.py", line 12, in speed_list
for i in range(speed_level):
TypeError: 'NoneType' object cannot be interpreted as an integer
2021-07-06 07:31:03 ERROR (MainThread) [homeassistant.components.fan] Error while setting up tuya platform for fan
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 258, in _async_setup_platform
await asyncio.gather(*pending)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 383, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 588, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 614, in add_to_platform_finish
await self.async_added_to_hass()
File "/usr/src/homeassistant/homeassistant/components/tuya/fan.py", line 75, in async_added_to_hass
self.speeds.extend(self._tuya.speed_list())
File "/usr/local/lib/python3.8/site-packages/tuyaha/devices/fan.py", line 12, in speed_list
for i in range(speed_level):
TypeError: 'NoneType' object cannot be interpreted as an integer
2021-07-06 07:31:03 ERROR (MainThread) [homeassistant.components.fan] Error adding entities for domain fan with platform tuya_v2
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 383, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 499, in _async_add_entity
capabilities=entity.capability_attributes,
File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 506, in capability_attributes
attrs[ATTR_SPEED_LIST] = self.speed_list
File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 488, in speed_list
speeds += self.preset_modes
File "/config/custom_components/tuya_v2/fan.py", line 139, in preset_modes
data = json.loads(self.tuya_device.function.get(DPCODE_MODE, {}).values).get(
File "/usr/local/lib/python3.8/json/__init__.py", line 341, in loads
raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not builtin_function_or_method
2021-07-06 07:31:03 ERROR (MainThread) [homeassistant.components.fan] Error while setting up tuya_v2 platform for fan
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 258, in _async_setup_platform
await asyncio.gather(*pending)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 383, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 499, in _async_add_entity
capabilities=entity.capability_attributes,
File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 506, in capability_attributes
attrs[ATTR_SPEED_LIST] = self.speed_list
File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 488, in speed_list
speeds += self.preset_modes
File "/config/custom_components/tuya_v2/fan.py", line 139, in preset_modes
data = json.loads(self.tuya_device.function.get(DPCODE_MODE, {}).values).get(
File "/usr/local/lib/python3.8/json/__init__.py", line 341, in loads
raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not builtin_function_or_method
```

**Comment by tsutsuku** [comment]
@Kranzy Can you provide the device specification and info from the log like issues template?

**Comment by Kranzy** [comment]
I am not sure what you mean by info from the log like issues template?

The fan I am trying to control is a skyfan with fan only, no light.
https://ventair.com.au/product/sky1203wh

Add in module to control via app
https://ventair.com.au/product/skyappcm

**Comment by tsutsuku** [comment]
like this:

**Device info (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-home-assistant/wiki/How-to-get-the-log)):**
like this:
{
      "active_time": 1623229189,
      "biz_type": 18,
      "category": "cz",
      "create_time": 1560491945,
      "icon": "smart/product_icon/cz.png",
      "id": "aaaaaaaaaaa",
      "ip": "xxxxxxxxxxxxxxxx",
      "lat": "30.30286857361191",
      "local_key": "xxxxxxxxxxxxx",
      "lon": "120.0639743842656",
      "model": "",
      "name": "Living Room Socket",
      "online": false,
      "owner_id": "34794909",
      "product_id": "yfemiswbgjhddhcf",
      "product_name": "Switch Product",
      "status": [
        {
          "code": "switch",
          "value": false
        },
        {
          "code": "countdown_1",
          "value": 0
        },
        {
          "code": "cur_current",
          "value": 0
        },
        {
          "code": "cur_power",
          "value": 0
        },
        {
          "code": "cur_voltage",
          "value": 2343
        }
      ],
      "sub": false,
      "time_zone": "+08:00",
      "uid": "xxxxxxxxxxxxxxxxxxx",
      "update_time": 1625101929,
      "uuid": "xxxxxxxxxxxxxxxxxx"
    }

**Device specifications (please complete the following information, which can be found in [log](https://github.com/tuya/tuya-home-assistant/wiki/How-to-get-the-log)):**
Same device's id, like this:
[2021-07-01 10:18:01,351] [tuya-openapi] Request: method = GET, url = https://openapi.tuyacn.com/v1.0/devices/aaaaaaaaaaa/specifications, params = None, body = None, headers = {'client_id': 'xxxxxxxxxxxx', 'sign': 'xxxxxxxxxxxx', 'sign_method': 'HMAC-SHA256', 'access_token': '213e2d4af5e8d217abc0b104462a9f72', 't': '1625105881351', 'lang': 'en'}
2021-07-01 10:18:01 DEBUG (SyncWorker_1) [tuya iot] Response: {
  "result": {
    "category": "cz",
    "functions": [
      {
        "code": "countdown_1",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "switch",
        "type": "Boolean",
        "values": "{}"
      }
    ],
    "status": [
      {
        "code": "cur_voltage",
        "type": "Integer",
        "values": "{\"unit\":\"V\",\"min\":0,\"max\":2500,\"scale\":0,\"step\":1}"
      },
      {
        "code": "cur_current",
        "type": "Integer",
        "values": "{\"unit\":\"mA\",\"min\":0,\"max\":30000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "switch",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "cur_power",
        "type": "Integer",
        "values": "{\"unit\":\"W\",\"min\":0,\"max\":50000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_1",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1625105881348
}

**Additional context**
Add any other context or logs about the problem here.

**Comment by Kranzy** [comment]
Thanks for that, please see below. I enabled 'Device status notification' api and that removed some of the errors in my log. Still no entity shows up for the fan. Logs below as requested. I have removed anything I thought may be personal information.

```
2021-07-07 02:53:20 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration tuya_v2 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-07-07 02:53:22 INFO (MainThread) [custom_components.tuya_v2] Tuya async setup conf None
2021-07-07 02:53:22 INFO (MainThread) [custom_components.tuya_v2] tuya.__init__.async_setup_entry-->{'password': '****', 'endpoint': 'https://openapi.tuyaeu.com', 'access_id': '****', 'access_secret': '****', 'tuya_app_type': 'tuyaSmart', 'country_code': '61', 'username': '****@****.com', 'tuya_project_type': 0}
2021-07-07 02:53:22 DEBUG (SyncWorker_16) [tuya iot] Request: method = POST, url = https://openapi.tuyaeu.com/v1.0/iot-01/associated-users/actions/authorized-login, params = None, body = {'username': '****@****.com', 'password': '****', 'country_code': '61', 'schema': 'tuyaSmart'}, headers = {'client_id': '****', 'sign': '****', 'sign_method': 'HMAC-SHA256', 'access_token': '', 't': '****', 'lang': 'en', 'dev_lang': 'python', 'dev_version': '0.3.0', 'dev_channel': 'hass'}
2021-07-07 02:53:23 DEBUG (SyncWorker_16) [tuya iot] Response: {
"result": {
"access_token": "****",
"expire_time": 7200,
"refresh_token": "****",
"uid": "****"
},
"success": true,
"t": ****
}
2021-07-07 02:53:23 DEBUG (MainThread) [tuya iot] start
2021-07-07 02:53:23 DEBUG (Thread-6) [tuya iot] Request: method = POST, url = https://openapi.tuyaeu.com/v1.0/iot-03/open-hub/access-config, params = None, body = {'uid': '****', 'link_id': 'tuya-iot-app-sdk-python.7deca14a-dece-11eb-8c00-****', 'link_type': 'mqtt', 'topics': 'device', 'msg_encrypted_version': '1.0'}, headers = {'client_id': '****', 'sign': '****', 'sign_method': 'HMAC-SHA256', 'access_token': '****', 't': '****', 'lang': 'en'}
2021-07-07 02:53:23 DEBUG (SyncWorker_8) [tuya iot] Request: method = GET, url = https://openapi.tuyaeu.com/v1.0/users/eu****/devices, params = None, body = None, headers = {'client_id': '****', 'sign': '****', 'sign_method': 'HMAC-SHA256', 'access_token': '****', 't': '****', 'lang': 'en'}
2021-07-07 02:53:24 DEBUG (Thread-6) [tuya iot] Response: {
"result": {
"client_id": "cloud_b79acb04******",
"expire_time": 7200,
"password": "f606ef6d******",
"sink_topic": {
"device": "cloud/token/out/{device_id}"
},
"source_topic": {
"device": "cloud/token/in/5361c55d****"
},
"url": "ssl://m1.tuyaeu.com:8883",
"username": "cloud_5361c55****"
},
"success": true,
"t": 1625626403926
}
2021-07-07 02:53:24 DEBUG (Thread-6) [tuya iot] connecting ssl://m1.tuyaeu.com:8883
2021-07-07 02:53:24 DEBUG (Thread-6) [tuya iot] _on_log: Sending CONNECT (u1, p1, wr0, wq0, wf0, c1, k60) client_id=b'cloud_b79acb0****'
2021-07-07 02:53:24 DEBUG (SyncWorker_8) [tuya iot] Response: {
"result": [
{
"active_time": 1625192613,
"biz_type": 0,
"category": "fs",
"create_time": 1625192613,
"icon": "smart/icon/bay1584532656526XHLd/4174877b87bb92ca949b71f3c24771c1.png",
"id": "828234****",
"ip": "119.18.39.96",
"lat": "",
"local_key": "9af48a4814****",
"lon": "",
"name": "Skyfan DC",
"online": true,
"owner_id": "831****",
"product_id": "vzj97d3m05yjhchn",
"product_name": "Skyfan DC",
"status": [
{
"code": "switch",
"value": false
},
{
"code": "fan_speed_percent",
"value": 1
}
],
"sub": false,
"time_zone": "+10:00",
"uid": "eu15763011****",
"update_time": 1625383769,
"uuid": "82823423e****"
},
{
"active_time": 1576301472,
"biz_type": 0,
"category": "dj",
"create_time": 1576301472,
"icon": "smart/icon/ay1533773342993pM7Be/3470a4f4776acc57fda12111a46a55a1.jpg",
"id": "82005237****",
"ip": "119.18.39.96",
"lat": "",
"local_key": "5d914398****",
"lon": "",
"model": "I002777",
"name": "Genio RGB Fairy Light",
"online": false,
"owner_id": "831****",
"product_id": "0xh49brrqkompp52",
"product_name": "Genio RGB Fairy Light",
"status": [
{
"code": "switch_led",
"value": true
}
],
"sub": false,
"time_zone": "+10:00",
"uid": "eu15763011****",
"update_time": 1613795266,
"uuid": "820052372****"
}
],
"success": true,
"t": 1625626404829
}
2021-07-07 02:53:24 DEBUG (SyncWorker_8) [tuya iot] Request: method = GET, url = https://openapi.tuyaeu.com/v1.0/devices/82823423****/specifications, params = None, body = None, headers = {'client_id': '****', 'sign': '****', 'sign_method': 'HMAC-SHA256', 'access_token': '****', 't': '****', 'lang': 'en'}
2021-07-07 02:53:25 DEBUG (Thread-7) [tuya iot] _on_log: Received CONNACK (0, 0)
2021-07-07 02:53:25 DEBUG (Thread-7) [tuya iot] connect flags->{'session present': 0}, rc->0
2021-07-07 02:53:25 DEBUG (Thread-7) [tuya iot] _on_log: Sending SUBSCRIBE (d0, m1) [(b'cloud/token/in/5361c55da****', 0)]
2021-07-07 02:53:25 DEBUG (SyncWorker_8) [tuya iot] Response: {
"result": {
"category": "fs",
"functions": [
{
"code": "switch",
"type": "Boolean",
"values": "{}"
},
{
"code": "fan_speed_percent",
"type": "Integer",
"values": "{\"min\":\"1\",\"max\":\"5\",\"scale\":\"0\",\"step\":\"1\"}"
}
],
"status": [
{
"code": "switch",
"type": "Boolean",
"values": "{}"
},
{
"code": "fan_speed_percent",
"type": "Integer",
"values": "{\"min\":\"1\",\"max\":\"5\",\"scale\":\"0\",\"step\":\"1\"}"
}
]
},
"success": true,
"t": 1625626405179
}
2021-07-07 02:53:25 DEBUG (SyncWorker_8) [tuya iot] Request: method = GET, url = https://openapi.tuyaeu.com/v1.0/devices/820052****/specifications, params = None, body = None, headers = {'client_id': '****', 'sign': '****', 'sign_method': 'HMAC-SHA256', 'access_token': '****', 't': '****', 'lang': 'en'}
2021-07-07 02:53:25 DEBUG (Thread-7) [tuya iot] _on_log: Received SUBACK
2021-07-07 02:53:25 DEBUG (Thread-7) [tuya iot] _on_subscribe: 1
2021-07-07 02:53:25 DEBUG (SyncWorker_8) [tuya iot] Response: {
"result": {
"category": "dj",
"functions": [
{
"code": "switch_led",
"type": "Boolean",
"values": "{}"
}
],
"status": [
{
"code": "switch_led",
"type": "Boolean",
"values": "{}"
}
]
},
"success": true,
"t": 1625626405517
}
2021-07-07 02:53:25 INFO (MainThread) [custom_components.tuya_v2] init support type->['switch', 'fan', 'cover', 'climate', 'light', 'sensor', 'binary_sensor', 'humidifier', 'number', 'vacuum']
2021-07-07 02:53:25 INFO (MainThread) [custom_components.tuya_v2] tuya async platform-->switch
2021-07-07 02:53:25 INFO (MainThread) [custom_components.tuya_v2] tuya async platform-->fan
2021-07-07 02:53:25 INFO (MainThread) [custom_components.tuya_v2] tuya async platform-->cover
2021-07-07 02:53:25 INFO (MainThread) [custom_components.tuya_v2] tuya async platform-->climate
2021-07-07 02:53:25 INFO (MainThread) [custom_components.tuya_v2] tuya async platform-->light
2021-07-07 02:53:25 INFO (MainThread) [custom_components.tuya_v2] tuya async platform-->sensor
2021-07-07 02:53:25 INFO (MainThread) [custom_components.tuya_v2] tuya async platform-->binary_sensor
2021-07-07 02:53:25 INFO (MainThread) [custom_components.tuya_v2] tuya async platform-->humidifier
2021-07-07 02:53:25 INFO (MainThread) [custom_components.tuya_v2] tuya async platform-->number
2021-07-07 02:53:25 INFO (MainThread) [custom_components.tuya_v2] tuya async platform-->vacuum
2021-07-07 02:53:25 INFO (MainThread) [custom_components.tuya_v2.switch] switch init
2021-07-07 02:53:25 INFO (MainThread) [custom_components.tuya_v2.switch] switch add-> []
2021-07-07 02:53:25 INFO (MainThread) [custom_components.tuya_v2.fan] fan init
2021-07-07 02:53:25 INFO (MainThread) [custom_components.tuya_v2.fan] fan add-> ['82823423e0****']
2021-07-07 02:53:25 INFO (MainThread) [custom_components.tuya_v2.cover] cover init
2021-07-07 02:53:25 INFO (MainThread) [custom_components.tuya_v2.cover] cover add-> []
2021-07-07 02:53:25 INFO (MainThread) [custom_components.tuya_v2.climate] climate init
2021-07-07 02:53:25 INFO (MainThread) [custom_components.tuya_v2.climate] climate add->[]
2021-07-07 02:53:25 INFO (MainThread) [custom_components.tuya_v2.light] light init
2021-07-07 02:53:25 INFO (MainThread) [custom_components.tuya_v2.light] light add-> ['820052372****']
2021-07-07 02:53:25 INFO (MainThread) [custom_components.tuya_v2.sensor] sensor init
2021-07-07 02:53:25 INFO (MainThread) [custom_components.tuya_v2.sensor] sensor add-> []
2021-07-07 02:53:25 INFO (MainThread) [custom_components.tuya_v2.binary_sensor] binary sensor init
2021-07-07 02:53:25 INFO (MainThread) [custom_components.tuya_v2.binary_sensor] binary sensor add->[]
2021-07-07 02:53:25 INFO (MainThread) [custom_components.tuya_v2.humidifier] humidifier init
2021-07-07 02:53:25 INFO (MainThread) [custom_components.tuya_v2.humidifier] humidifier add-> []
2021-07-07 02:53:25 INFO (MainThread) [custom_components.tuya_v2.number] number init
2021-07-07 02:53:25 INFO (MainThread) [custom_components.tuya_v2.number] number add-> []
2021-07-07 02:53:25 INFO (MainThread) [custom_components.tuya_v2.vacuum] vacuum init
2021-07-07 02:53:25 INFO (MainThread) [custom_components.tuya_v2.vacuum] vacuum add -> []
2021-07-07 02:54:19 INFO (MainThread) [custom_components.tuya_v2] integration unload
2021-07-07 02:54:19 DEBUG (MainThread) [tuya iot] stop
2021-07-07 02:54:19 DEBUG (MainThread) [tuya iot] _on_log: Sending DISCONNECT
2021-07-07 02:54:19 DEBUG (Thread-7) [tuya iot] disconnect
2021-07-07 02:54:19 INFO (MainThread) [custom_components.tuya_v2] tuya.__init__.async_setup_entry-->{'password': '****', 'endpoint': 'https://openapi.tuyaeu.com', 'access_id': '****', 'access_secret': '****', 'tuya_app_type': 'tuyaSmart', 'country_code': '61', 'username': '****@****.com', 'tuya_project_type': 0}
2021-07-07 02:54:19 DEBUG (SyncWorker_9) [tuya iot] Request: method = POST, url = https://openapi.tuyaeu.com/v1.0/iot-01/associated-users/actions/authorized-login, params = None, body = {'username': '****@****.com', 'password': '****', 'country_code': '61', 'schema': 'tuyaSmart'}, headers = {'client_id': '****', 'sign': '****', 'sign_method': 'HMAC-SHA256', 'access_token': '', 't': '****', 'lang': 'en', 'dev_lang': 'python', 'dev_version': '0.3.0', 'dev_channel': 'hass'}
2021-07-07 02:54:20 DEBUG (SyncWorker_9) [tuya iot] Response: {
"result": {
"access_token": "****",
"expire_time": 7200,
"refresh_token": "****",
"uid": "*****"
},
"success": true,
"t": 1625626460474
}
2021-07-07 02:54:20 DEBUG (MainThread) [tuya iot] start
2021-07-07 02:54:20 DEBUG (Thread-107) [tuya iot] Request: method = POST, url = https://openapi.tuyaeu.com/v1.0/iot-03/open-hub/access-config, params = None, body = {'uid': '****', 'link_id': 'tuya-iot-app-sdk-python.7deca14a-dece-11eb-8c00-****', 'link_type': 'mqtt', 'topics': 'device', 'msg_encrypted_version': '1.0'}, headers = {'client_id': '****', 'sign': '****', 'sign_method': 'HMAC-SHA256', 'access_token': '****', 't': '****', 'lang': 'en'}
2021-07-07 02:54:20 DEBUG (SyncWorker_6) [tuya iot] Request: method = GET, url = https://openapi.tuyaeu.com/v1.0/users/eu157****UMIj/devices, params = None, body = None, headers = {'client_id': '****', 'sign': '****', 'sign_method': 'HMAC-SHA256', 'access_token': '****', 't': '****', 'lang': 'en'}
2021-07-07 02:54:20 DEBUG (Thread-107) [tuya iot] Response: {
"result": {
"client_id": "cloud_b79ac****",
"expire_time": 7143,
"password": "f606ef6ddc****",
"sink_topic": {
"device": "cloud/token/out/{device_id}"
},
"source_topic": {
"device": "cloud/token/in/5361c55da0f3d****"
},
"url": "ssl://m1.tuyaeu.com:8883",
"username": "cloud_5361c55da0f3d****"
},
"success": true,
"t": 1625626460818
}
2021-07-07 02:54:20 DEBUG (Thread-107) [tuya iot] connecting ssl://m1.tuyaeu.com:8883
2021-07-07 02:54:21 DEBUG (Thread-107) [tuya iot] _on_log: Sending CONNECT (u1, p1, wr0, wq0, wf0, c1, k60) client_id=b'cloud_b79ac****'
2021-07-07 02:54:21 DEBUG (SyncWorker_6) [tuya iot] Response: {
"result": [
{
"active_time": 1625192613,
"biz_type": 0,
"category": "fs",
"create_time": 1625192613,
"icon": "smart/icon/bay1584532656526XHLd/4174877b87bb92ca949b71f3c24771c1.png",
"id": "8282342****",
"ip": "119.18.39.96",
"lat": "",
"local_key": "9af48a48147****",
"lon": "",
"name": "Skyfan DC",
"online": true,
"owner_id": "831***",
"product_id": "vzj97d3m05yjhchn",
"product_name": "Skyfan DC",
"status": [
{
"code": "switch",
"value": false
},
{
"code": "fan_speed_percent",
"value": 1
}
],
"sub": false,
"time_zone": "+10:00",
"uid": "eu15763011****",
"update_time": 1625383769,
"uuid": "82823423e****"
},
{
"active_time": 1576301472,
"biz_type": 0,
"category": "dj",
"create_time": 1576301472,
"icon": "smart/icon/ay1533773342993pM7Be/3470a4f4776acc57fda12111a46a55a1.jpg",
"id": "82005237****",
"ip": "119.18.39.96",
"lat": "",
"local_key": "5d914398a2****",
"lon": "",
"model": "I002777",
"name": "Genio RGB Fairy Light",
"online": false,
"owner_id": "831****",
"product_id": "0xh49brrqkompp52",
"product_name": "Genio RGB Fairy Light",
"status": [
{
"code": "switch_led",
"value": true
}
],
"sub": false,
"time_zone": "+10:00",
"uid": "eu15763****",
"update_time": 1613795266,
"uuid": "820****"
}
],
"success": true,
"t": 1625626461688
}
2021-07-07 02:54:21 DEBUG (SyncWorker_6) [tuya iot] Request: method = GET, url = https://openapi.tuyaeu.com/v1.0/devices/828234****/specifications, params = None, body = None, headers = {'client_id': '****', 'sign': '****', 'sign_method': 'HMAC-SHA256', 'access_token': '****', 't': '1625626461829', 'lang': 'en'}
2021-07-07 02:54:22 DEBUG (Thread-108) [tuya iot] _on_log: Received CONNACK (0, 0)
2021-07-07 02:54:22 DEBUG (Thread-108) [tuya iot] connect flags->{'session present': 0}, rc->0
2021-07-07 02:54:22 DEBUG (Thread-108) [tuya iot] _on_log: Sending SUBSCRIBE (d0, m1) [(b'cloud/token/in/5361c55d*****', 0)]
2021-07-07 02:54:22 DEBUG (SyncWorker_6) [tuya iot] Response: {
"result": {
"category": "fs",
"functions": [
{
"code": "switch",
"type": "Boolean",
"values": "{}"
},
{
"code": "fan_speed_percent",
"type": "Integer",
"values": "{\"min\":\"1\",\"max\":\"5\",\"scale\":\"0\",\"step\":\"1\"}"
}
],
"status": [
{
"code": "switch",
"type": "Boolean",
"values": "{}"
},
{
"code": "fan_speed_percent",
"type": "Integer",
"values": "{\"min\":\"1\",\"max\":\"5\",\"scale\":\"0\",\"step\":\"1\"}"
}
]
},
"success": true,
"t": 1625626461984
}
2021-07-07 02:54:22 DEBUG (SyncWorker_6) [tuya iot] Request: method = GET, url = https://openapi.tuyaeu.com/v1.0/devices/8200523****/specifications, params = None, body = None, headers = {'client_id': '****', 'sign': '****', 'sign_method': 'HMAC-SHA256', 'access_token': '****', 't': '****', 'lang': 'en'}
2021-07-07 02:54:22 DEBUG (Thread-108) [tuya iot] _on_log: Received SUBACK
2021-07-07 02:54:22 DEBUG (Thread-108) [tuya iot] _on_subscribe: 1
2021-07-07 02:54:22 DEBUG (SyncWorker_6) [tuya iot] Response: {
"result": {
"category": "dj",
"functions": [
{
"code": "switch_led",
"type": "Boolean",
"values": "{}"
}
],
"status": [
{
"code": "switch_led",
"type": "Boolean",
"values": "{}"
}
]
},
"success": true,
"t": 1625626462289
}
2021-07-07 02:54:22 INFO (MainThread) [custom_components.tuya_v2] init support type->['switch', 'fan', 'cover', 'climate', 'light', 'sensor', 'binary_sensor', 'humidifier', 'number', 'vacuum']
2021-07-07 02:54:22 INFO (MainThread) [custom_components.tuya_v2] tuya async platform-->switch
2021-07-07 02:54:22 INFO (MainThread) [custom_components.tuya_v2] tuya async platform-->fan
2021-07-07 02:54:22 INFO (MainThread) [custom_components.tuya_v2] tuya async platform-->cover
2021-07-07 02:54:22 INFO (MainThread) [custom_components.tuya_v2] tuya async platform-->climate
2021-07-07 02:54:22 INFO (MainThread) [custom_components.tuya_v2] tuya async platform-->light
2021-07-07 02:54:22 INFO (MainThread) [custom_components.tuya_v2] tuya async platform-->sensor
2021-07-07 02:54:22 INFO (MainThread) [custom_components.tuya_v2] tuya async platform-->binary_sensor
2021-07-07 02:54:22 INFO (MainThread) [custom_components.tuya_v2] tuya async platform-->humidifier
2021-07-07 02:54:22 INFO (MainThread) [custom_components.tuya_v2] tuya async platform-->number
2021-07-07 02:54:22 INFO (MainThread) [custom_components.tuya_v2] tuya async platform-->vacuum
2021-07-07 02:54:22 INFO (MainThread) [custom_components.tuya_v2.switch] switch init
2021-07-07 02:54:22 INFO (MainThread) [custom_components.tuya_v2.switch] switch add-> []
2021-07-07 02:54:22 INFO (MainThread) [custom_components.tuya_v2.fan] fan init
2021-07-07 02:54:22 INFO (MainThread) [custom_components.tuya_v2.fan] fan add-> ['82823423****']
2021-07-07 02:54:22 INFO (MainThread) [custom_components.tuya_v2.cover] cover init
2021-07-07 02:54:22 INFO (MainThread) [custom_components.tuya_v2.cover] cover add-> []
2021-07-07 02:54:22 INFO (MainThread) [custom_components.tuya_v2.climate] climate init
2021-07-07 02:54:22 INFO (MainThread) [custom_components.tuya_v2.climate] climate add->[]
2021-07-07 02:54:22 INFO (MainThread) [custom_components.tuya_v2.light] light init
2021-07-07 02:54:22 INFO (MainThread) [custom_components.tuya_v2.light] light add-> ['82005237****']
2021-07-07 02:54:22 INFO (MainThread) [custom_components.tuya_v2.sensor] sensor init
2021-07-07 02:54:22 INFO (MainThread) [custom_components.tuya_v2.sensor] sensor add-> []
2021-07-07 02:54:22 INFO (MainThread) [custom_components.tuya_v2.binary_sensor] binary sensor init
2021-07-07 02:54:22 INFO (MainThread) [custom_components.tuya_v2.binary_sensor] binary sensor add->[]
2021-07-07 02:54:22 INFO (MainThread) [custom_components.tuya_v2.humidifier] humidifier init
2021-07-07 02:54:22 INFO (MainThread) [custom_components.tuya_v2.humidifier] humidifier add-> []
2021-07-07 02:54:22 INFO (MainThread) [custom_components.tuya_v2.number] number init
2021-07-07 02:54:22 INFO (MainThread) [custom_components.tuya_v2.number] number add-> []
2021-07-07 02:54:22 INFO (MainThread) [custom_components.tuya_v2.vacuum] vacuum init
2021-07-07 02:54:22 INFO (MainThread) [custom_components.tuya_v2.vacuum] vacuum add -> []
```

**Comment by Kranzy** [comment]
I still get this in the log about the fan

```
Logger: homeassistant.components.fan
Source: custom_components/tuya_v2/fan.py:139
Integration: Fan (documentation, issues)
First occurred: 1:10:42 PM (2 occurrences)
Last logged: 1:10:42 PM

Error adding entities for domain fan with platform tuya_v2
Error while setting up tuya_v2 platform for fan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 383, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 499, in _async_add_entity
    capabilities=entity.capability_attributes,
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 506, in capability_attributes
    attrs[ATTR_SPEED_LIST] = self.speed_list
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 488, in speed_list
    speeds += self.preset_modes
  File "/config/custom_components/tuya_v2/fan.py", line 139, in preset_modes
    data = json.loads(self.tuya_device.function.get(DPCODE_MODE, {}).values).get(
  File "/usr/local/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not builtin_function_or_method
```

**Comment by tsutsuku** [comment]
@Kranzy Get it. I think we can fix it soon.

**Comment by Kranzy** [comment]
Awesome, thanks for your effort. appreciate it
