### ISSUE TITLE
 DDS238-2 cz sw9asyjj8j44frjl no sensors data

### ISSUE THREAD

**Issue by MagicOneIta** [tuya/tuya-home-assistant#714]
### The problem

**Describe the bug**
I have only switch but not sensors or sensor data

**Expected behavior**
Sensors data of device

**Screenshots**
![image](https://user-images.githubusercontent.com/20352749/143408504-7f309017-2025-46ac-acb0-0b366ba63f95.png)

**Home Assistant Version**
2021.11.5

**Device info 
Product sw9asyjj8j44frjl
Product Name kWh meter
Product Category cz
Device Status Online
Activated At 2021-11-23 23:45:46
Data Center Central Europe Data Center
Extension Information 
Sub-Device or Not No

![image](https://user-images.githubusercontent.com/20352749/143446776-581d327b-d31f-44e4-9cb8-082ce5daca77.png)

2021-11-25 09:55:52 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up binary_sensor.tuya
2021-11-25 09:55:52 INFO (MainThread) [homeassistant.components.camera] Setting up camera.tuya
2021-11-25 09:55:52 INFO (MainThread) [homeassistant.components.light] Setting up light.tuya
2021-11-25 09:55:52 INFO (MainThread) [homeassistant.components.number] Setting up number.tuya
2021-11-25 09:55:52 INFO (MainThread) [homeassistant.components.scene] Setting up scene.tuya
2021-11-25 09:55:52 INFO (MainThread) [homeassistant.components.select] Setting up select.tuya
2021-11-25 09:55:52 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.tuya
2021-11-25 09:55:52 INFO (MainThread) [homeassistant.components.switch] Setting up switch.tuya
2021-11-25 09:55:52 INFO (MainThread) [homeassistant.components.vacuum] Setting up vacuum.tuya
2021-11-25 09:55:52 INFO (SyncWorker_0) [homeassistant.loader] Loaded cover from homeassistant.components.cover
2021-11-25 09:55:52 INFO (SyncWorker_5) [homeassistant.loader] Loaded climate from homeassistant.components.climate
2021-11-25 09:55:52 INFO (SyncWorker_6) [homeassistant.loader] Loaded humidifier from homeassistant.components.humidifier
2021-11-25 09:55:52 INFO (SyncWorker_2) [homeassistant.loader] Loaded fan from homeassistant.components.fan
2021-11-25 09:55:52 INFO (SyncWorker_3) [homeassistant.loader] Loaded siren from homeassistant.components.siren
2021-11-25 09:55:52 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up tuya platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/src/homeassistant/homeassistant/components/tuya/sensor.py", line 497, in async_setup_entry
    async_discover_device([*hass_data.device_manager.device_map])
  File "/usr/src/homeassistant/homeassistant/components/tuya/sensor.py", line 490, in async_discover_device
    TuyaSensorEntity(
  File "/usr/src/homeassistant/homeassistant/components/tuya/sensor.py", line 546, in __init__
    self.unit_of_measurement is None
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 264, in unit_of_measurement
    return self.hass.config.units.temperature_unit
AttributeError: 'NoneType' object has no attribute 'config'

### What version of Home Assistant Core has the issue?

2021.11.5

### What type of installation are you running?

Home Assistant Container

### Integration causing the issue

Tuya

**Comment by MagicOneIta** [comment]
![image](https://user-images.githubusercontent.com/20352749/143446776-581d327b-d31f-44e4-9cb8-082ce5daca77.png)

2021-11-25 09:55:52 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up binary_sensor.tuya
2021-11-25 09:55:52 INFO (MainThread) [homeassistant.components.camera] Setting up camera.tuya
2021-11-25 09:55:52 INFO (MainThread) [homeassistant.components.light] Setting up light.tuya
2021-11-25 09:55:52 INFO (MainThread) [homeassistant.components.number] Setting up number.tuya
2021-11-25 09:55:52 INFO (MainThread) [homeassistant.components.scene] Setting up scene.tuya
2021-11-25 09:55:52 INFO (MainThread) [homeassistant.components.select] Setting up select.tuya
2021-11-25 09:55:52 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.tuya
2021-11-25 09:55:52 INFO (MainThread) [homeassistant.components.switch] Setting up switch.tuya
2021-11-25 09:55:52 INFO (MainThread) [homeassistant.components.vacuum] Setting up vacuum.tuya
2021-11-25 09:55:52 INFO (SyncWorker_0) [homeassistant.loader] Loaded cover from homeassistant.components.cover
2021-11-25 09:55:52 INFO (SyncWorker_5) [homeassistant.loader] Loaded climate from homeassistant.components.climate
2021-11-25 09:55:52 INFO (SyncWorker_6) [homeassistant.loader] Loaded humidifier from homeassistant.components.humidifier
2021-11-25 09:55:52 INFO (SyncWorker_2) [homeassistant.loader] Loaded fan from homeassistant.components.fan
2021-11-25 09:55:52 INFO (SyncWorker_3) [homeassistant.loader] Loaded siren from homeassistant.components.siren
2021-11-25 09:55:52 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up tuya platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/src/homeassistant/homeassistant/components/tuya/sensor.py", line 497, in async_setup_entry
    async_discover_device([*hass_data.device_manager.device_map])
  File "/usr/src/homeassistant/homeassistant/components/tuya/sensor.py", line 490, in async_discover_device
    TuyaSensorEntity(
  File "/usr/src/homeassistant/homeassistant/components/tuya/sensor.py", line 546, in __init__
    self.unit_of_measurement is None
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 264, in unit_of_measurement
    return self.hass.config.units.temperature_unit
AttributeError: 'NoneType' object has no attribute 'config'

**Comment by MagicOneIta** [comment]
I open issue on https://github.com/home-assistant/core/issues

**Comment by garylogin** [comment]
same problem i think

core-2021.12.3
1.12.3
supervisor-2021.12.2

2021-12-18 11:19:33 ERROR (Thread-3) [tuya_iot] error while get mqtt config
2021-12-18 11:19:33 ERROR (Thread-3) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/site-packages/tuya_iot/openmq.py", line 156, in run
    time.sleep(self.mq_config.expire_time - 60)
AttributeError: 'NoneType' object has no attribute 'expire_time'
2021-12-18 11:19:34 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up tuya platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/src/homeassistant/homeassistant/components/tuya/sensor.py", line 677, in async_setup_entry
    async_discover_device([*hass_data.device_manager.device_map])
  File "/usr/src/homeassistant/homeassistant/components/tuya/sensor.py", line 670, in async_discover_device
    TuyaSensorEntity(
  File "/usr/src/homeassistant/homeassistant/components/tuya/sensor.py", line 730, in __init__
    self.unit_of_measurement is None
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 354, in unit_of_measurement
    return self.hass.config.units.temperature_unit
AttributeError: 'NoneType' object has no attribute 'config'

**Comment by MagicOneIta** [comment]
Hello,
I solved it by removing another device that was causing conflict, in my case it was a temperature and humidity sensor.
I removed it from the devices in the application and now everything works.
I heve removed this:
Product Name: WIFI XR3
Product Category wsdcg
