### ISSUE TITLE
Tuya devices (dj) not supported

### ISSUE THREAD

**Issue by big23** [tuya/tuya-home-assistant#734]
After add Tuya integration to Home Assistant, lot of devices (lights) are available without entities.

Home Assistant 2012.12.1

**Comment by bkr1969** [comment]
Yes....this is a major issue and I've been trying to get to take notice since 2021.11.1.  So far, no one seems to be listening.  my dj device is pretty important in my automations and I can't understand why it would suddenly be dropped from supported devices.

**Comment by bkr1969** [comment]
``
Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform await asyncio.shield(task) File "/usr/src/homeassistant/homeassistant/components/tuya/light.py", line 316, in async_setup_entry async_discover_device([*hass_data.device_manager.device_map]) File "/usr/src/homeassistant/homeassistant/components/tuya/light.py", line 309, in async_discover_device TuyaLightEntity( File "/usr/src/homeassistant/homeassistant/components/tuya/light.py", line 429, in __init__ device.status_range[self._color_temp_dpcode].values KeyError: <DPCode.TEMP_VALUE: 'temp_value'>
``

**Comment by big23** [comment]
After upgrade HA to 2021.12.7 everything is OK. Please close

**Comment by bkr1969** [comment]
How is this fixed? I’m on 2021.12.7 and device type dj still shows as “unavailable.” Please reopen.

**Comment by frenck** [comment]
@bkr1969 Create a new issue with specifics. Thanks.
Also, you might want to report it to Home Assistant, not here.

**Comment by bkr1969** [comment]
@frenck I have posted this problem on HA and on a couple of threads here.  No one seems to have any answers or feedback as to why this device is no longer working. In the core release notes (I believe it was 2021.12.5 but I could be wrong) it specifically lists this device type as being fixed as far as brightness (with your name on it) but it is still unsupported.  Who maintains this integration?

**Comment by frenck** [comment]
@bkr1969 Maybe you've missed it... but this is the Tuya repository, that originally hosted the Tuya V2 custom integration. This one has been discontinued.

This is not the Home Assistant repository or issue tracker.

**Comment by bkr1969** [comment]
So where is the new one?  I simply opened the documentation for the Tuya integration and submitted an issue.  No one has given me any response in either forum.

**Comment by frenck** [comment]
@bkr1969 https://www.home-assistant.io/help
