### ISSUE TITLE
Tuya Integration Suddenly Started Showing Devices as "Unsupported"

### ISSUE THREAD

**Issue by almighty059** [tuya/tuya-home-assistant#805]
I have almost 30 devices connected to the Tuya Integration and several days ago approximately 80% of them started showing as being "unsupported" in the Device Info and they also lost their Entities. The devices still work fine when operating over the Tuya Cloud or LocalTuya and the problem only seems to exist within the Tuya Integration. I tried reloading, restarting, deleting, reinstalling, etc. and each Device still says "unsupported" and shows no Entities. 

I have included a screenshot from one of the times that I reinstalled the integration and you can see several Devices at once and you can see that several of them show as being "unsupported". 

I have been using some of these devices for over a year and they have always been connected and supported to the Tuya Integration with no issues until now. 

Home Assistant OS
core-2022.5.2

Diagnostics:
[config_entry-tuya-d4208934f80f77f0d662c5bd00bbc592.json.txt](https://github.com/tuya/tuya-home-assistant/files/8667509/config_entry-tuya-d4208934f80f77f0d662c5bd00bbc592.json.txt)

Screenshot:
![167262218-993bb0da-fecc-458b-834c-f315f973a51b](https://user-images.githubusercontent.com/63380298/167789557-da38eee4-3078-4da4-bb3d-13ff0c376014.png)

**Comment by almighty059** [comment]
Just to update this I found the following error.

`2022-05-15 07:37:54 ERROR (MainThread) [homeassistant.components.light] Error while setting up tuya platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/src/homeassistant/homeassistant/components/tuya/light.py", line 382, in async_setup_entry
    async_discover_device([*hass_data.device_manager.device_map])
  File "/usr/src/homeassistant/homeassistant/components/tuya/light.py", line 375, in async_discover_device
    TuyaLightEntity(
  File "/usr/src/homeassistant/homeassistant/components/tuya/light.py", line 450, in __init__
    h_type=IntegerTypeData(dpcode, **function_data["h"]),
KeyError: 'h'
`

**Comment by almighty059** [comment]
Haven't got any help so I'm closing.
