### ISSUE TITLE
Unable to add new integration in HA 2022.11.2

### ISSUE THREAD

**Issue by dreamtheater39** [tuya/tuya-home-assistant#871]
Unable to add a new/fresh integration. Fails with "Unknown error occurred".
  File "/usr/src/homeassistant/homeassistant/components/tuya/config_flow.py", line 72, in _try_login
    response = api.connect(
  File "/usr/local/lib/python3.10/site-packages/tuya_iot/openapi.py", line 222, in connect
    self.token_info = TuyaTokenInfo(response)
  File "/usr/local/lib/python3.10/site-packages/tuya_iot/openapi.py", line 41, in __init__
    token_response.get("t", 0)
TypeError: unsupported operand type(s) for +: 'int' and 'str'

Full Error Logs:
Home Assistant 2022.11.2
Supervisor 2022.10.2
Operating System 9.3
Frontend 20221108.0 - latest

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 82, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 180, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 280, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/usr/src/homeassistant/homeassistant/components/tuya/config_flow.py", line 92, in async_step_user
    response, data = await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/tuya/config_flow.py", line 72, in _try_login
    response = api.connect(
  File "/usr/local/lib/python3.10/site-packages/tuya_iot/openapi.py", line 222, in connect
    self.token_info = TuyaTokenInfo(response)
  File "/usr/local/lib/python3.10/site-packages/tuya_iot/openapi.py", line 41, in __init__
    token_response.get("t", 0)
TypeError: unsupported operand type(s) for +: 'int' and 'str'

**Comment by mirasu** [comment]
Yo he perdido todos los dispositivos . Ya no puedo controlarlos desde home assistant

**Comment by eroji** [comment]
Same issue here
