### ISSUE TITLE
Integration working but no devices

### ISSUE THREAD

**Issue by paul12tree** [tuya/tuya-home-assistant#891]
Has all been working well with three smart switches but nothing showing now. The integration card was still visible. 
Deleted and re-added integration (with suitable reboots) and same result. Permissions look right in Tuya IoT and nothing has been changed afaik to make this happen. Any help appreciated

**Comment by autoexecbat3000** [comment]
Same symptom.  Seeing some errors in the log:

Logger: root
Source: /usr/src/homeassistant/homeassistant/bootstrap.py:386
First occurred: 9:46:05 PM (1 occurrences)
Last logged: 9:46:05 PM

Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/site-packages/tuya_iot/openmq.py", line 161, in run
    time.sleep(self.mq_config.expire_time - 60)
AttributeError: 'NoneType' object has no attribute 'expire_time'


also:

Logger: tuya_iot
Source: /usr/local/lib/python3.10/site-packages/tuya_iot/openmq.py:166
First occurred: 9:46:05 PM (1 occurrences)
Last logged: 9:46:05 PM
error while get mqtt config

**Comment by jjlauer** [comment]
Yeah, same thing happening to me and guess what -- pretty sure your Tuya devices stop working if your "cloud account" subscription expires.  You get a measily 30 day to start, then apparently you need to login to renew it every 6 months.  Nothing like everything breaking every 6 months, eh?

Can't wait for matter devices to arrive so I can ditch these proprietary, pieces of trash.

**Comment by paul12tree** [comment]
Good spot. Thanks Seems I have used up the free trial and now they want real money for the ‘IoT Core Plan’. The option for either $25k or $50k per year to run 3 smart plugs might be pushing it a bit for my budget! What a shame...  From: Joe LauerSent: 09 January 2023 04:04To: tuya/tuya-home-assistantCc: paul12tree; AuthorSubject: Re: [tuya/tuya-home-assistant] Integration working but no devices (Issue #891) Yeah, same thing happening to me and guess what -- pretty sure your Tuya devices stop working if your "cloud account" subscription expires. You get a measily 30 day to start, then apparently you need to login to renew it every 6 months. Nothing like everything breaking every 6 months, eh?Can't wait for matter devices to arrive so I can ditch these proprietary, pieces of trash.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by jjlauer** [comment]
There is in fact still a way to ask for 6 months, but the FAQ on this integration is out of date.  It was impossible to find, so I actually triggered their live support on the tuya site and asked about how to extend it for 6 months.  They gave me a link where it shows the subscriptions, and there's a status called Expired or Expiring with a question mark next to it.  You click the question mark and you get the "extend 6 months" trial questionnaire.  What a pain.

**Comment by autoexecbat3000** [comment]
Crazy. I'm going to give this a go, to try to save future me a headache: https://github.com/make-all/tuya-local

**Comment by paul12tree** [comment]
Me too – although to get the localkey you need, ideally, to have the cloud integration....hmmmm  From: autoexecbat3000Sent: 09 January 2023 16:29To: tuya/tuya-home-assistantCc: paul12tree; AuthorSubject: Re: [tuya/tuya-home-assistant] Integration working but no devices (Issue #891) Crazy. I'm going to give this a go, to try to save future me a headache: https://github.com/make-all/tuya-local—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by jjlauer** [comment]
I'd love to know how tuya-local goes, I gave https://github.com/rospogrigio/localtuya a try last month and it unfortunately didn't work w/ my devices and almost broke my whole home assistant install.  All i had were simple light switches.

I believe you may not even need a subscription to manually use the tuya cloud account to simply fetch local keys of your devices.  It's a pain for sure, but I'm just trying to eek out getting my own tuya devices to function until matter devices get more mainstream.  Would love to see how it goes.
