### ISSUE TITLE
Broken in home assistant 2023.5.3

### ISSUE THREAD

**Issue by zendick** [tuya/tuya-home-assistant#928]
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/tuya_v2/__init__.py:176
Integration: Tuya v2 (documentation)
First occurred: May 15, 2023 at 2:54:02 PM (2 occurrences)
Last logged: 8:06:17 PM

Error setting up entry e@mail.nope for tuya_v2
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/tuya_v2/__init__.py", line 118, in async_setup_entry
    success = await _init_tuya_sdk(hass, entry)
  File "/config/custom_components/tuya_v2/__init__.py", line 176, in _init_tuya_sdk
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**Comment by mice6** [comment]
I too have the same problem. Please help developers

**Comment by Luterin70** [comment]
Same issue:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/tuya_v2/__init__.py", line 118, in async_setup_entry
    success = await _init_tuya_sdk(hass, entry)
  File "/config/custom_components/tuya_v2/__init__.py", line 176, in _init_tuya_sdk
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

Perhaps this will be the push for me to change to my already bought Philips Hue Lamps.

**Comment by philspain72** [comment]
same problem

**Comment by ryansdistrict** [comment]
same issue,,,, 
guys any work around or solution for this, my house is built on scenes and now am stuck not being able to update my home assistant, its been 2 months with huge HA improvements

**Comment by jofotoo** [comment]
Same.  Sure would be nice to have my leak sensors working.
