### ISSUE TITLE
Stuck with configuring 2 bulbs, this is the result of one of them

### ISSUE THREAD

**Issue by ArnolddeBolster** [tuya/tuya-home-assistant#957]
**Device normal info**
- Tuya
- Bulb

Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.localtuya.config_flow
Source: custom_components/localtuya/config_flow.py:595
Integration: LocalTuya integration (documentation, issues)
First occurred: 19:48:03 (19 occurrences)
Last logged: 21:14:26

Unexpected exception: [Errno 113] Connect call failed ('192.168......', 6668)
Traceback (most recent call last):
  File "/config/custom_components/localtuya/config_flow.py", line 595, in async_step_configure_device
    self.dps_strings = await validate_input(self.hass, user_input)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/localtuya/config_flow.py", line 242, in validate_input
    interface = await pytuya.connect(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 1182, in connect
    _, protocol = await loop.create_connection(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1085, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1069, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 973, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 628, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 668, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.......', 6668)

**Comment by ArnolddeBolster** [comment]
solved: i noticed in the tuya app that one device didn't have proper network connection.
so i disconnected it in the tuya app and added it again. 
it became the same ip-adres but a new different deviceid and localid.
after that done i could simply add it in localtuya. the other bulb i managed after few tries to connect also.

for those who try to understand the dp settings, i also struggled with, you can get them from tuya iot>cloud>api explorer>device management>device control>query properties.
that part for me i was missing in tutorial
