### ISSUE TITLE
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'. Did you mean: 'async_unload_platforms'

### ISSUE THREAD

**Issue by KiiDii** [tuya/tuya-home-assistant#990]
I get an error after adding the integration:

> Logger: homeassistant.config_entries
> Source: config_entries.py:584
> First occurred: 21:47:14 (1 occurrences)
> Last logged: 21:47:14
> 
> Error setting up entry kiidii.aniname@gmail.com for tuya_v2
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 584, in async_setup
>     result = await component.async_setup_entry(hass, self)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/tuya_v2/__init__.py", line 118, in async_setup_entry
>     success = await _init_tuya_sdk(hass, entry)
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/tuya_v2/__init__.py", line 176, in _init_tuya_sdk
>     hass.config_entries.async_setup_platforms(entry, PLATFORMS)
>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'. Did you mean: 'async_unload_platforms'?

### Algorithm for my actions:

1. Installed the add-on via HACS using [these instructions](https://developer.tuya.com/en/docs/iot/Home_Assistant_Integration?id=Kamcjcbvk2mu8#subtitle-5-Option%202%3A%20HACS%20installation)
2. Restarted Home Assistant
3. Went to the integration section and found **Tuya v2** there.
4. In the **Cloud Project Type** section I selected: ‘Smart Home PaaS’.
5. In **credentials** section I specified my credentials and country code: ‘ua’. In the field: **Mobile app** I specified ‘Tuya App’.
6. Integration is added, but I see: ‘Failed To Setup’.
7. I looked at the logs and saw the logs I specified at the beginning of the post.

### Versions:

- Home Assistant Core: 2024.5.5
- Home Assistant Supervisor: 2024.05.1
- Home Assistant Operating System: 12.3
- Home Assistant Frontend: 20240501.1
- HACS version: 1.34.0

### Hardware
- Raspberry Pi 4 (rpi4-64)

**Comment by ketiv223** [comment]
такая же проблема, есть решение?

```
`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 586, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_v2/__init__.py", line 118, in async_setup_entry
    success = await _init_tuya_sdk(hass, entry)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_v2/__init__.py", line 176, in _init_tuya_sdk
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'. Did you mean: 'async_unload_platforms'?`
```

**Comment by eecklund** [comment]
Having the same issue.

Logger: homeassistant.config_entries
Source: config_entries.py:640
First occurred: 3:24:41 PM (2 occurrences)
Last logged: 3:24:52 PM

Error setting up entry lgehrig44@gmail.com for tuya_v2
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_v2/__init__.py", line 118, in async_setup_entry
    success = await _init_tuya_sdk(hass, entry)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_v2/__init__.py", line 176, in _init_tuya_sdk
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'. Did you mean: 'async_unload_platforms'?

**Comment by LegionSMOKEZ** [comment]
Any update to this?

**Comment by KiiDii** [comment]
> Any update to this?

Nope
